defmodule Comma.MultiPodRuntimeInventory do
  @moduledoc "Audited multi-Pod classification of local runtime coordination paths."

  @entries [
    {CommaSSH.Listener, "SSH endpoint listener", "one optional process per Pod",
     "256 connections per listener; one channel per connection",
     "PEM host key in shared Comma Postgres; socket state is local",
     "retain local listener; disconnect on Pod loss and reconnect with the same host identity"},
    {CommaSSH.Connections, "verified SSH connection handoff", "one process per Pod",
     "one monitored entry per authenticated connection; 256 connections per listener",
     "ephemeral verified-key context removed when the connection exits",
     "retain local one-claim handoff; never transfer authentication between Pods"},
    {CommaSSH.Session, "SSH account session controller", "one process per active SSH channel",
     "one serial command; 20-second channel deadline; 30-second authorization checks",
     "durable account sessions and key bindings in Comma Postgres; enrollment context is local",
     "retain connection-linked controller; reconnect resolves current account authorization"},
    {CommaSSH.Chat, "SSH Router Conversation projection",
     "one process per selected SSH workspace",
     "one subscription; 100 recent messages of at most 8000 characters; refresh at most 4 Hz",
     "ephemeral transcript over the canonical Conversation owner",
     "retain local projection; owner loss requires reconnect and never resends uncertain submissions"},
    {SalixAgent.RoundConfigPrewarm, "round configuration prewarm cache", "one process per Pod",
     "one ETS slot per encountered agent; 5-second freshness and 10-second default take wait; no entry-count cap or expiry sweep",
     "rebuildable local snapshots; canonical configuration remains outside the process",
     "retain local optimization; take or discard removes a slot, stale or absent results use the caller's build"},
    {SalixIM.SlackUserProfileCache, "Slack display-name cache", "one process per Pod",
     "one ETS row per encountered workspace/connect and user pair; configurable freshness defaults to 10 minutes; no entry-count cap or expiry sweep",
     "rebuildable local profiles; Slack remains the source",
     "retain local cache; expired or absent entries resolve through users.info; failed or nameless lookups are not cached"},
    {CommaWeb.IMessageRuntime, "shared product iMessage relay receiver",
     "one contender per enabled Pod",
     "one stream, at most 1 MiB per frame, serial handling, 60-second stream passes and 5-second retry, paused after three consecutive failures; one dedicated checked-out Comma DB connection on the owner",
     "PostgreSQL session advisory lock and one cursor row per operator-owned relay id",
     "checkpoint after handled/ignored events; stable Session source ids collapse replay; no progress during dependency failure"},
    {SalixAnalytics.SlackSemanticIndexer, "optional canonical semantic-index reconciliation",
     "one process per enabled Pod",
     "one 1-second timer; one indexed cursor page of at most 20 message references across retained history; failure delay 5 seconds",
     "PG search_cursors and source/publication epochs; replaceable ClickHouse components",
     "enqueue bounded historical pages in Oban; source IDs and publication fence duplicate/late builds"},
    {SalixAnalytics.SlackSemanticQueue, "optional semantic priority queue bridge",
     "one process per enabled Pod",
     "1024 local offers, 20 inserts per turn; one pending file and at most 20 reference jobs per tick; two indexed oldest-pending queries per second; prune at most 1000 terminal jobs and 1000 expired search windows per minute",
     "SalixStore.Repo Oban jobs in slack_semantic schema",
     "Oban text/media concurrency 1 each per Pod; live priority 0, history 9; cooperative history cancellation; orphan rescue accepts duplicates"},
    {SalixCluster.Ring, "derived cluster membership", "per Pod", "bounded by BEAM members",
     "local", "retain local"},
    {SalixCluster.Recovery, "periodic recovery", "one process per Pod",
     "S3 lease + per-pass page/delete/time budgets; housekeeping async off the tick path",
     "durable S3 lease/fence", "retain"},
    {SalixCluster.SessionWorkNotificationListener, "session-work PG invalidation listener",
     "one process per Salix control-Postgres Pod",
     "one LISTEN connection + bounded reconnect backoff; owner-only bounded wake admission",
     "lossy Postgres hint over durable token-fenced candidates",
     "retain subscribe-before-catch-up listener; periodic recovery owns completeness"},
    {SalixCluster.Timers, "periodic timer discovery", "one process per Pod",
     "S3 lease + bounded window", "durable S3 create-once", "retain"},
    {SalixCluster.Schedules, "periodic schedule discovery", "one process per Pod",
     "S3 lease + due window", "durable S3 CAS/create-once", "retain"},
    {SalixCalendar.Actor, "calendar actor", "per active Calendar on owner Pod",
     "one group Calendar", "Salix canonical S3 actor", "retain local actor"},
    {SalixCalendar.SourceActor, "calendar source actor",
     "per active Calendar source on owner Pod", "one Calendar source",
     "durable S3 lease + source sync CAS", "retain local actor"},
    {SalixIM.ConversationActor, "conversation actor", "per active conversation on owner Pod",
     "one conversation", "Salix canonical S3 actor", "retain local actor"},
    {"SalixIM.TaskWorkerWatch", "conversation private plain-Task Worker watch",
     "one unnamed child per active ConversationActor", "one active Task Worker",
     "epoch-keyed Messages on the owned Conversation; activity subscription and timers are local",
     "retain owner-linked private capability; reconstruct from Conversation and session activity"},
    {"SalixIM.ConversationStore", "conversation private store",
     "one unnamed child per active ConversationActor", "one conversation",
     "Salix canonical S3 physical state",
     "retain owner-linked private capability; no registration or lookup"},
    {SalixIM.ConversationGroupActor, "conversation group actor",
     "per active conversation group on owner Pod", "one bounded group collection",
     "Salix canonical S3 actor", "retain local actor"},
    {SalixIM.ConversationParticipantActor, "participant actor",
     "per active participant on owner Pod", "one participant",
     "Salix canonical Participant cursor and provider receipts", "retain local actor"},
    {"SalixIM.ConversationParticipantStore", "participant private store",
     "one unnamed child per active ConversationParticipantActor", "one participant",
     "Salix canonical Participant cursor and provider receipts",
     "retain owner-linked private capability; no registration or lookup"},
    {SalixIM.SlackRouterStatusActor, "socket/status actor", "per connected router on owner Pod",
     "one router", "ephemeral connection state", "retain local actor"},
    {SalixIM.PrivateChatStatusActor, "Telegram, WeChat and Signal typing indicator",
     "per private chat/topic on Router owner Pod",
     "32 accepted source IDs; 1024 actors per Pod; 30-minute presentation lifetime",
     "canonical Session Activity + native provider typing",
     "fail closed on owner loss; next inbound recreates presentation; no global scan"},
    {SalixIM.ProviderRuntime, "provider polling", "one process per Pod",
     "static provider set + configured task concurrency/timeout",
     "durable provider cursor + create-once event receipt",
     "retain bounded idempotent provider polling"},
    {SalixIM.ConversationSearchWorker, "conversation Task-search projection worker",
     "one process per Pod",
     "one job per tick + at most 64 one-MiB source segments and bounded projection output",
     "durable PostgreSQL queue and token-fenced claim over canonical S3 source",
     "retain bounded per-Pod worker; SKIP LOCKED partitions durable work"},
    {SalixIM.ConversationSearchDiscovery, "conversation Task-search discovery",
     "one process per Pod",
     "one Group key or at most 100 Conversation prefixes per turn + eight metadata reads",
     "durable PostgreSQL singleton lease/cursor/barrier over canonical S3 inventory",
     "retain per-Pod contender; singleton claim owns fleet-wide progress"},
    {SalixIM.Triage.Runtime, "triage admission coordinator", "one process per Pod",
     "one admission-config read per accepted receipt",
     "durable typed S3 receipts + PostgreSQL conditional Triage records",
     "retain local mode/namespace projection; admission is CAS-fenced"},
    {SalixIM.Triage.ProductEffectWorker, "triage product-effect executor", "one process per Pod",
     "configured bounded obligation batch + claim lease",
     "durable PostgreSQL obligation claim/settlement + Conversation idempotency/provider delivery",
     "retain bounded local worker over durable fenced claims; Conversation owns provider delivery"},
    {SalixIM.Triage.ReceiptRecovery, "periodic triage receipt recovery", "one process per Pod",
     "PostgreSQL lease + bounded receipt/authority pages + batch limit",
     "durable PostgreSQL lease/Triage records + typed S3 receipts",
     "retain lease-gated bounded recovery; overlapping passes after TTL are accepted"},
    {SalixIM.Triage.ClickHousePatrolWorker, "ClickHouse-only ambient Triage patrol",
     "one process per Pod",
     "bounded enabled-channel discovery + bounded due-claim batch and ClickHouse page",
     "durable PostgreSQL per-channel cursor/lease/fence + ClickHouse observations + typed v3 receipts",
     "retain local worker over durable fenced claims; expired claims are stealable and receipt identity collapses replay"},
    {SalixIM.ProviderIdentityScanLimiter, "identity fallback scan admission",
     "one process per Pod", "configured per-Pod concurrency cap",
     "advisory permits over an application-lifetime ETS table",
     "retain local capacity; per-Pod bound is the intended blast-radius unit"},
    {SalixIM.Provider.Feishu.API, "provider request queue", "one process per Pod",
     "configured request queue", "per-Pod transport capacity", "retain local capacity"},
    {SalixAnalytics.TypedSinkWorker, "telemetry batch queue", "two named processes per Pod",
     "configured queue/batch", "best-effort analytics",
     "retain best-effort; never own billing outcome"},
    # Corrected 2026-08-31: the ledger said "with local disk spill past it".
    # There is none, deliberately — the worker's moduledoc records that spilling
    # to the node's disk would trade a bounded, observable loss for an unbounded
    # one. Past the buffer it drops and counts.
    {SalixAnalytics.EventArchive.Worker, "encrypted event-archive ClickHouse writer",
     "one process per Pod, started only when archive recipients are configured",
     "bounded ETS buffer; overflow drops rather than spilling",
     "best-effort archiving; sealed items only, never plaintext",
     "retain per-Pod: each Pod archives the loops it runs, and a lost buffer leaves a seq gap that mix salix.archive.verify reports rather than silent loss. Each Pod also draws its own writer epoch, so rows from two Pods can never collide on the ReplacingMergeTree key"},
    {SalixIM.SlackMessageMirror.OutboxDrainer, "Slack message mirror outbox drainer",
     "one process per Pod, started wherever ClickHouse is configured unless slack_mirror.enabled is false",
     "one batch per tick + SKIP LOCKED claim; immediate next tick only while batches come back full",
     "durable PostgreSQL outbox; a row is deleted only after ClickHouse acknowledges it",
     "retain: the process holds nothing, so two Pods draining take different rows and a Pod dying mid-batch leaves its rows to be claimed again after the lease. The re-insert that follows is absorbed by the ReplacingMergeTree, whose key is the message and whose version derives from the message's own observable state — so the rows carry no Pod identity ON PURPOSE"},
    {SalixIM.SlackMessageMirror.BackfillRunner, "Slack history backfill scheduler",
     "one process per Pod, started wherever ClickHouse is configured unless slack_mirror.enabled is false",
     "one discovery Task + max_concurrent_passes pass Tasks per Pod; one Slack request per pace_ms per installation; one page of connects per discovery tick",
     "durable PostgreSQL ledger: per-installation due/lease rows and per-channel monotone watermarks",
     "retain: Slack rate-limits per workspace+bot, so the installation is the unit claimed and two Pods claim DISTINCT installations rather than splitting one token's budget. Channel watermarks only ever move down, so a stale walker's commit cannot lose progress; its lease is dedupe, not a fence"},
    {BridgeForTeams.Cache, "ETS cache", "one process per Pod", "bounded by active BFT reads",
     "rebuildable", "retain local"},
    {BridgeForTeams.Salix.ReadCache, "Salix read-through cache", "one process per Pod",
     "TTL/config bounded", "rebuildable", "retain local"},
    {BridgeForTeams.RateLimit, "magic-link limiter", "one process per Pod", "key/window bounded",
     "global Redis token bucket", "retain supervised Hammer.Redis; fail closed"},
    {BridgeForTeams.Salix.Reconciler, "outbox drainer", "one process per Pod",
     "DB batch + SKIP LOCKED", "durable Postgres outbox", "retain"},
    {BridgeForTeams.Salix.TenantConfigChecker, "periodic tenant check", "one process per Pod",
     "bounded organization page", "durable PostgreSQL cursor and singleton lease",
     "retain domain-specific shared claim"},
    {BridgeForTeams.EnvironmentProvisioning.Reconciler, "provision request reconciler",
     "one process per Pod", "configured active-request page + project/device cursor",
     "shared Postgres lease/fence + idempotent status projection",
     "retain one lease-fenced bounded convergence pass"},
    {BridgeForTeams.DashboardProjection.Reconciler, "projection hint queue",
     "one process per Pod", "bounded stale discovery + one project claim",
     "durable desired/completed generation and fenced lease",
     "retain mailbox as doorbell over durable backstop"},
    {BridgeForTeams.SlackHistoryOnboarding.Reconciler, "Slack-history import doorbell",
     "one process per Pod", "one active task + one replacement timer + oldest runnable row",
     "durable PostgreSQL run state, receipts, checkpoints, and derivation leases",
     "retain local doorbell; database fences own correctness and cross-Pod convergence"},
    {BridgeForTeams.EnvironmentRuntimeObserver, "runtime observation queue",
     "one process per Pod", "configured queue", "best-effort observability",
     "retain best-effort"},
    {BridgeForTeams.Observability.Pruner, "periodic retention prune", "one process per Pod",
     "one bounded relation batch", "durable singleton lease and phase cursor",
     "retain domain-specific shared claim"},
    {BridgeForTeams.StorageMetering.Reconciler, "periodic storage metering",
     "one process per Pod", "bounded project page + max_objects",
     "durable Postgres generation/claim + billing idempotency key",
     "retain domain-specific shared claim"},
    {BridgeForTeams.Salix.EventRelay, "Salix event relay", "one process per Pod",
     "bounded subscription mailbox", "events remain canonical in Salix",
     "retain local relay; reconnect from durable source"},
    {Comma.Migrations.LegacyS3Inventory, "retired S3 snapshot inventory reader",
     "explicit audit command only", "bounded legacy snapshot", "read-only; never supervised",
     "retain until separately approved physical disposition"},
    {Comma.SchemaReadiness, "Comma schema readiness proof", "one process per product Pod",
     "one exact migration version lookup at startup", "derived from Comma PostgreSQL ledger",
     "retain local readiness projection"},
    {Comma.ObanBacklogSampler, "Comma Oban backlog sampler", "one process per product Pod",
     "two fixed queues and aggregate SQL only", "best-effort low-cardinality telemetry",
     "retain local observer; never owns job state"},
    {Comma.ObanPlugins.OperationLifeline, "durable operation orphan rescuer",
     "one plugin process per product Pod", "configured stale-job batch and interval",
     "PostgreSQL operation identity + Oban leader election",
     "retain bounded leader-elected durable-job recovery"},
    {Comma.AuthChallengeStore.Redis, "Redis auth challenge adapter",
     "one supervised connection per Pod", "one auth key", "Redis-owned TTL and atomic consume",
     "retain supervised Redix; fail closed"},
    {Comma.Auth.GoogleAdapter.Oidcc.JwksRefreshGate, "Google JWKS refresh cooldown",
     "one process per Comma Pod", "one provider-wide cooldown without attacker-controlled keys",
     "ephemeral refresh throttle", "retain bounded per-Pod gate"},
    {"CommaWeb.TelegramOIDC.ProviderOwner", "Telegram OIDC provider lifecycle",
     "one process per OIDC-enabled Comma Pod",
     "one linked SDK worker or one restart timer; 5-10 second retry delay",
     "ephemeral discovery/JWKS cache and local recovery state",
     "retain bounded per-Pod owner; no cross-Pod coordination or durable binding authority"},
    {SalixWeb.ConnectorTaskAdmission, "connector admission", "per Pod atomics",
     "configured local capacity", "ephemeral capacity", "retain local"},
    {SalixWeb.CloudVM.ArchiveGC, "retired Cloud VM archive cleanup", "one process per Pod",
     "one indexed Group Workload and at most 50 S3 objects per 15-second pass",
     "durable Group Workload GC intent and exact archive generation prefix",
     "retain bounded local worker; duplicate Pod passes can retry S3 deletes, and the Workload guards the current generation"},
    {SalixEnv.ExecActivity, "execution activity", "per Pod ETS", "active local executions",
     "ephemeral UI label", "retain local"},
    {SalixAgent.SubscriptionWorker, "subscription SDK subprocess", "one process per Pod",
     "64 active calls; one unacknowledged 64 KiB chunk per call; 120-second deadline",
     "ephemeral transport; account credentials remain in PostgreSQL",
     "retain local subprocess; fail active calls on exit and restart on the next request"},
    {SalixWeb.SubscriptionRuntimeWorker, "subscription runtime delivery", "one process per Pod",
     "four deliveries per batch; ten-second delay; sixty-second task deadline; three failed attempts",
     "PostgreSQL bindings with SKIP LOCKED and ninety-second claim leases",
     "retain bounded reconciliation; reconnect, access, or operator retry reactivates exhausted delivery"},
    {SalixAgent.SubscriptionQuotaWorker, "subscription quota polling", "one process per Pod",
     "four due accounts per pass; 30-second interval; 100 expired OAuth attempts per cleanup",
     "PostgreSQL account rows and next_poll_at claims through SKIP LOCKED",
     "retain bounded database-claimed polling; expired claims permit another Pod to resume"},
    {SalixAgent.RuntimeFiles, "bounded schema-key atom conversion", "per decode",
     "closed field set", "not node identity", "retain; reject untrusted keys"},
    {SalixAgent.SkillStore, "bounded schema-key atom conversion", "per decode",
     "closed field set", "not node identity", "retain; reject untrusted keys"},
    {SalixAgent.RouterRequestMonitor, "Router request-start observation", "one process per Pod",
     "1024 registered owners and pending sessions; 1000 pending source IDs per session; one 15-second sampling timer",
     "ephemeral best-effort telemetry; owner/observer restart loses observations",
     "retain local observer; no actor RPC or durable scans; new Router traffic restores registration"},
    {SalixAgent.ActivitySurface, "agent activity projection", "one process per Pod",
     "active agent-owner sessions", "ephemeral projection",
     "retain agent-owner-local surface; read through owner-routed snapshot"},
    {SalixAgent.DraftSurface, "participant draft projection", "one process per Pod",
     "active agent-owner sessions", "ephemeral projection",
     "retain agent-owner-local surface; read through owner-routed snapshot"},
    {SalixAgent.ExecutionSurface, "session execution measurements", "one process per Pod",
     "at most 4096 observations; completed observations expire after three minutes",
     "ephemeral diagnostic projection, never execution authority",
     "retain owner-local surface; read through exact owner-routed snapshot"},
    {SalixAgent.Decide.Limits, "decision request rate admission", "one process per Pod",
     "60 calls per minute and four per second per Tenant/Group; bucket timers expire after at most two minutes; no Group-count cap",
     "ephemeral local counters reset on restart",
     "retain independent Tenant/Group budgets per Pod; no node-total or cluster-wide quota"},
    {SalixAgent.DependencyAdmission, "dependency admission", "one process per Pod",
     "configured global and per-tenant active dependency jobs",
     "ephemeral owner- and task-monitored admission tokens",
     "retain bounded local capacity; never consume the core task supervisor"},
    {SalixAgent.OwnershipCell, "agent runtime ownership cell", "one process per Pod",
     "one ETS row per agent with live runtime on this Pod; cleared on clean lease release and on full superseded-runtime teardown",
     "ephemeral mirror of the fenced durable root head; safety stays with the S3 ETag CAS and per-session runtime_epoch stamps",
     "retain local fast-path mirror; never authoritative for ownership"},
    {SalixAgent.DependencyRunner, "background dependency registry", "one process per Pod",
     "dependency admission caps plus keyed single-flight jobs",
     "ephemeral owner-held handles; durable work remains domain-owned",
     "retain local background owner; timeout or cancel exact jobs"},
    {SalixIM.ConversationLogRecovery, "Conversation log recovery", "one process per Pod",
     "one-second due-index polling; eight tasks; at most 200 Participant slots per candidate",
     "Postgres coalesces prepared log tails; Session progress and provider receipts remain authoritative",
     "retain bounded indexed recovery; no Conversation directory traversal"},
    {SalixAgent.SessionWorkRecovery, "session-work recovery worker", "one process per Pod",
     "single-flight bounded eager/deferred pages + per-page wake budget + 1,024 exact-wake queue",
     "token-fenced durable session-work discovery; shared Recovery owns lease/ticker",
     "retain local domain worker; never own a second scheduler or lease"},
    {SalixAgent.ExternalWorkerOperationReconciler, "external-worker operation recovery",
     "one process per Pod", "bounded tenant/provider window + claim lease",
     "durable Postgres operation row + claim/lease", "retain bounded claim-fenced recovery"},
    {SalixAgent.ExternalSessionActor, "external session actor", "per owned session",
     "one session", "canonical session state outside process", "retain owner-partitioned actor"},
    {SalixAgent.SessionHistory.Scheduler, "tenant-fair history admission", "one process per Pod",
     "1,024 queued identities; four active jobs total; two active jobs per tenant",
     "advisory local queue; canonical source and PG projection remain durable",
     "retain Pod-local session serialization; cross-Pod overlap remains row-locked and idempotent"},
    {SalixAgent.SessionHistory.Recent, "recent session history indexing",
     "four processes per Pod",
     "shared 1,024-entry identity queue; one 32-record/128-chunk tail per lane",
     "canonical S3 originals; row-locked idempotent PostgreSQL projection",
     "retain fixed recent lanes; shared admission prioritizes queued recent work over maintenance"},
    {SalixAgent.SessionHistory.Worker, "session history projection worker", "one process per Pod",
     "1,024 exact identity hints; bounded source pages and 128-chunk batches",
     "canonical S3 originals; PostgreSQL row-locked progress; confirmed ClickHouse copies",
     "retain bounded idempotent projection; local hints are advisory and durable discovery repairs loss"},
    {SalixAgent.SessionResidency, "session residency pressure controller", "one process per Pod",
     "one ETS row and monitor per resident actor; bounded CLOCK scan per tick; memory-pressure admission, not a hard actor-count cap",
     "ephemeral local residency and caller pins; canonical session state remains outside the process",
     "retain Pod-local pressure sampling and idle-only eviction; never authoritative for ownership"},
    {SalixAgent.InternalSessionActor, "internal session actor", "per owned session",
     "one session", "canonical session state outside process", "retain owner-partitioned actor"},
    {SalixAgent.AgentRoleActor, "agent role actor", "per owned router, worker or meeting agent",
     "one agent; one conversation-source task and tracked delivery staging tasks",
     "canonical agent state outside process", "retain owner-partitioned actor"},
    {SalixAgent.PreparedBlobCleanup, "prepared blob cleanup", "one process per Pod",
     "configured interval and local prepared blobs", "temporary local files",
     "retain local cleanup"},
    {SalixAgent.Loops.Host, "spinfoam background-loop runtime child", "one process per Pod",
     "one child process; 40 outstanding JSON-RPC requests plus a queue; host.call through DependencyJob with the guest deadline; resident objects capped by :spinfoam_max_objects; respawn backoff at most 5 per hour",
     "ephemeral child state; Loop records, checkpoints and incarnations live in PostgreSQL agent_loops",
     "retain local runtime; child loss unloads every object and the Reconciler reloads adopted Loops from their checkpoints"},
    {SalixAgent.Loops.Reconciler, "background-loop ownership follower", "one process per Pod",
     "one adoption task per locally claimed Agent; 60-second ownership sweep over local Registry agents plus one page of at most 200 stranded active Loops whose owner Server is started through Placement; releases on Server DOWN",
     "follows SalixAgent.Server claims (HeadCommit/Lease); incarnation fence in agent_loops",
     "retain local follower; a Loop runs only on its Agent's current owner Pod and a stale incarnation is fenced at every write"},
    {SalixAgent.SSH.TailcatGateway, "Tailcat gateway subprocess for outbound SSH",
     "one process per Pod",
     "one child process started on first dial; one Tailcat client with a new ephemeral node key per open Tailcat SSH connection, bounded by the SSH session limit per Agent session; 16 KiB request frames; 15-second dial deadline",
     "ephemeral child, socket, tunnels and node keys; nothing stored",
     "retain local runtime; child exit ends its SSH connections and the next dial starts a new child"},
    {SalixAgent.SSH.Session, "outbound SSH PTY session",
     "per open ssh.open session, under its session actor's SSH supervisor",
     "4 open sessions per Agent session; one OTP SSH connection and PTY channel; 1 MiB output ring and one terminal screen; 30-minute idle and 8-hour lifetime limits",
     "ephemeral connection and output; never reconnected or replayed",
     "end with the session actor; the Agent opens a new session"},
    {SalixEnv.FrameStream, "frame stream", "per active local stream", "one bounded stream",
     "ephemeral transport", "retain local"},
    {SalixEnv.Transfer.StreamReceiver, "transfer receiver", "per active local transfer",
     "one bounded transfer", "ephemeral transport", "retain local"},
    {SalixEnv.Transfer.StreamSender, "transfer sender", "per active local transfer",
     "one bounded transfer", "ephemeral transport", "retain local"},
    {SalixEnv.Transfer.Tokens, "transfer token registry", "one process per Pod",
     "TTL-bounded local transfers", "ephemeral authorization token",
     "retain local; never use as cross-Pod bearer authority"},
    {SalixEnv.ComputeReconciler, "compute workload reconciler", "one process per Pod",
     "fixed workload batch × provider command budget per pass",
     "durable Postgres workload generation and provider idempotency",
     "retain bounded CAS-fenced convergence"},
    {SalixWeb.CloudVM.ConnectorSession, "Cloud VM Connector protocol adapter",
     "per active local VM", "one carrier with shared Connector request and stream limits",
     "ephemeral transport", "delegate to ConnectorSocket; retain connection generation fencing"},
    {SalixEnv.WriteFrameSink, "write frame sink", "per active local sink", "one bounded stream",
     "ephemeral transport", "retain local"},
    {SalixMCP.Builtins, "built-in MCP seeder", "one process per Pod", "fixed catalog",
     "canonical system-definition upsert", "retain idempotent fixed-catalog seeder"},
    {SalixMCP.Connection, "MCP connection", "per active local connection", "one connection",
     "ephemeral transport", "retain local"},
    {SalixMeet.CalendarAutojoin, "calendar autojoin", "one process per Pod",
     "max groups/events/concurrency per pass",
     "global S3 lease + CAS projection + durable join-dispatch outbox",
     "retain globally lease-fenced bounded convergence"},
    {SalixMeet.Delivery, "meeting delivery sweep", "one process per Pod",
     "S3 lease + full meet-state scan per pass", "durable S3 lease + per-meeting CAS work claims",
     "retain globally lease-fenced sweep"},
    {SalixMeet.MeetingGroupProjectionAuditor, "meeting group projection drift auditor",
     "one process per Pod", "one bounded S3 meeting page per tick + configured page size",
     "read-only comparison of sealed S3 meeting truth against PostgreSQL projection",
     "retain local read-only auditor; repair stays in a later online release"},
    {SalixMeet.Meeting, "meeting runtime", "per active meeting", "one meeting",
     "canonical meeting artifacts", "retain owner-partitioned actor"},
    {SalixStore.Convergence.Worker, "store convergence worker", "one process per Pod",
     "pages_per_run × page_size", "durable S3 cursor + CAS-fenced progress/completion",
     "retain CAS-fenced bounded convergence"},
    {SalixStore.AgentVMMSettlementSweeper, "Agent VMM command deadline settlement",
     "one process per Pod", "fixed command page + indexed deadline window",
     "durable command rows + SKIP LOCKED settlement", "retain bounded database-claimed recovery"},
    {SalixStore.SlackRouterThreadParticipationSweeper,
     "Slack Router participation expiry cleanup", "one process per Pod",
     "fixed hourly pass of at most 1,000 indexed expired rows",
     "rebuildable Postgres cache rows + SKIP LOCKED cleanup",
     "retain bounded concurrent cleanup; live reads enforce expiry independently"},
    {SalixStore.Ids, "distributed id state", "one process per Pod",
     "10-bit ordinal/reserved worker partition", "worker id encoded in every Snowflake",
     "retain manifest-partitioned generator; unknown/duplicate mapping fails closed"},
    {SalixStore.Inflight.Poller, "store in-flight gauge publisher", "one process per Pod",
     "fixed-cadence scan of a pod-local ETS table with a fixed operation vocabulary",
     "pod-local observational state only (application-master-owned ETS)",
     "retain local telemetry poller"},
    {SalixStore.TenantApiKeyReadiness, "salix tenant-api-key cutover readiness proof",
     "one process per salix Pod", "one cutover-marker lookup at startup",
     "derived from the salix PostgreSQL cutover marker", "retain local readiness projection"},
    {SalixStore.ProviderCredentialsReadiness,
     "salix provider-credentials cutover readiness proof", "one process per salix Pod",
     "one cutover-marker lookup at startup", "derived from the salix PostgreSQL cutover marker",
     "retain local readiness projection"},
    {SalixStore.TenantConfigsReadiness, "salix tenant-configs cutover readiness proof",
     "one process per salix Pod", "one cutover-marker lookup at startup",
     "derived from the salix PostgreSQL cutover marker", "retain local readiness projection"},
    {SalixStore.SchedulesReadiness, "salix schedules cutover readiness proof",
     "one process per salix Pod", "one cutover-marker lookup at startup",
     "derived from the salix PostgreSQL cutover marker", "retain local readiness projection"},
    {SalixStore.OAuthAppsReadiness, "salix oauth-apps cutover readiness proof",
     "one process per salix Pod", "one cutover-marker lookup at startup",
     "derived from the salix PostgreSQL cutover marker", "retain local readiness projection"},
    {SalixStore.MeetingGroupProjectionReadiness,
     "salix meeting-group projection feature readiness proof", "one process per salix Pod",
     "one cutover-marker lookup at startup", "derived from the salix PostgreSQL cutover marker",
     "retain local feature gate; never block the first projection-writer rollout"},
    {SalixStore.S3.Fake, "test S3 fake", "test process only", "test fixture bounded",
     "non-production", "exclude from production topology; retain test helper"},
    {Salix.Control.PluginCatalogCache, "plugin catalog cache", "one process per Pod",
     "one ETS row per group read on this Pod; 60-second freshness; expired rows swept every 60 seconds",
     "rebuildable cache; S3 catalog records remain the source",
     "retain local cache; writes invalidate every ring Pod and missed invalidations expire"},
    {SalixWeb.ConnectorDisconnectQueue, "connector disconnect queue", "one process per Pod",
     "configured queued + active + retry capacity",
     "generation-fenced local cleanup hint; canonical connector state is external",
     "retain bounded local cleanup queue; never own durable connector state"},
    {SalixWeb.ConnectorExternalEventCoordinator, "connector external-event coordinator",
     "one process per Pod; calls route to the SalixCluster.Ring owner",
     "configured retained count/bytes plus per-tenant and per-lane queue/cache/deadline caps",
     "external-session event-id CAS is the durable safety backstop",
     "retain owner-routed bounded detached admission and cache"},
    {SalixWeb.SiteAPI, "site API state owner", "one process per Pod", "TTL cache keys",
     "rebuildable local configuration cache", "retain local cache; global limiter is separate"},
    {SalixWeb.SiteAPI.State, "site API configuration cache", "one process per Pod",
     "TTL-bounded site configuration cache", "rebuildable local configuration cache",
     "retain local cache; no quota ownership"},
    {BillingCommerce.CycleScheduler, "billing cycle scheduler", "one process per Pod",
     "configured due-cycle page and interval", "durable cycle row lock + grant idempotency key",
     "retain bounded row-locked idempotent scheduler"},
    {BillingCore.FeeControl.Server, "billing fee control", "one process per Pod",
     "TTL-bounded local cache + bounded PostgreSQL probe",
     "PostgreSQL balance/entitlement authority; per-Pod cache only",
     "retain local cache; never own billing quota"},
    {BillingCore.Metering.PendingChargeWorker, "pending charge worker", "one process per Pod",
     "configured batch and interval", "durable rows + SKIP LOCKED + charge idempotency",
     "retain bounded database-claimed replay"},
    {CommaLog, "structured log dispatcher", "one process per Pod", "configured local mailbox",
     "best-effort observability", "retain local"},
    {SystemsObservability.EctoHandler, "Ecto telemetry handler", "one process per Pod",
     "configured local telemetry series", "best-effort observability", "retain local"},
    {SystemsObservability.HistogramReporter, "histogram reporter", "one process per Pod",
     "configured local histogram series", "best-effort observability", "retain local"},
    {SystemsObservability.Runtime, "runtime telemetry reporter", "one process per Pod",
     "configured local telemetry series", "best-effort observability", "retain local"}
  ]

  def entries do
    Enum.map(@entries, fn {module_name, kind, cardinality, bound, durability, disposition} ->
      %{
        module_name: normalize_module_name(module_name),
        kind: kind,
        cardinality: cardinality,
        bound: bound,
        durability: durability,
        fan_out:
          if(String.contains?(cardinality, "per Pod"),
            do: "multiplies with replica count",
            else: "partitioned by local owner or bounded identity"
          ),
        disposition: disposition
      }
    end)
  end

  def module_names, do: Enum.map(entries(), & &1.module_name)

  defp normalize_module_name(module_name) when is_binary(module_name), do: module_name
  defp normalize_module_name(module) when is_atom(module), do: inspect(module)
end
