CREATE TABLE IF NOT EXISTS {{database}}.llm_call_events (
  dedup String,
  source String,
  source_key String,
  version UInt64,
  event_date Date,
  metered_at String,
  created_at String,
  entrypoint String,
  surface String,
  billing_account_id String,
  product_owner_type String,
  product_owner_id String,
  tenant_id String,
  group_id String,
  actor_type String,
  resource_kind String,
  provider Nullable(String),
  sku Nullable(String),
  model Nullable(String),
  status String,
  charge_status String,
  prompt_tokens UInt64,
  completion_tokens UInt64,
  total_tokens UInt64,
  cache_read_input_tokens UInt64,
  cache_write_input_tokens UInt64,
  quality String,
  trace_id Nullable(String),
  request_id Nullable(String),
  salix_agent_id Nullable(String),
  session_id Nullable(String),
  turn_id Nullable(String),
  round_id Nullable(String),
  stale Bool
) ENGINE = ReplacingMergeTree(version)
ORDER BY (source, source_key);

CREATE TABLE IF NOT EXISTS {{database}}.vm_usage_events (
  dedup String,
  source String,
  source_key String,
  version UInt64,
  event_date Date,
  metered_at String,
  created_at String,
  entrypoint String,
  surface String,
  billing_account_id String,
  product_owner_type String,
  product_owner_id String,
  tenant_id String,
  group_id String,
  actor_type String,
  resource_kind String,
  provider Nullable(String),
  sku Nullable(String),
  status String,
  charge_status String,
  interval_start Nullable(String),
  interval_end Nullable(String),
  duration_seconds UInt64,
  env_id Nullable(String),
  sprite_name Nullable(String),
  quality String
) ENGINE = ReplacingMergeTree(version)
ORDER BY (source, source_key);

CREATE TABLE IF NOT EXISTS {{database}}.storage_usage_events (
  dedup String,
  source String,
  source_key String,
  version UInt64,
  event_date Date,
  metered_at String,
  created_at String,
  entrypoint String,
  surface String,
  billing_account_id String,
  product_owner_type String,
  product_owner_id String,
  tenant_id String,
  group_id String,
  actor_type String,
  resource_kind String,
  provider Nullable(String),
  sku Nullable(String),
  storage_tier Nullable(String),
  status String,
  charge_status String,
  bucket Nullable(String),
  prefix Nullable(String),
  bytes UInt64,
  object_count UInt64,
  sample_window_seconds UInt64,
  byte_seconds UInt64,
  tier_source Nullable(String),
  tier_cache_hit Bool,
  quality String
) ENGINE = ReplacingMergeTree(version)
ORDER BY (source, source_key);

CREATE TABLE IF NOT EXISTS {{database}}.billing_charge_events (
  dedup String,
  source String,
  source_key String,
  version UInt64,
  event_date Date,
  metered_at String,
  created_at String,
  entrypoint String,
  surface String,
  billing_account_id String,
  product_owner_type String,
  product_owner_id String,
  tenant_id String,
  group_id String,
  actor_type String,
  resource_kind String,
  provider Nullable(String),
  sku Nullable(String),
  status String,
  charge_status String,
  pricing_status String,
  calculated_credits UInt64,
  charged_credits UInt64,
  grace_credits UInt64,
  balance_after Nullable(Int64),
  pricing_components String,
  credits_per_usd UInt64
) ENGINE = ReplacingMergeTree(version)
ORDER BY (source, source_key);

CREATE TABLE IF NOT EXISTS {{database}}.fee_control_checks (
  dedup String,
  source String,
  source_key String,
  version UInt64,
  event_date Date,
  metered_at String,
  created_at String,
  entrypoint String,
  surface String,
  billing_account_id String,
  product_owner_type String,
  product_owner_id String,
  tenant_id String,
  group_id String,
  actor_type String,
  resource_kind String,
  provider Nullable(String),
  sku Nullable(String),
  status String,
  mode String,
  cache_hit Bool,
  cache_age_ms Nullable(UInt64),
  cache_ttl_ms Nullable(UInt64),
  query_performed Bool,
  query_duration_ms Nullable(UInt64),
  result_source String,
  would_block Bool,
  would_exceed Bool,
  balance_snapshot Nullable(Int64),
  trace_id Nullable(String),
  log_correlation_id Nullable(String)
) ENGINE = ReplacingMergeTree(version)
ORDER BY (source, source_key);
