defmodule SalixAgent.AgentActor do
  @moduledoc """
  Owner-routed entry points for one agent's agent-level work.

  Every function resolves the agent owner node through AgentServer placement
  and runs its `_local` counterpart there. Work that must be ordered per agent
  goes to the agent's `SalixAgent.AgentRoleActor`; stateless session commands
  and configuration reads run in bounded reply tasks on the owner node.
  Distributed routing, leases, and placement belong to AgentServer; deliveries
  commit durably into session ledgers at deliver time (A2, rpc-direct-delivery.md).
  """

  alias SalixAgent.AgentActor.SessionCommand
  alias SalixAgent.{AgentReplyTask, AgentRoleActor, RoundConfig}

  @type agent_record :: %{optional(String.t()) => term()}
  @type inbox_entry :: map()
  @type wake_target :: %{runtime: :internal | :external, session_id: String.t()}

  @roles ~w(router worker meeting)

  @doc """
  Replace a Router agent's canonical internal session on its current owner.

  `expected_session_id` is an application-level fence for response-loss retries
  and stale operator views. The target id is generated by the owner and cannot
  be supplied by the caller.
  """
  @spec switch_router_session(String.t(), String.t(), String.t(), keyword()) ::
          {:ok, map()} | {:error, term()}
  def switch_router_session(agent_id, tenant_id, expected_session_id, opts \\ [])
      when is_binary(agent_id) and is_binary(tenant_id) and
             is_binary(expected_session_id) and is_list(opts) do
    with {:ok, _agent} <- SalixAgent.Control.get(agent_id, tenant_id) do
      route_to_owner(agent_id, :switch_router_session_local, [
        agent_id,
        tenant_id,
        expected_session_id,
        opts
      ])
    end
  end

  @doc false
  def switch_router_session_local(agent_id, tenant_id, expected_session_id, opts \\ [])
      when is_binary(agent_id) and is_binary(tenant_id) and
             is_binary(expected_session_id) and is_list(opts) do
    timeout = Keyword.get(opts, :timeout, :infinity)

    with {:ok, agent} <- SalixAgent.Control.get(agent_id, tenant_id),
         :ok <- require_role(agent, "router"),
         {:ok, pid} <- ensure_started(agent) do
      AgentRoleActor.switch_canonical_session(pid, expected_session_id, timeout)
    end
  end

  @doc """
  Read the exact Session Activity and transient presentation surfaces on the
  agent owner node.

  Activity and draft remain ephemeral owner-local state. Callers on a
  Conversation/Participant owner must route this snapshot instead of reading
  their own Pod's ETS tables. This owner-routed invalidation/read contract
  refines `tla/salix/ParticipantRealtimeSubscription.tla`.
  """
  @spec participant_realtime_snapshot(String.t(), String.t(), keyword()) ::
          {:ok, map()} | {:error, term()}
  def participant_realtime_snapshot(agent_id, session_id, opts \\ [])
      when is_binary(agent_id) and is_binary(session_id) and is_list(opts) do
    opts = Keyword.put_new(opts, :process_on_init, false)

    # Routing and the canonical activity read resolve the same control
    # record; one scope serves the snapshot from a single read.
    SalixStore.ReadScope.run(fn ->
      route_to_owner(agent_id, :participant_realtime_snapshot_local, [
        agent_id,
        session_id,
        opts
      ])
    end)
  end

  @doc false
  def participant_realtime_snapshot_local(agent_id, session_id, _opts \\ [])
      when is_binary(agent_id) and is_binary(session_id) do
    with {:ok, canonical} <- SalixAgent.Runtime.get_session_activity(agent_id, session_id) do
      {:ok,
       %{
         "canonical" => canonical,
         "activity" => SalixAgent.ActivitySurface.get_session(agent_id, session_id),
         "draft" => SalixAgent.DraftSurface.get(agent_id, session_id)
       }}
    end
  end

  # Private history overlay; distinct from Participant public status/draft.
  def execution_history_snapshot(agent_id, session_id) do
    route_to_owner(agent_id, :execution_history_snapshot_local, [
      agent_id,
      session_id,
      [process_on_init: false, timeout: 5_000]
    ])
  end

  def execution_history_snapshot_local(agent_id, session_id, _opts) do
    {:ok, SalixAgent.ExecutionSurface.get(agent_id, session_id)}
  end

  @spec execute_session_tool(String.t(), String.t(), String.t(), map(), keyword()) ::
          {:ok, map()} | {:error, term()}
  def execute_session_tool(agent_id, session_id, tool_name, attrs, opts \\ [])
      when is_binary(agent_id) and is_binary(session_id) and is_binary(tool_name) and
             is_map(attrs) do
    route_to_owner(agent_id, :execute_session_tool_local, [
      agent_id,
      session_id,
      tool_name,
      attrs,
      opts
    ])
  end

  @doc false
  def execute_session_tool_local(agent_id, session_id, tool_name, attrs, opts \\ [])
      when is_binary(agent_id) and is_binary(session_id) and is_binary(tool_name) and
             is_map(attrs) do
    run_command(agent_id, opts, fn _agent ->
      SessionCommand.execute_session_tool(agent_id, session_id, tool_name, attrs)
    end)
  end

  @spec complete_async_tool_call(String.t(), String.t(), String.t(), map(), map(), keyword()) ::
          {:ok, map()} | {:error, term()}
  def complete_async_tool_call(agent_id, session_id, tool_call_id, result, meta, opts \\ [])
      when is_binary(agent_id) and is_binary(session_id) and is_binary(tool_call_id) and
             is_map(result) and is_map(meta) do
    route_to_owner(agent_id, :complete_async_tool_call_local, [
      agent_id,
      session_id,
      tool_call_id,
      result,
      meta,
      opts
    ])
  end

  @doc false
  def complete_async_tool_call_local(agent_id, session_id, tool_call_id, result, meta, opts \\ [])
      when is_binary(agent_id) and is_binary(session_id) and is_binary(tool_call_id) and
             is_map(result) and is_map(meta) do
    run_command(agent_id, opts, fn _agent ->
      SessionCommand.complete_async_tool_call(agent_id, session_id, tool_call_id, result, meta)
    end)
  end

  @spec update_async_tool_call_progress(String.t(), String.t(), String.t(), map(), keyword()) ::
          {:ok, map()} | {:error, term()}
  def update_async_tool_call_progress(agent_id, session_id, tool_call_id, progress, opts \\ [])
      when is_binary(agent_id) and is_binary(session_id) and is_binary(tool_call_id) and
             is_map(progress) do
    route_to_owner(agent_id, :update_async_tool_call_progress_local, [
      agent_id,
      session_id,
      tool_call_id,
      progress,
      opts
    ])
  end

  @doc false
  def update_async_tool_call_progress_local(
        agent_id,
        session_id,
        tool_call_id,
        progress,
        opts \\ []
      )
      when is_binary(agent_id) and is_binary(session_id) and is_binary(tool_call_id) and
             is_map(progress) do
    timeout = Keyword.get(opts, :timeout, :infinity)

    with {:ok, agent} <- SalixAgent.Control.get_record(agent_id),
         :ok <- require_role(agent) do
      SessionCommand.update_async_tool_call_progress(
        agent_id,
        session_id,
        tool_call_id,
        progress,
        timeout: timeout
      )
    end
  end

  @spec commit_connector_event(map(), map(), keyword()) :: {:ok, map()} | {:error, term()}
  def commit_connector_event(%{"agent_id" => agent_id} = capability, params, opts \\ [])
      when is_binary(agent_id) and is_map(params) do
    route_to_owner(agent_id, :commit_connector_event_local, [capability, params, opts])
  end

  @doc false
  def commit_connector_event_local(
        %{"agent_id" => agent_id} = capability,
        params,
        opts \\ []
      )
      when is_binary(agent_id) and is_map(params) do
    run_command(agent_id, opts, fn _agent ->
      SessionCommand.commit_connector_event(capability, params)
    end)
  end

  @spec accept_external_session(String.t(), String.t(), map(), keyword()) ::
          {:ok, :accepted | :stale, map()} | {:error, term()}
  def accept_external_session(agent_id, session_id, attrs, opts \\ [])
      when is_binary(agent_id) and is_binary(session_id) and is_map(attrs) do
    route_to_owner(agent_id, :accept_external_session_local, [
      agent_id,
      session_id,
      attrs,
      opts
    ])
  end

  @doc false
  def accept_external_session_local(agent_id, session_id, attrs, opts \\ [])
      when is_binary(agent_id) and is_binary(session_id) and is_map(attrs) do
    run_command(agent_id, opts, fn _agent ->
      SessionCommand.accept_external_session(agent_id, session_id, attrs)
    end)
  end

  @spec begin_external_session(String.t(), String.t(), String.t(), map(), keyword()) ::
          {:ok, map()} | {:error, term()}
  def begin_external_session(agent_id, session_id, tenant_id, runtime, opts \\ [])
      when is_binary(agent_id) and is_binary(session_id) and is_binary(tenant_id) and
             is_map(runtime) do
    route_to_owner(agent_id, :begin_external_session_local, [
      agent_id,
      session_id,
      tenant_id,
      runtime,
      opts
    ])
  end

  @doc false
  def begin_external_session_local(agent_id, session_id, tenant_id, runtime, opts \\ [])
      when is_binary(agent_id) and is_binary(session_id) and is_binary(tenant_id) and
             is_map(runtime) do
    run_command(agent_id, opts, fn _agent ->
      SessionCommand.begin_external_session(agent_id, session_id, tenant_id, runtime)
    end)
  end

  @spec update_external_session(String.t(), String.t(), map(), keyword()) ::
          {:ok, map()} | {:error, term()}
  def update_external_session(agent_id, session_id, attrs, opts \\ [])
      when is_binary(agent_id) and is_binary(session_id) and is_map(attrs) do
    route_to_owner(agent_id, :update_external_session_local, [agent_id, session_id, attrs, opts])
  end

  @doc false
  def update_external_session_local(agent_id, session_id, attrs, opts \\ [])
      when is_binary(agent_id) and is_binary(session_id) and is_map(attrs) do
    run_command(agent_id, opts, fn _agent ->
      SessionCommand.update_external_session(agent_id, session_id, attrs)
    end)
  end

  @spec complete_external_session(String.t(), String.t(), map(), keyword()) ::
          {:ok, map()} | {:error, term()}
  def complete_external_session(agent_id, session_id, attrs \\ %{}, opts \\ [])
      when is_binary(agent_id) and is_binary(session_id) and is_map(attrs) do
    route_to_owner(agent_id, :complete_external_session_local, [
      agent_id,
      session_id,
      attrs,
      opts
    ])
  end

  @doc false
  def complete_external_session_local(agent_id, session_id, attrs, opts \\ [])
      when is_binary(agent_id) and is_binary(session_id) and is_map(attrs) do
    run_command(agent_id, opts, fn _agent ->
      SessionCommand.complete_external_session(agent_id, session_id, attrs)
    end)
  end

  @spec fail_external_session(String.t(), String.t(), term(), map(), keyword()) ::
          {:ok, map()} | {:error, term()}
  def fail_external_session(agent_id, session_id, reason, attrs \\ %{}, opts \\ [])
      when is_binary(agent_id) and is_binary(session_id) and is_map(attrs) do
    route_to_owner(agent_id, :fail_external_session_local, [
      agent_id,
      session_id,
      reason,
      attrs,
      opts
    ])
  end

  @doc false
  def fail_external_session_local(agent_id, session_id, reason, attrs \\ %{}, opts \\ [])
      when is_binary(agent_id) and is_binary(session_id) and is_map(attrs) do
    run_command(agent_id, opts, fn _agent ->
      SessionCommand.fail_external_session(agent_id, session_id, reason, attrs)
    end)
  end

  @spec append_external_event(String.t(), String.t(), map(), keyword()) ::
          {:ok, map(), map()} | {:error, term()}
  def append_external_event(agent_id, session_id, attrs, opts \\ [])
      when is_binary(agent_id) and is_binary(session_id) and is_map(attrs) do
    route_to_owner(agent_id, :append_external_event_local, [agent_id, session_id, attrs, opts])
  end

  @doc false
  def append_external_event_local(agent_id, session_id, attrs, opts \\ [])
      when is_binary(agent_id) and is_binary(session_id) and is_map(attrs) do
    run_command(agent_id, opts, fn _agent ->
      SessionCommand.append_external_event(agent_id, session_id, attrs)
    end)
  end

  @spec commit_external_session_events(String.t(), String.t(), [map()], keyword()) ::
          {:ok, map()} | {:error, term()}
  def commit_external_session_events(agent_id, session_id, events, opts \\ [])
      when is_binary(agent_id) and is_binary(session_id) and is_list(events) do
    route_to_owner(agent_id, :commit_external_session_events_local, [
      agent_id,
      session_id,
      events,
      opts
    ])
  end

  @doc false
  def commit_external_session_events_local(agent_id, session_id, events, opts \\ [])
      when is_binary(agent_id) and is_binary(session_id) and is_list(events) do
    run_command(agent_id, opts, fn _agent ->
      SessionCommand.commit_external_session_events(agent_id, session_id, events)
    end)
  end

  @spec stage_external_delivery(String.t(), String.t(), map(), keyword()) ::
          {:ok, :external} | {:error, term()}
  def stage_external_delivery(agent_id, session_id, delivery, opts \\ [])
      when is_binary(agent_id) and is_binary(session_id) and is_map(delivery) do
    route_to_owner(agent_id, :stage_external_delivery_local, [
      agent_id,
      session_id,
      delivery,
      opts
    ])
  end

  @doc false
  def stage_external_delivery_local(agent_id, session_id, delivery, opts \\ [])
      when is_binary(agent_id) and is_binary(session_id) and is_map(delivery) do
    run_command(agent_id, opts, fn agent ->
      with {:ok, session_id, delivery} <- external_delivery_target(agent, session_id, delivery) do
        SessionCommand.stage_external_delivery(agent_id, session_id, delivery)
      end
    end)
  end

  @spec consult_worker_session(String.t(), String.t(), String.t(), String.t(), keyword()) ::
          {:ok, map()} | {:error, term()}
  def consult_worker_session(agent_id, session_id, question, request_id, opts \\ [])
      when is_binary(agent_id) and is_binary(session_id) and is_binary(question) and
             is_binary(request_id) do
    route_to_owner(agent_id, :consult_worker_session_local, [
      agent_id,
      session_id,
      question,
      request_id,
      opts
    ])
  end

  @doc false
  def consult_worker_session_local(agent_id, session_id, question, request_id, opts \\ [])
      when is_binary(agent_id) and is_binary(session_id) and is_binary(question) and
             is_binary(request_id) do
    with {:ok, %{"role" => "worker"}} <- SalixAgent.Control.get_record(agent_id) do
      AgentReplyTask.call(
        fn ->
          SessionCommand.consult_worker_session(agent_id, session_id, question, request_id, opts)
        end,
        Keyword.get(opts, :timeout, :infinity)
      )
    else
      {:ok, _agent} -> {:error, :not_worker}
      {:error, _} = error -> error
    end
  end

  @spec runtime_session_config(String.t(), map(), keyword()) :: {:ok, map()} | {:error, term()}
  def runtime_session_config(agent_id, attrs \\ %{}, opts \\ [])
      when is_binary(agent_id) and is_map(attrs) do
    route_to_owner(agent_id, :runtime_session_config_local, [agent_id, attrs, opts])
  end

  @doc false
  def runtime_session_config_local(agent_id, attrs \\ %{}, opts \\ [])
      when is_binary(agent_id) and is_map(attrs) do
    run_command(agent_id, opts, fn agent ->
      RoundConfig.build_runtime_session_config(agent_id, agent["role"], attrs)
    end)
  end

  @spec stage_rpc_delivery(String.t(), inbox_entry(), keyword()) ::
          {:ok, :committed, [wake_target()]}
          | {:ok, :duplicate}
          | {:ok, :ignored}
          | {:error, :not_owner}
          | {:error, term()}
  def stage_rpc_delivery(agent_id, entry, opts \\ [])
      when is_binary(agent_id) and is_map(entry) do
    route_to_owner(agent_id, :stage_rpc_delivery_local, [agent_id, entry, opts])
  end

  @doc false
  def stage_rpc_delivery_local(agent_id, entry, opts \\ [])
      when is_binary(agent_id) and is_map(entry) do
    with :ok <- verify_rpc_delivery_owner(agent_id) do
      stage_delivery_and_wake_local(agent_id, entry, opts)
    end
  end

  # The RPC delivery owner fence (plan §1.3): placement resolution and this
  # stage are not atomic, so before committing, the target node checks that
  # the DURABLE agent head still names it as owner. A moved head means this
  # node is stale — refuse with :not_owner and commit nothing; the caller
  # re-resolves placement (bounded, facade-side). An absent head is a
  # never-claimed agent: nobody owns it yet, and the first Server activation
  # on this node will claim it, so delivery may proceed. The residual
  # fence-read → CAS window is closed by the session CAS + the same-id retry
  # dedupe, modeled in tla/salix/RpcDeliver.tla.
  #
  # The head observation is the delivery's: inside its read scope the facade
  # (or the provider callback before it) may have read the head already,
  # and placement and this fence share that one read. An observation that
  # names another owner while this node holds a live claim predates that
  # claim (placement took the agent over from an expired lease after the
  # read); the fence then reads the head again instead of refusing a
  # delivery the durable head would admit.
  defp verify_rpc_delivery_owner(agent_id) do
    case SalixStore.Agent.peek_in_scope(agent_id) do
      {:ok, head} ->
        cond do
          is_nil(head.owner_node) or head.owner_node == to_string(node()) ->
            :ok

          match?({:ok, _epoch}, SalixAgent.OwnershipCell.fetch(agent_id)) ->
            SalixStore.ReadScope.invalidate({:head, agent_id})
            verify_rpc_delivery_owner_freshly(agent_id)

          true ->
            {:error, :not_owner}
        end

      {:error, :not_found} ->
        :ok

      {:error, _} = err ->
        err
    end
  end

  defp verify_rpc_delivery_owner_freshly(agent_id) do
    case SalixStore.Agent.peek(agent_id) do
      {:ok, head} ->
        if is_nil(head.owner_node) or head.owner_node == to_string(node()) do
          :ok
        else
          # This fresh head supersedes the local placement hint. Preserve any
          # newer claim installed while the read was in flight.
          SalixAgent.OwnershipCell.fence(agent_id, head.epoch)
          {:error, :not_owner}
        end

      {:error, :not_found} ->
        :ok

      {:error, _} = err ->
        err
    end
  end

  @spec stage_delivery(String.t(), inbox_entry(), keyword()) ::
          {:ok, :committed, [wake_target()]}
          | {:ok, :duplicate}
          | {:ok, :ignored}
          | {:error, term()}
  def stage_delivery(agent_id, entry, opts \\ []) when is_binary(agent_id) and is_map(entry) do
    route_to_owner(agent_id, :stage_delivery_and_wake_local, [agent_id, entry, opts])
  end

  @doc false
  def stage_delivery_and_wake_local(agent_id, entry, opts \\ [])
      when is_binary(agent_id) and is_map(entry) do
    case stage_delivery_local(agent_id, entry, opts) do
      {:ok, :committed, targets} = result ->
        case wake_targets_after_commit(agent_id, targets) do
          :ok -> result
          {:deferred, _reason} -> result
          {:error, _} = error -> error
        end

      other ->
        other
    end
  end

  @doc false
  def stage_delivery_local(agent_id, entry, opts \\ [])
      when is_binary(agent_id) and is_map(entry) do
    timeout = Keyword.get(opts, :timeout, :infinity)

    with {:ok, agent} <- SalixAgent.Control.get_record(agent_id),
         {:ok, pid} <- ensure_started(agent) do
      AgentRoleActor.stage_delivery(pid, entry, timeout)
    end
  end

  @doc false
  def prepare_conversation_input(agent_id) do
    with {:ok, record} <- SalixAgent.Control.get_record(agent_id),
         {:ok, _config} <- SalixAgent.LlmResolver.resolve_runtime(agent_id, record),
         do: :ok
  end

  @doc false
  def notify_conversation(agent_id, source, opts \\ []) when is_map(source) do
    case {SalixAgent.Fleet.server_running?(agent_id),
          Registry.lookup(SalixAgent.Registry, key(agent_id))} do
      {true, [{pid, _}]} ->
        GenServer.cast(
          pid,
          {:conversation_source, source,
           {SalixStore.ReadScope.capture(), System.monotonic_time(:millisecond)}}
        )

      _ ->
        SalixStore.ReadScope.run(fn ->
          route_to_owner(agent_id, :notify_conversation_local, [
            agent_id,
            source,
            Keyword.put(opts, :create, true)
          ])
        end)
    end
  end

  @doc false
  def notify_conversation_local(agent_id, source, _opts) do
    with {:ok, agent} <- SalixAgent.Control.get_record(agent_id),
         {:ok, pid} <- ensure_started(agent) do
      GenServer.cast(
        pid,
        {:conversation_source, source,
         {SalixStore.ReadScope.capture(), System.monotonic_time(:millisecond)}}
      )
    end
  end

  @doc "Start or find the agent's local role actor."
  @spec ensure_started(agent_record()) :: {:ok, pid()} | {:error, term()}
  def ensure_started(%{} = agent) do
    with :ok <- require_role(agent), do: start_actor(agent)
  end

  @doc false
  def migrate_external_sessions(agent_id, tenant_id, target, operation_id, opts \\ []) do
    route_to_owner(agent_id, :migrate_external_sessions_local, [
      agent_id,
      tenant_id,
      target,
      operation_id,
      opts
    ])
  end

  @doc false
  def migrate_external_sessions_local(agent_id, tenant_id, target, operation_id, opts) do
    SalixAgent.ExternalSessionMigration.run(agent_id, tenant_id, target, operation_id, opts)
  end

  @spec stop(String.t()) :: :ok
  def stop(agent_id) when is_binary(agent_id) do
    case Registry.lookup(SalixAgent.Registry, key(agent_id)) do
      [{pid, _}] -> SalixAgent.Fleet.terminate_child(pid)
      [] -> :ok
    end

    :ok
  end

  @spec commit_workspace_operation(String.t(), String.t(), term(), [map()], keyword()) ::
          {:ok, term()} | {:error, term()}
  def commit_workspace_operation(agent_id, operation_id, result, events, opts \\ [])
      when is_binary(agent_id) and is_binary(operation_id) and is_list(events) and
             is_list(opts) do
    with :ok <- authorize_workspace_commit(agent_id, operation_id, events, opts) do
      route_to_owner(agent_id, :commit_workspace_operation_local, [
        agent_id,
        operation_id,
        result,
        events,
        opts
      ])
    end
  end

  defp authorize_workspace_commit(agent_id, operation_id, events, opts) do
    if Keyword.get(opts, :storage_authorized, false) do
      :ok
    else
      SalixAgent.StorageAuthorization.authorize_write(%{
        agent_id: agent_id,
        operation_id: operation_id,
        events: events,
        billing_context: Keyword.get(opts, :billing_context, %{}),
        entrypoint: Keyword.get(opts, :entrypoint),
        actor_type: Keyword.get(opts, :actor_type)
      })
    end
  end

  @doc false
  def commit_workspace_operation_local(agent_id, operation_id, result, events, opts \\ [])
      when is_binary(agent_id) and is_binary(operation_id) and is_list(events) and
             is_list(opts) do
    timeout = Keyword.get(opts, :timeout, :infinity)

    with {:ok, agent} <- SalixAgent.Control.get_record(agent_id),
         {:ok, pid} <- ensure_started(agent) do
      AgentRoleActor.commit_workspace_operation(pid, operation_id, result, events, timeout)
    end
  end

  @doc false
  def prepare_workspace_operation_for_session(
        agent_id,
        session_id,
        operation_id,
        result,
        events,
        opts \\ []
      )
      when is_binary(agent_id) and is_binary(session_id) and is_binary(operation_id) and
             is_list(events) and is_list(opts) do
    with true <- SalixAgent.InternalSessionActor.owner?(agent_id, session_id),
         :ok <- authorize_workspace_commit(agent_id, operation_id, events, opts),
         {:ok, pid} <- local_actor_pid(agent_id) do
      AgentRoleActor.prepare_workspace_operation(
        pid,
        operation_id,
        result,
        events,
        opts,
        Keyword.get(opts, :timeout, :infinity)
      )
    else
      false -> {:error, :not_session_owner}
      {:error, _} = error -> error
    end
  end

  @doc false
  def commit_prepared_workspace_operation_for_session(
        agent_id,
        session_id,
        prepared,
        opts \\ []
      )

  def commit_prepared_workspace_operation_for_session(
        agent_id,
        session_id,
        %SalixAgent.AgentWorkspace.PreparedOperation{agent_id: agent_id} = prepared,
        opts
      )
      when is_binary(agent_id) and is_binary(session_id) and is_list(opts) do
    with true <- SalixAgent.InternalSessionActor.owner?(agent_id, session_id),
         {:ok, pid} <- local_actor_pid(agent_id) do
      AgentRoleActor.commit_prepared_workspace_operation(
        pid,
        prepared,
        Keyword.get(opts, :timeout, :infinity)
      )
    else
      false -> {:error, :not_session_owner}
      {:error, _} = error -> error
    end
  end

  def commit_prepared_workspace_operation_for_session(
        _agent_id,
        _session_id,
        _prepared,
        _opts
      ),
      do: {:error, :invalid_prepared_workspace_operation}

  defp local_actor_pid(agent_id) do
    case Registry.lookup(SalixAgent.Registry, key(agent_id)) do
      [{pid, _}] ->
        {:ok, pid}

      [] ->
        with {:ok, agent} <- SalixAgent.Control.get_record(agent_id),
             do: ensure_started(agent)
    end
  end

  @spec stop_runtime(String.t(), keyword()) :: :ok | {:error, term()}
  def stop_runtime(agent_id, opts \\ []) when is_binary(agent_id) and is_list(opts) do
    reason = Keyword.get(opts, :reason, :stop)
    route_to_owner(agent_id, :stop_runtime_local, [agent_id, reason, opts])
  end

  @doc false
  def stop_runtime_local(agent_id, reason, opts \\ [])
      when is_binary(agent_id) and is_list(opts) do
    timeout = Keyword.get(opts, :timeout, :infinity)

    with {:ok, agent} <- SalixAgent.Control.get_record(agent_id),
         {:ok, pid} <- ensure_started(agent) do
      AgentRoleActor.stop_runtime(pid, reason, timeout)
    end
  end

  def key(agent_id), do: {:agent_actor, agent_id}

  def via(agent_id), do: {:via, Registry, {SalixAgent.Registry, key(agent_id)}}

  @doc false
  def local_owner_process?(agent_id) when is_binary(agent_id) do
    case Registry.lookup(SalixAgent.Registry, key(agent_id)) do
      [{pid, _}] -> pid == self()
      [] -> false
    end
  end

  @spec wake_targets(String.t(), [wake_target()]) :: :ok | {:error, term()}
  def wake_targets(_agent_id, []), do: :ok

  def wake_targets(agent_id, targets) when is_binary(agent_id) and is_list(targets) do
    Enum.reduce(targets, :ok, fn target, first_error ->
      result = wake_target(agent_id, target)
      if first_error == :ok, do: result, else: first_error
    end)
  end

  defp wake_target(agent_id, %{runtime: :internal, session_id: session_id}),
    do: SalixAgent.InternalSessionFleet.wake(agent_id, session_id)

  defp wake_target(agent_id, %{runtime: :external, session_id: session_id}),
    do: SalixAgent.ExternalSessionFleet.wake(agent_id, session_id)

  defp wake_target(_agent_id, target), do: {:error, {:invalid_wake_target, target}}

  @spec wake_targets_after_commit(String.t(), [wake_target()]) ::
          :ok | {:deferred, term()} | {:error, term()}
  def wake_targets_after_commit(agent_id, targets)
      when is_binary(agent_id) and is_list(targets) do
    # A cutover can retire a target after recovery read its index. Classify
    # each target before aggregation so it cannot hide another wake failure.
    result =
      Enum.reduce(targets, :ok, fn target, first_error ->
        result =
          case wake_target(agent_id, target) do
            {:error, {:retired_router_session, _canonical}} -> :ok
            other -> other
          end

        if first_error == :ok, do: result, else: first_error
      end)

    case result do
      :ok ->
        :ok

      {:error, {:invalid_wake_target, _target} = reason} ->
        {:error, reason}

      {:error, reason} ->
        CommaLog.log("wake_targets_failed", %{
          agent_id: agent_id,
          targets: targets,
          reason: reason
        })

        {:deferred, reason}
    end
  end

  # Stateless commands need no ordering with the role actor. They run in a
  # bounded reply task on the owner node: the task is cancelled if the caller
  # exits and answers a timeout error after the configured reply budget.
  defp run_command(agent_id, opts, fun) do
    with {:ok, agent} <- SalixAgent.Control.get_record(agent_id),
         :ok <- require_role(agent) do
      AgentReplyTask.call(fn -> fun.(agent) end, Keyword.get(opts, :timeout, :infinity))
    end
  end

  # Router deliveries always route to the canonical group router session. A
  # delivery `session_id` is source context, not a routing decision, for
  # router agents.
  defp external_delivery_target(%{"role" => "router"} = agent, _session_id, delivery) do
    payload = delivery[:payload] || delivery["payload"] || %{}

    with {:ok, router_session_id} <- SalixStore.RuntimeIds.persisted_router_session_id(agent) do
      payload =
        payload
        |> Map.drop([:session_id, "session_id"])
        |> Map.merge(%{:session_id => router_session_id, "session_id" => router_session_id})

      {:ok, router_session_id,
       delivery |> Map.drop([:payload, "payload"]) |> Map.put(:payload, payload)}
    end
  end

  defp external_delivery_target(_agent, session_id, delivery), do: {:ok, session_id, delivery}

  defp require_role(%{"role" => role}) when role in @roles, do: :ok
  defp require_role(agent), do: {:error, {:unsupported_agent_role, agent["role"]}}

  defp require_role(%{"role" => role}, role), do: :ok
  defp require_role(agent, _role), do: {:error, {:unsupported_agent_role, agent["role"]}}

  defp route_to_owner(agent_id, local_fun, args) do
    opts = List.last(args)
    timeout = if is_list(opts), do: Keyword.get(opts, :timeout, :infinity), else: :infinity

    with {:ok, _agent} <- SalixAgent.Control.get_record(agent_id),
         :ok <- SalixAgent.Control.ensure_not_stopped(agent_id),
         {:ok, pid} <- SalixAgent.Placement.ensure_started(agent_id, owner_start_opts(opts)) do
      owner_node = node(pid)

      if owner_node == node() do
        apply(__MODULE__, local_fun, args)
      else
        :erpc.call(owner_node, __MODULE__, local_fun, args, timeout)
      end
    end
  end

  # :create defaults to false: every pre-A2 route_to_owner caller reaches an
  # agent whose Server already exists. The RPC delivery ingress passes
  # create: true (its contract default) so a first delivery can start the
  # owner Server, mirroring the staged path's wake.
  defp owner_start_opts(opts) when is_list(opts) do
    [create: Keyword.get(opts, :create, false), startup_mode: owner_startup_mode(opts)]
  end

  defp owner_start_opts(_opts), do: [create: false]

  defp owner_startup_mode(opts) do
    if Keyword.get(opts, :process_on_init, true), do: :active, else: :passive
  end

  defp start_actor(agent) do
    opts = [agent_id: agent["agent_id"], agent: agent]

    case DynamicSupervisor.start_child(SalixAgent.FleetSup, {AgentRoleActor, opts}) do
      {:ok, pid} -> {:ok, pid}
      {:error, {:already_started, pid}} -> {:ok, pid}
      {:error, reason} -> {:error, reason}
    end
  catch
    :exit, reason -> {:error, {:exit, reason}}
  end
end
