defmodule SalixAgent.Tools.Schedules do
  @moduledoc """
  Durable schedule tools for the current agent.

  ## Seam

  `salix_agent` cannot depend on `salix_cluster` (dependency cycle), so the
  schedules implementation is resolved at runtime via
  `Application.get_env(:salix_agent, :schedules_mod)` — in production this is
  `SalixCluster.Schedules`. When unset (`nil`), every action raises
  `"schedule manager unavailable on this node"`, which the tool dispatcher
  synthesizes into an error tool-result.

  The configured module must expose the `SalixCluster.Schedules` surface used
  here: `create(id, params)`, `delete_agent_owned(id, agent_id)`,
  `list_by_agents(agent_ids)`. `create`
  expects a params map carrying `agent_id`, `prompt`, and exactly one of a
  positive integer `interval_minutes`, a `cron` string (with optional
  `timezone`), or one RFC3339 `run_at`, plus optional `session_id` (keys may be atoms or strings; the
  store stringifies). Returned schedule maps are string-keyed.

  The Salix schedules store supports interval and cron recurrence plus one-shot
  execution (`interval_minutes` XOR `cron` + `timezone` XOR `run_at`). The tool surface is split into explicit canonical
  names:

  - `schedule.create` takes exactly one of `interval_minutes`, `cron` (+ optional
    `timezone`), or RFC3339 `run_at`, plus `prompt`. The target is always the calling agent and current
    session from the tool context. Schedule ids are generated by `SalixStore.Ids`,
    never caller-supplied.
  - `schedule.list` returns only the calling agent's schedules as a JSON array.
  - `schedule.delete` verifies ownership first: a missing id or another agent's
    schedule both raise `"schedule not found"`. On success it returns
    `{"status":"deleted","schedule_id":...}`.

  The tool mutates control-plane state directly through the schedules store
  (rows in the salix control Postgres,
  docs/storage-search.md), not agent journal state, so it
  returns plain content strings — no journal events.
  """

  @normal_auto_wait_seconds SalixAgent.Tools.AsyncPolicy.normal_tool_auto_wait_seconds()
  @visible_write_opts [safety: "write"]

  alias SalixAgent.MeetingActivationProvenance

  @doc """
  Tool defs in stable registration order: `{name, description, fun,
  auto_wait_seconds}` entries where `fun` is a 2-arity capture taking
  `(args, ctx)`.
  """
  @spec defs() ::
          [
            {String.t(), String.t(), (map(), map() -> String.t()), pos_integer()}
            | {String.t(), String.t(), (map(), map() -> String.t()), pos_integer(), keyword()}
          ]
  def defs do
    [
      {"schedule.create",
       "Create a one-shot or recurring prompt for the calling agent and current session. Use run_at for one meeting/reminder time, cron for calendar recurrence, or interval_minutes for duration recurrence. Keep proactive Feishu delivery Router-owned: the prompt must contain the exact im_api.feishu.send_text connect_id, receive_id=chat_id, text, and structured mentions/mention_all to execute when it fires.",
       &__MODULE__.create_schedule/2, @normal_auto_wait_seconds, @visible_write_opts},
      {"schedule.list", "List schedules owned by the current agent.",
       &__MODULE__.list_schedules/2, @normal_auto_wait_seconds},
      {"schedule.delete", "Delete one schedule owned by the current agent.",
       &__MODULE__.delete_schedule/2, @normal_auto_wait_seconds}
    ]
  end

  @doc false
  def create_schedule(args, ctx), do: create(args, ctx)

  @doc false
  def list_schedules(_args, ctx), do: list(ctx)

  @doc false
  def delete_schedule(args, ctx), do: delete(args, ctx)

  # ---- actions ----

  defp create(args, ctx) do
    prompt = arg(args, "prompt")
    if prompt == "", do: raise("'prompt' is required")

    case MeetingActivationProvenance.authorize_schedule(ctx) do
      :ok -> :ok
      {:error, reason} -> raise "schedule.create source provenance rejected: #{inspect(reason)}"
      other -> raise "schedule.create source provenance invalid: #{inspect(other)}"
    end

    params =
      %{agent_id: ctx.agent_id, session_id: session_id!(ctx), prompt: prompt}
      |> Map.merge(timing(args))
      |> put_optional(args, "timezone", :timezone)
      |> put_ifc_authority(ctx)

    case schedules_mod().create(unique_id(), params) do
      {:ok, sched} -> Jason.encode!(sched)
      {:error, :already_exists} -> raise "schedule id collision, retry"
      {:error, :invalid_schedule} -> raise "invalid schedule parameters"
      {:error, reason} -> raise "create schedule failed: #{inspect(reason)}"
    end
  end

  # Exactly one of `interval_minutes` / `cron` / `run_at`. Models often emit every declared
  # schema property, tacking on a filler `interval_minutes` (0 / "" / null) even
  # when using `cron`; such a blank value is treated as "not provided" so cron
  # wins. A genuine conflict (cron + a *positive* interval) still raises the XOR
  # error; a present-but-invalid interval with no cron keeps the specific
  # positive-integer error.
  defp timing(args) do
    cron = arg(args, "cron")
    interval = int_arg(args, "interval_minutes")
    run_at = arg(args, "run_at")

    provided =
      [
        if(cron != "", do: :cron),
        if(is_integer(interval) and interval > 0, do: :interval),
        if(run_at != "", do: :run_at)
      ]
      |> Enum.reject(&is_nil/1)

    cond do
      length(provided) > 1 ->
        raise "provide exactly one of 'interval_minutes', 'cron', or 'run_at'"

      run_at != "" ->
        %{run_at: parse_run_at!(run_at)}

      cron != "" ->
        %{cron: cron}

      not blank?(args, "interval_minutes") ->
        unless is_integer(interval) and interval > 0,
          do: raise("'interval_minutes' must be a positive integer")

        %{interval_minutes: interval}

      true ->
        raise "provide exactly one of 'interval_minutes', 'cron', or 'run_at'"
    end
  end

  defp parse_run_at!(value) do
    case DateTime.from_iso8601(value) do
      {:ok, datetime, _offset} -> DateTime.to_unix(datetime, :millisecond)
      _ -> raise "'run_at' must be an RFC3339 timestamp with timezone"
    end
  end

  defp blank?(args, key) do
    case args[key] || args[String.to_atom(key)] do
      nil -> true
      "" -> true
      _ -> false
    end
  end

  # Who asked for this schedule, and what its prompt was written from
  # (`docs/verification.md` §8). A fire acts with its
  # creator's authority, so the creator has to be recorded when the schedule
  # is made — at fire time there is no one to ask.
  #
  # `SalixAgent.IFC.Check` established both while deciding this very call: the
  # requester it admitted, and the join of everything the prompt drew on. Both
  # are absent when the Group is `off`, and a schedule made then simply carries
  # no authority of its own, exactly as it did before.
  defp put_ifc_authority(params, ctx) do
    case Map.get(ctx, :ifc_evidence) do
      %{} = evidence ->
        params
        |> put_present(:ifc_creator, evidence["requester"])
        |> put_present(:ifc_label, evidence["sources_label"])

      _absent ->
        params
    end
  end

  defp put_present(params, _key, nil), do: params
  defp put_present(params, _key, ""), do: params
  defp put_present(params, key, value), do: Map.put(params, key, value)

  defp put_optional(params, args, key, target) do
    case arg(args, key) do
      "" -> params
      val -> Map.put(params, target, val)
    end
  end

  defp list(ctx) do
    # Owner-filtered at the store (WHERE agent_id = ...): unrelated schedules
    # are neither queried nor transferred to this tool.
    case schedules_mod().list_by_agents([ctx.agent_id]) do
      {:ok, scheds} ->
        Jason.encode!(scheds)

      {:error, reason} ->
        raise "list schedules failed: #{inspect(reason)}"
    end
  end

  defp delete(args, ctx) do
    id = arg(args, "schedule_id")
    if id == "", do: raise("'schedule_id' is required")

    # Ownership is part of the DELETE predicate (agent-owned, never a Task
    # row whose owner is its group binding), so there is no read→delete
    # window and no path to another owner's definition. Anything not owned is
    # indistinguishable from missing (willow's loadOwnSchedule behavior).
    case schedules_mod().delete_agent_owned(id, ctx.agent_id) do
      :ok -> Jason.encode!(%{"status" => "deleted", "schedule_id" => id})
      {:error, :not_found} -> raise "schedule not found"
      {:error, reason} -> raise "delete schedule failed: #{inspect(reason)}"
    end
  end

  # ---- helpers ----

  defp schedules_mod do
    Application.get_env(:salix_agent, :schedules_mod) ||
      raise "schedule manager unavailable on this node"
  end

  defp unique_id do
    SalixStore.Ids.new_schedule_id()
  end

  defp session_id!(ctx) do
    case Map.get(ctx, :session_id) || Map.get(ctx, "session_id") do
      value when is_binary(value) ->
        value = String.trim(value)

        if SalixStore.Ids.valid_session_id?(value),
          do: value,
          else: raise("invalid ctx.session_id")

      _ ->
        raise "ctx.session_id is required"
    end
  end

  # Same string-args pattern as SalixAgent.Tools.arg/2.
  defp arg(args, key), do: to_string(args[key] || args[String.to_atom(key)] || "")

  defp int_arg(args, key) do
    case args[key] || args[String.to_atom(key)] do
      n when is_integer(n) ->
        n

      b when is_binary(b) ->
        case Integer.parse(b) do
          {n, ""} -> n
          _ -> nil
        end

      _ ->
        nil
    end
  end
end
