defmodule Salix.Control.Groups do
  @moduledoc """
  Group control-plane API.
  """

  alias Salix.Control.{PluginCatalogCache, Store, Tenants}
  alias SalixStore.{Ids, Keys, SlackTriageChannelCutover}

  @generated_id_retries 5
  @writable_fields ~w(
    name
    purpose
    hidden
    router_agent_id
    billing_owner
    owner_emails
    memory_ask_worker_enabled
    control_command_vfs_enabled
    ifc
  )

  # Information-flow integrity is per Group and off until someone sets it
  # (docs/verification.md). The group record owns the
  # mode, so this is where it is written and where it is validated.
  @ifc_modes ~w(off audit enforce)

  # The runtime composes rule A's refusal, rule B's footer and the
  # confirmation card itself, so it cannot follow the model's instruction to
  # answer in the asker's language. The Group says which one those sentences
  # are written in (§6.4); Chinese when it says nothing, which is what every
  # existing workspace already reads.
  @ifc_languages SalixAgent.IFC.languages()
  @ifc_settings ~w(mode language)

  def list(tenant_id) do
    if Ids.valid_tenant_id?(tenant_id) do
      tenant_id
      |> Keys.ctl_groups_prefix_for_tenant()
      |> Store.list_keyed_records()
      |> Enum.flat_map(fn
        {key, %{"group_id" => group_id} = group} ->
          if key == Keys.ctl_group(group_id) and valid_record?(group_id, group) and
               group["tenant_id"] == tenant_id,
             do: [without_legacy_fields(group)],
             else: []

        _ ->
          []
      end)
      |> Enum.filter(&visible_group?/1)
    else
      []
    end
  end

  def get(id) do
    if Ids.valid_group_id?(id) do
      case Store.get_record(Keys.ctl_group(id)) do
        {:ok, group} ->
          if valid_record?(id, group),
            do: {:ok, without_legacy_fields(group)},
            else: {:error, :not_found}

        {:error, _} = error ->
          error
      end
    else
      {:error, :not_found}
    end
  end

  def get(id, tenant_id) do
    with true <- Ids.valid_group_id_for_tenant?(id, tenant_id),
         {:ok, group} <- get(id),
         true <- group["tenant_id"] == tenant_id and visible_group?(group) do
      {:ok, group}
    else
      false -> {:error, :not_found}
      {:error, _} = err -> err
    end
  end

  def create(attrs, tenant_id) when is_map(attrs) do
    attrs = stringify_keys(attrs)

    if Store.present?(attrs["group_id"]) or Store.present?(attrs["tenant_id"]) do
      {:error, {:bad_request, "group identity is generated by the group owner"}}
    else
      create_generated(
        Map.drop(attrs, ["group_id", "tenant_id"]),
        tenant_id,
        @generated_id_retries
      )
    end
  end

  def create_preallocated(attrs, tenant_id, group_id)
      when is_map(attrs) and is_binary(tenant_id) and is_binary(group_id) do
    attrs = attrs |> stringify_keys() |> Map.drop(["group_id", "tenant_id"])

    if Ids.valid_group_id_for_tenant?(group_id, tenant_id) do
      ensure_preallocated(attrs, tenant_id, group_id)
    else
      {:error, {:bad_request, "invalid group_id for tenant"}}
    end
  end

  def create_preallocated(_attrs, _tenant_id, _group_id),
    do: {:error, {:bad_request, "invalid preallocated group"}}

  def update(id, attrs) when is_map(attrs) do
    with {:ok, group} <- get(id),
         {:ok, attrs} <- normalize_update_attrs(attrs),
         :ok <- validate_memory_ask_worker_enabled(attrs),
         :ok <- validate_control_command_vfs_enabled(attrs),
         :ok <- validate_ifc(attrs),
         :ok <- validate_group_agent_refs(attrs, group["tenant_id"], group["group_id"]),
         {:ok, attrs} <- normalize_owner_emails(attrs) do
      update_group_record(id, attrs)
    end
  end

  def update(_id, _attrs), do: {:error, {:bad_request, "invalid request body"}}

  def update(id, attrs, tenant_id) when is_map(attrs) do
    with {:ok, _group} <- get(id, tenant_id) do
      update(id, attrs)
    end
  end

  def update(_id, _attrs, _tenant_id), do: {:error, {:bad_request, "invalid request body"}}

  defp update_group_record(id, attrs) do
    write = fn ->
      Store.update_record(Keys.ctl_group(id), fn group ->
        group
        |> Map.merge(attrs)
        |> merge_ifc(group, attrs)
        |> without_legacy_fields()
      end)
    end

    result =
      if Map.has_key?(attrs, "router_agent_id") do
        SlackTriageChannelCutover.with_authority_write(write)
      else
        write.()
      end

    if match?({:ok, _}, result) and Map.has_key?(attrs, "hidden") do
      _ = PluginCatalogCache.invalidate_group(id)
    end

    result
  end

  # `ifc` is a settings map rather than a value, so a write of one setting
  # keeps the others. Replacing it wholesale would mean that whoever changed
  # the mode also reset the language, from a form that never showed it.
  defp merge_ifc(updated, group, %{"ifc" => %{} = settings}) do
    current = if is_map(group["ifc"]), do: group["ifc"], else: %{}
    Map.put(updated, "ifc", Map.merge(current, settings))
  end

  defp merge_ifc(updated, _group, _attrs), do: updated

  def delete(id) do
    with {:ok, group} <- get(id),
         :ok <- ensure_group_unreferenced(id),
         :ok <-
           SalixStore.BrowserStorage.delete_group(group["tenant_id"], id, fn ->
             with :ok <- SalixIM.ProviderConnects.delete_group_im_connects(group["tenant_id"], id),
                  :ok <- SalixAgent.SSH.delete_group_data(id),
                  do: Store.delete_record(Keys.ctl_group(id))
           end) do
      _ = PluginCatalogCache.invalidate_group(id)
      # The Group's live voice calls, phone and WebSocket, end now.
      _ = SalixVoice.revoke_group(id)
      :ok
    end
  end

  def delete(id, tenant_id) do
    with {:ok, _group} <- get(id, tenant_id) do
      delete(id)
    end
  end

  # `owner_emails` is the platform-managed recipient list for the group's
  # `email.send_to_owners` agent tool (synced from the BridgeForTeams swarm
  # owner list). It is control-plane state only and is never disclosed to
  # agents — the tool reads it server-side at send time.
  defp normalize_owner_emails(attrs) when is_map(attrs) do
    case Map.fetch(attrs, "owner_emails") do
      :error ->
        {:ok, attrs}

      {:ok, value} ->
        case sanitize_owner_emails(value) do
          {:ok, emails} ->
            {:ok, Map.put(attrs, "owner_emails", emails)}

          :error ->
            {:error, {:bad_request, "owner_emails must be a list of email address strings"}}
        end
    end
  end

  defp sanitize_owner_emails(value) when is_list(value) do
    if Enum.all?(value, &is_binary/1) do
      emails =
        value
        |> Enum.map(&String.trim/1)
        |> Enum.reject(&(&1 == ""))
        |> Enum.uniq()

      if Enum.all?(emails, &String.contains?(&1, "@")), do: {:ok, emails}, else: :error
    else
      :error
    end
  end

  defp sanitize_owner_emails(_value), do: :error

  defp validate_group_agent_refs(attrs, tenant_id, group_id) do
    case attrs["router_agent_id"] do
      nil ->
        :ok

      "" ->
        :ok

      agent_id when is_binary(agent_id) ->
        case SalixAgent.Control.get(agent_id, tenant_id) do
          {:ok, agent} ->
            cond do
              agent["group_id"] != group_id or
                  not Ids.valid_agent_id_for_group?(agent_id, group_id) ->
                {:error, {:bad_request, "router_agent_id must belong to this group"}}

              agent["role"] != "router" ->
                {:error, {:bad_request, "router_agent_id must reference a router agent"}}

              true ->
                :ok
            end

          {:error, :not_found} ->
            {:error, {:bad_request, "router_agent_id not found"}}

          {:error, reason} ->
            {:error, reason}
        end

      _other ->
        {:error, {:bad_request, "router_agent_id must be a string"}}
    end
  end

  defp ensure_group_unreferenced(group_id) do
    refs =
      group_id
      |> Keys.ctl_agents_prefix_for_group()
      |> Store.list_keyed_records()
      |> Enum.count(fn
        {key, %{"agent_id" => agent_id} = agent} ->
          key == Keys.ctl_agent(agent_id) and
            Ids.valid_agent_id_for_group?(agent_id, group_id) and
            agent["group_id"] == group_id and not Map.has_key?(agent, "archived_at")

        _ ->
          false
      end)

    if refs == 0 do
      :ok
    else
      {:error, {:conflict, "agent group is referenced by agents: #{refs} agent(s)"}}
    end
  end

  defp visible_group?(group), do: group["hidden"] != true

  defp create_generated(_attrs, _tenant_id, 0), do: {:error, :id_collision}

  defp create_generated(attrs, tenant_id, attempts) do
    case create_once(attrs, tenant_id, Ids.new_group_id(tenant_id)) do
      {:error, :exists} -> create_generated(attrs, tenant_id, attempts - 1)
      result -> result
    end
  rescue
    ArgumentError -> {:error, {:bad_request, "invalid tenant_id"}}
  end

  defp create_once(attrs, tenant_id, group_id) do
    with {:ok, _tenant} <- Tenants.get(tenant_id),
         {:ok, attrs} <- normalize_create_attrs(attrs),
         :ok <- validate_memory_ask_worker_enabled(attrs),
         :ok <- validate_control_command_vfs_enabled(attrs),
         :ok <- validate_group_agent_refs(attrs, tenant_id, group_id),
         {:ok, attrs} <- normalize_owner_emails(attrs) do
      rec =
        %{
          "group_id" => group_id,
          "tenant_id" => tenant_id,
          "name" => attrs["name"] || "Workspace",
          "created_at" => Store.now(),
          "router_conversation_id" => Ids.new_conversation_id(),
          "memory_ask_worker_enabled" => attrs["memory_ask_worker_enabled"] == true,
          "control_command_vfs_enabled" => attrs["control_command_vfs_enabled"] == true
        }
        |> Store.put_optional("purpose", attrs["purpose"])
        |> Store.put_optional("hidden", attrs["hidden"])
        |> Store.put_optional("router_agent_id", attrs["router_agent_id"])
        |> Store.put_optional("billing_owner", attrs["billing_owner"])
        |> Map.put(
          "agent_management_owner",
          if(get_in(attrs, ["billing_owner", "surface"]) == "bridge", do: "bridge", else: "salix")
        )
        |> Store.put_optional("owner_emails", attrs["owner_emails"])

      Store.put_new(Keys.ctl_group(group_id), rec)
    end
  end

  defp ensure_preallocated(attrs, tenant_id, group_id) do
    case create_once(attrs, tenant_id, group_id) do
      {:ok, _group} = result ->
        result

      {:error, :exists} ->
        finish_preallocated_group(tenant_id, group_id)

      {:error, {:ambiguous, _}} ->
        finish_preallocated_group(tenant_id, group_id)

      {:error, _} = error ->
        error
    end
  end

  defp finish_preallocated_group(tenant_id, group_id) do
    with {:ok, %{"tenant_id" => ^tenant_id} = group} <- get(group_id) do
      {:ok, group}
    else
      {:error, :not_found} -> {:error, :unavailable}
      _ -> {:error, :unavailable}
    end
  end

  defp normalize_create_attrs(attrs), do: normalize_attrs(attrs, "create")
  defp normalize_update_attrs(attrs), do: normalize_attrs(attrs, "update")

  # Keep new nodes safe during a rolling deployment even if an older node writes
  # the retired field after the release migration has scanned this record.
  defp without_legacy_fields(group) do
    group
    |> Map.delete("home_agent_id")
    |> Map.put_new("memory_ask_worker_enabled", false)
    |> Map.put_new("control_command_vfs_enabled", false)
  end

  # The only thing a caller may set is the mode, and only to a mode that
  # exists. An unknown key here would read as `off` at the seam and silently do
  # nothing, which is worse than a rejected write.
  # A partial write is allowed and merges into whatever is already stored, so
  # a caller that only knows about the mode can never silently drop the
  # language, and vice versa. Every setting it does name is validated.
  defp validate_ifc(attrs) do
    case Map.fetch(attrs, "ifc") do
      :error ->
        :ok

      {:ok, %{} = settings} when map_size(settings) > 0 ->
        cond do
          Map.keys(settings) -- @ifc_settings != [] ->
            {:error,
             {:bad_request, "ifc accepts only #{Enum.join(Enum.sort(@ifc_settings), ", ")}"}}

          not valid_setting?(settings, "mode", @ifc_modes) ->
            {:error, {:bad_request, "ifc.mode must be one of: #{Enum.join(@ifc_modes, ", ")}"}}

          not valid_setting?(settings, "language", @ifc_languages) ->
            {:error,
             {:bad_request,
              "ifc.language must be one of: #{Enum.join(Enum.sort(@ifc_languages), ", ")}"}}

          true ->
            :ok
        end

      {:ok, _invalid} ->
        {:error, {:bad_request, "ifc must be a non-empty object of information-flow settings"}}
    end
  end

  defp valid_setting?(settings, key, allowed) do
    case Map.fetch(settings, key) do
      :error -> true
      {:ok, value} -> value in allowed
    end
  end

  defp validate_memory_ask_worker_enabled(attrs) do
    case Map.fetch(attrs, "memory_ask_worker_enabled") do
      :error -> :ok
      {:ok, enabled} when is_boolean(enabled) -> :ok
      {:ok, _value} -> {:error, {:bad_request, "memory_ask_worker_enabled must be a boolean"}}
    end
  end

  defp validate_control_command_vfs_enabled(attrs) do
    case Map.fetch(attrs, "control_command_vfs_enabled") do
      :error -> :ok
      {:ok, enabled} when is_boolean(enabled) -> :ok
      {:ok, _value} -> {:error, {:bad_request, "control_command_vfs_enabled must be a boolean"}}
    end
  end

  defp normalize_attrs(attrs, operation) do
    attrs = stringify_keys(attrs)
    unknown = Map.keys(attrs) -- @writable_fields

    if unknown == [] do
      {:ok, attrs}
    else
      {:error,
       {:bad_request, "unsupported group #{operation} fields: " <> Enum.join(unknown, ", ")}}
    end
  end

  defp valid_record?(
         group_id,
         %{"group_id" => group_id, "tenant_id" => tenant_id} = group
       ),
       do:
         Ids.valid_group_id_for_tenant?(group_id, tenant_id) and
           Store.present?(group["router_conversation_id"])

  defp valid_record?(_group_id, _record), do: false

  defp stringify_keys(map), do: Map.new(map, fn {key, value} -> {to_string(key), value} end)
end
