defmodule Salix.Control.Tenants do
  @moduledoc """
  Tenant control-plane API.
  """

  alias Salix.Control.Store
  alias SalixStore.{FeishuTenantApps, Ids, Keys, TenantApiKeys, TenantConfigs}

  @tenant_config_sections ~w(agent_defaults vm)
  @tenant_im_config_sections ~w(slack telegram discord imessage feishu meetings)
  @tenant_im_status_platforms ~w(slack telegram discord imessage feishu)
  @generated_id_retries 5

  def list do
    Keys.ctl_tenants_prefix()
    |> Store.list_keyed_records(delimiter: "/")
    |> Enum.flat_map(fn
      {key, %{"tenant_id" => tenant_id} = tenant} ->
        if key == Keys.ctl_tenant(tenant_id) and canonical_record?(tenant),
          do: [tenant],
          else: []

      _ ->
        []
    end)
    |> Enum.sort_by(& &1["created_at"], :desc)
  end

  def get(id) do
    if Ids.valid_tenant_id?(id) do
      case Store.get_record(Keys.ctl_tenant(id)) do
        {:ok, %{"tenant_id" => ^id} = tenant} -> {:ok, tenant}
        {:ok, _record} -> {:error, :not_found}
        {:error, _} = error -> error
      end
    else
      {:error, :not_found}
    end
  end

  def create(attrs) when is_map(attrs) do
    attrs = stringify_keys(attrs)

    if Store.present?(attrs["tenant_id"]) do
      {:error, {:bad_request, "tenant_id is generated by the tenant owner"}}
    else
      create_generated(Map.delete(attrs, "tenant_id"), @generated_id_retries)
    end
  end

  def create_preallocated(attrs, tenant_id) when is_map(attrs) and is_binary(tenant_id) do
    attrs = attrs |> stringify_keys() |> Map.delete("tenant_id")

    if Ids.valid_tenant_id?(tenant_id) do
      ensure_preallocated(attrs, tenant_id)
    else
      {:error, {:bad_request, "invalid tenant_id"}}
    end
  end

  def create_preallocated(_attrs, _tenant_id),
    do: {:error, {:bad_request, "invalid preallocated tenant"}}

  def update(id, attrs) when is_map(attrs) do
    attrs = stringify_keys(attrs)

    with false <- Map.has_key?(attrs, "tenant_id"),
         {:ok, _tenant} <- get(id) do
      Store.update_record(Keys.ctl_tenant(id), fn rec ->
        rec
        |> maybe_put("name", attrs["name"])
        |> maybe_put("config", attrs["config"])
      end)
    else
      true -> {:error, {:bad_request, "tenant_id is immutable"}}
      {:error, _} = error -> error
    end
  end

  def update(_id, _attrs), do: {:error, {:bad_request, "invalid request body"}}

  # Tenant API keys live in Postgres (docs/storage-search.md).
  # Serving code reads Postgres directly. It does NOT re-check the cutover
  # marker per request: readiness does that once — Comma.PodLifecycle.ready(:salix)
  # (via SalixStore.TenantApiKeyReadiness) keeps a pod out of service until the
  # marker exists, so by the time a request lands the migration is a settled
  # deploy-time fact. A transient store fault still degrades to :unavailable
  # (503), never :unauthorized (401) — a cold/faulting node must not tell a
  # caller its key is invalid.

  @doc """
  List a tenant's keys, or `{:error, :unavailable}` on a transient store fault.
  Never raises: the dashboard shows a notice and the admin API returns 503.
  """
  def list_api_keys(tenant_id) do
    TenantApiKeys.list_by_tenant(tenant_id)
  rescue
    _exception -> {:error, :unavailable}
  end

  def create_api_key(tenant_id, attrs) do
    with {:ok, _tenant} <- get(tenant_id) do
      key = "salix_" <> Store.random_id()
      key_hash = :crypto.hash(:sha256, key) |> Base.encode16(case: :lower)

      rec = %{
        "key_hash" => key_hash,
        "tenant_id" => tenant_id,
        "name" => attrs["name"] || "API key",
        "created_at" => Store.now()
      }

      case TenantApiKeys.insert(rec) do
        {:ok, _} -> {:ok, Map.put(rec, "key", key)}
        {:error, :exists} -> {:error, :exists}
      end
    end
  rescue
    # A Postgres/DBConnection fault must surface as unavailable (503), not an
    # unhandled crash: the admin POST endpoint and the CloudVM key rotation both
    # need a structured result to retry instead of a Plug.Conn.WrapperError.
    _exception -> {:error, {:unavailable, "tenant api key store unavailable"}}
  end

  def delete_api_key(tenant_id, key_hash) do
    with {:ok, _tenant} <- get(tenant_id) do
      TenantApiKeys.delete(tenant_id, key_hash)
    end
  rescue
    _exception -> {:error, {:unavailable, "tenant api key store unavailable"}}
  end

  def validate_api_key(raw_key) when is_binary(raw_key) and raw_key != "" do
    key_hash = :crypto.hash(:sha256, raw_key) |> Base.encode16(case: :lower)
    validate_key(key_hash)
  end

  def validate_api_key(_raw_key), do: {:error, :unauthorized}

  # Store faults must read as *unavailable* (503), not *unauthorized* (401): a
  # cold/faulting node returning 401 would tell a caller its key is invalid.
  # The caller (SalixWeb.Auth) maps :unavailable to 503.
  defp validate_key(key_hash) do
    case TenantApiKeys.get_by_hash(key_hash) do
      {:ok, %{"tenant_id" => tenant_id} = rec} ->
        # The tenant record still lives in S3. Distinguish "tenant is gone"
        # (unauthorized, exactly as the retired per-tenant scan behaved) from a
        # transient object-store fault — S3.get returns {:error, {:ambiguous,
        # ...}} tuples on 5xx/transport faults, which must read as unavailable
        # (503), not unauthorized (401).
        case get(tenant_id) do
          {:ok, _tenant} -> {:ok, tenant_id, rec}
          {:error, :not_found} -> {:error, :unauthorized}
          {:error, _fault} -> {:error, :unavailable}
        end

      {:error, :not_found} ->
        {:error, :unauthorized}
    end
  rescue
    # A Postgres fault mid-lookup is unavailable, not unauthorized.
    _exception -> {:error, :unavailable}
  end

  def im_status(tenant_id) do
    with {:ok, tenant} <- get(tenant_id),
         {:ok, config} <- decode_tenant_config(tenant["config"]) do
      statuses =
        @tenant_im_status_platforms
        |> Enum.filter(&configured_im_section?(Map.get(config, &1, %{})))
        |> Enum.map(&base_im_platform_status(&1, config))
        |> Enum.sort_by(& &1["platform"])

      {:ok, statuses}
    end
  end

  def get_config(tenant_id, name, default) do
    cond do
      name in @tenant_config_sections ->
        with {:ok, tenant} <- get(tenant_id),
             {:ok, config} <- decode_tenant_config(tenant["config"]) do
          {:ok, Map.get(config, name, default)}
        end

      name == "im_integrations" ->
        with {:ok, tenant} <- get(tenant_id),
             {:ok, config} <- decode_tenant_config(tenant["config"]) do
          value = Map.take(config, @tenant_im_config_sections)
          {:ok, if(value == %{}, do: default, else: value)}
        end

      true ->
        get_control_config_record(tenant_id, name, default)
    end
  end

  # Discrete tenant-config records live in Postgres (docs/storage-search.md).
  # A store fault reads as unavailable (the retired S3 path surfaced its faults
  # the same way), never crashes the caller.
  defp get_control_config_record(tenant_id, name, default) do
    case TenantConfigs.get(tenant_id, name) do
      {:ok, rec} -> {:ok, Map.get(rec, "value", default)}
      {:error, :not_found} -> {:ok, default}
    end
  rescue
    _exception -> {:error, :unavailable}
  end

  def update_config(tenant_id, "agent_defaults", value) when is_map(value) do
    # Default pointers must name templates this tenant can see; a blank value
    # clears the pointer so the role defers to the platform default.
    with {:ok, validated} <- SalixAgent.AgentDefaults.validate_attrs(value, tenant_id) do
      result = update_tenant_config_section(tenant_id, "agent_defaults", validated)
      SalixStore.ReadScope.invalidate({:tenant_agent_defaults, tenant_id})
      result
    end
  end

  def update_config(tenant_id, name, value) do
    cond do
      name in @tenant_config_sections ->
        update_tenant_config_section(tenant_id, name, value)

      name == "im_integrations" ->
        update_tenant_im_config(tenant_id, value)

      true ->
        update_control_config_record(tenant_id, name, value)
    end
  end

  def put_feishu_tenant_app(tenant_id, attrs) do
    attrs = if is_map(attrs), do: attrs, else: %{}

    current =
      case FeishuTenantApps.get(tenant_id) do
        {:ok, rec} -> rec
        _ -> %{}
      end

    app_id = merge_field(attrs, current, "app_id")
    app_secret = merge_secret(attrs, current, "app_secret")
    verification_token = merge_secret(attrs, current, "verification_token")
    encrypt_key = merge_secret(attrs, current, "encrypt_key")

    if app_id == "" do
      {:error, {:bad_request, "app_id is required"}}
    else
      rec = %{
        "tenant_id" => tenant_id,
        "app_id" => app_id,
        "app_secret" => app_secret,
        "verification_token" => verification_token,
        "encrypt_key" => encrypt_key,
        "updated_at" => Store.now()
      }

      {:ok, _stored} = FeishuTenantApps.put(rec)
      {:ok, feishu_tenant_app_json(rec)}
    end
  rescue
    # A Postgres fault on the (admin-frequency) write surfaces as a structured
    # error the dashboard/API caller can show, not an unhandled crash.
    _exception -> {:error, :unavailable}
  end

  def delete_feishu_tenant_app(tenant_id) do
    FeishuTenantApps.delete(tenant_id)
  rescue
    _exception -> {:error, :unavailable}
  end

  def get_feishu_tenant_app(tenant_id) do
    case FeishuTenantApps.get(tenant_id) do
      {:ok, rec} ->
        app_id = Store.trim(rec["app_id"])
        app_secret = Store.trim(rec["app_secret"])

        if app_id == "" or app_secret == "" do
          {:error, :not_configured}
        else
          {:ok,
           %{
             "app_id" => app_id,
             "app_secret" => app_secret,
             "verification_token" => Store.trim(rec["verification_token"]),
             "encrypt_key" => Store.trim(rec["encrypt_key"])
           }}
        end

      {:error, :not_found} ->
        {:error, :not_configured}
    end
  rescue
    # A store fault must read as unavailable (the retired S3 path surfaced its
    # faults the same way), never crash the hot token-mint read path.
    _exception -> {:error, :unavailable}
  end

  defp update_control_config_record(tenant_id, name, value) do
    stripped = strip_nulls(value)

    record = %{
      "tenant_id" => tenant_id,
      "name" => name,
      "value" => stripped,
      "updated_at" => Store.now()
    }

    {:ok, _stored} = TenantConfigs.put(record)
    {:ok, stripped}
  rescue
    # A Postgres fault on the (admin/BFT-frequency) write surfaces as a
    # structured error the caller can show, not an unhandled crash.
    _exception -> {:error, :unavailable}
  end

  defp update_tenant_config_section(tenant_id, name, patch) do
    Store.update_record(Keys.ctl_tenant(tenant_id), fn rec ->
      {:ok, config} = decode_tenant_config(rec["config"])

      next_config =
        case merge_config_section(Map.get(config, name, %{}), patch) do
          nil -> Map.delete(config, name)
          section -> Map.put(config, name, section)
        end

      Map.put(rec, "config", Jason.encode!(next_config))
    end)
    |> case do
      {:ok, rec} ->
        {:ok, Map.get(elem(decode_tenant_config(rec["config"]), 1), name, %{})}

      other ->
        other
    end
  end

  defp update_tenant_im_config(tenant_id, patch) do
    Store.update_record(Keys.ctl_tenant(tenant_id), fn rec ->
      {:ok, config} = decode_tenant_config(rec["config"])

      next_config =
        Enum.reduce(@tenant_im_config_sections, config, fn section, acc ->
          if Map.has_key?(patch, section) do
            case normalize_config_section(patch[section]) do
              nil -> Map.delete(acc, section)
              value -> Map.put(acc, section, value)
            end
          else
            acc
          end
        end)

      Map.put(rec, "config", Jason.encode!(next_config))
    end)
    |> case do
      {:ok, rec} ->
        {:ok, Map.take(elem(decode_tenant_config(rec["config"]), 1), @tenant_im_config_sections)}

      other ->
        other
    end
  end

  defp feishu_tenant_app_json(rec) do
    %{
      "tenant_id" => rec["tenant_id"],
      "app_id" => rec["app_id"] || "",
      "app_secret_configured" => Store.present?(rec["app_secret"]),
      "verification_token_configured" => Store.present?(rec["verification_token"]),
      "encrypt_key_configured" => Store.present?(rec["encrypt_key"])
    }
  end

  defp merge_field(attrs, current, key) do
    if Map.has_key?(attrs, key),
      do: Store.trim(attrs[key]),
      else: Store.trim(current[key])
  end

  defp merge_secret(attrs, current, key) do
    case Map.fetch(attrs, key) do
      {:ok, value} ->
        case Store.trim(value) do
          "" -> Store.trim(current[key])
          trimmed -> trimmed
        end

      :error ->
        Store.trim(current[key])
    end
  end

  defp strip_nulls(map) when is_map(map) do
    map
    |> Enum.reject(fn {_k, v} -> is_nil(v) end)
    |> Map.new()
  end

  defp strip_nulls(other), do: other

  defp decode_tenant_config(nil), do: {:ok, %{}}
  defp decode_tenant_config(""), do: {:ok, %{}}

  defp decode_tenant_config(config) when is_binary(config) do
    case Jason.decode(config) do
      {:ok, decoded} when is_map(decoded) -> {:ok, decoded}
      {:ok, _} -> {:ok, %{}}
      {:error, reason} -> {:error, reason}
    end
  end

  defp decode_tenant_config(config) when is_map(config), do: {:ok, config}
  defp decode_tenant_config(_config), do: {:ok, %{}}

  defp merge_config_section(existing, patch) when is_map(patch) do
    if patch == %{} do
      nil
    else
      patch
      |> Enum.reduce(if(is_map(existing), do: existing, else: %{}), fn {key, value}, acc ->
        case normalize_config_value(value) do
          nil -> Map.delete(acc, key)
          normalized -> Map.put(acc, key, normalized)
        end
      end)
      |> normalize_config_section()
    end
  end

  defp merge_config_section(_existing, _patch), do: nil

  defp normalize_config_section(value) when is_map(value) do
    normalized =
      value
      |> Enum.reduce(%{}, fn {key, item}, acc ->
        case normalize_config_value(item) do
          nil -> acc
          normalized -> Map.put(acc, key, normalized)
        end
      end)

    if normalized == %{}, do: nil, else: normalized
  end

  defp normalize_config_section(_value), do: nil

  defp normalize_config_value(value) when is_binary(value) do
    case String.trim(value) do
      "" -> nil
      trimmed -> trimmed
    end
  end

  defp normalize_config_value(value) when is_map(value), do: normalize_config_section(value)
  defp normalize_config_value(value) when is_list(value), do: value
  defp normalize_config_value(nil), do: nil
  defp normalize_config_value(value), do: value

  defp base_im_platform_status(platform, config) do
    section = Map.get(config, platform, %{})

    %{
      "platform" => platform,
      "configured" => configured_im_section?(section),
      "online" => false
    }
    |> maybe_put_imessage_identity(platform, config)
  end

  defp maybe_put_imessage_identity(status, "imessage", config) do
    imessage = Map.get(config, "imessage", %{})

    status
    |> Store.put_optional("shared_identity", nonblank(imessage["shared_identity"]))
    |> Store.put_optional("shared_handle", nonblank(imessage["shared_handle"]))
  end

  defp maybe_put_imessage_identity(status, _platform, _config), do: status

  defp configured_im_section?(section) when is_map(section), do: strip_nulls(section) != %{}
  defp configured_im_section?(_section), do: false

  defp nonblank(value) when is_binary(value) do
    value = String.trim(value)
    if value == "", do: nil, else: value
  end

  defp nonblank(_value), do: nil

  defp create_generated(_attrs, 0), do: {:error, :id_collision}

  defp create_generated(attrs, attempts) do
    case create_once(attrs, Ids.new_tenant_id()) do
      {:error, :exists} -> create_generated(attrs, attempts - 1)
      result -> result
    end
  end

  defp create_once(attrs, tenant_id) do
    rec = %{
      "tenant_id" => tenant_id,
      "name" => attrs["name"] || "Tenant",
      "created_at" => Store.now(),
      "config" => attrs["config"] || "{}"
    }

    Store.put_new(Keys.ctl_tenant(tenant_id), rec)
  end

  defp ensure_preallocated(attrs, tenant_id) do
    case create_once(attrs, tenant_id) do
      {:ok, _tenant} = result -> result
      {:error, :exists} -> get(tenant_id)
      {:error, {:ambiguous, _}} -> confirm_preallocated(tenant_id)
      {:error, _} = error -> error
    end
  end

  defp confirm_preallocated(tenant_id) do
    case get(tenant_id) do
      {:ok, _tenant} = result -> result
      {:error, :not_found} -> {:error, :unavailable}
      {:error, _} = error -> error
    end
  end

  defp canonical_record?(%{"tenant_id" => tenant_id}), do: Ids.valid_tenant_id?(tenant_id)
  defp canonical_record?(_record), do: false

  defp stringify_keys(map), do: Map.new(map, fn {key, value} -> {to_string(key), value} end)

  defp maybe_put(map, _key, nil), do: map
  defp maybe_put(map, key, value), do: Map.put(map, key, value)
end
