/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=wrangler.jsonc --include-runtime=false --strict-vars=false src/env.d.ts` (hash: c7d02f56a49cc81c418abeec79a877ec)
interface __BaseEnv_Env {
  RESULTS: R2Bucket;
  DB: D1Database;
  ASSETS: Fetcher;
  GITHUB_OWNER: string;
  GITHUB_REPO: string;
  GITHUB_DEFAULT_REF: string;
}
declare namespace Cloudflare {
  interface GlobalProps {
    mainModule: typeof import("./worker");
  }
  interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
  [Binding in keyof EnvType]: EnvType[Binding] extends string
    ? EnvType[Binding]
    : string;
};
declare namespace NodeJS {
  interface ProcessEnv extends StringifyValues<
    Pick<Cloudflare.Env, "GITHUB_OWNER" | "GITHUB_REPO" | "GITHUB_DEFAULT_REF">
  > {}
}
