defmodule Comma.Repo.Migrations.AddSynchronicityIdsToCommaWorkspaces do
  use Ecto.Migration

  # Each Comma Workspace maps to one Synchronicity org and one default network.
  # Unlike the Salix/Billing ids, these are generated by the Synchronicity
  # control plane, so they are filled in by workspace convergence (nullable
  # until then) rather than minted at insert.
  def change do
    alter table(:comma_workspaces) do
      add(:sync_org_id, :string)
      add(:sync_network_id, :string)
    end
  end
end
