/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root";
import { Route as ViewerRouteImport } from "./routes/viewer";
import { Route as CompareRouteImport } from "./routes/compare";
import { Route as IndexRouteImport } from "./routes/index";
import { Route as EvaluationsIndexRouteImport } from "./routes/evaluations.index";
import { Route as RunsRunIdRouteImport } from "./routes/runs.$runId";
import { Route as EvaluationsEvalIdRouteImport } from "./routes/evaluations.$evalId";
import { Route as RunsRunIdItemsItemIdTrajectoryRouteImport } from "./routes/runs.$runId_.items.$itemId.trajectory";

const ViewerRoute = ViewerRouteImport.update({
  id: "/viewer",
  path: "/viewer",
  getParentRoute: () => rootRouteImport,
} as any);
const CompareRoute = CompareRouteImport.update({
  id: "/compare",
  path: "/compare",
  getParentRoute: () => rootRouteImport,
} as any);
const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any);
const EvaluationsIndexRoute = EvaluationsIndexRouteImport.update({
  id: "/evaluations/",
  path: "/evaluations/",
  getParentRoute: () => rootRouteImport,
} as any);
const RunsRunIdRoute = RunsRunIdRouteImport.update({
  id: "/runs/$runId",
  path: "/runs/$runId",
  getParentRoute: () => rootRouteImport,
} as any);
const EvaluationsEvalIdRoute = EvaluationsEvalIdRouteImport.update({
  id: "/evaluations/$evalId",
  path: "/evaluations/$evalId",
  getParentRoute: () => rootRouteImport,
} as any);
const RunsRunIdItemsItemIdTrajectoryRoute =
  RunsRunIdItemsItemIdTrajectoryRouteImport.update({
    id: "/runs/$runId_/items/$itemId/trajectory",
    path: "/runs/$runId/items/$itemId/trajectory",
    getParentRoute: () => rootRouteImport,
  } as any);

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute;
  "/compare": typeof CompareRoute;
  "/viewer": typeof ViewerRoute;
  "/evaluations/$evalId": typeof EvaluationsEvalIdRoute;
  "/runs/$runId": typeof RunsRunIdRoute;
  "/evaluations/": typeof EvaluationsIndexRoute;
  "/runs/$runId/items/$itemId/trajectory": typeof RunsRunIdItemsItemIdTrajectoryRoute;
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute;
  "/compare": typeof CompareRoute;
  "/viewer": typeof ViewerRoute;
  "/evaluations/$evalId": typeof EvaluationsEvalIdRoute;
  "/runs/$runId": typeof RunsRunIdRoute;
  "/evaluations": typeof EvaluationsIndexRoute;
  "/runs/$runId/items/$itemId/trajectory": typeof RunsRunIdItemsItemIdTrajectoryRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  "/": typeof IndexRoute;
  "/compare": typeof CompareRoute;
  "/viewer": typeof ViewerRoute;
  "/evaluations/$evalId": typeof EvaluationsEvalIdRoute;
  "/runs/$runId": typeof RunsRunIdRoute;
  "/evaluations/": typeof EvaluationsIndexRoute;
  "/runs/$runId_/items/$itemId/trajectory": typeof RunsRunIdItemsItemIdTrajectoryRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths:
    | "/"
    | "/compare"
    | "/viewer"
    | "/evaluations/$evalId"
    | "/runs/$runId"
    | "/evaluations/"
    | "/runs/$runId/items/$itemId/trajectory";
  fileRoutesByTo: FileRoutesByTo;
  to:
    | "/"
    | "/compare"
    | "/viewer"
    | "/evaluations/$evalId"
    | "/runs/$runId"
    | "/evaluations"
    | "/runs/$runId/items/$itemId/trajectory";
  id:
    | "__root__"
    | "/"
    | "/compare"
    | "/viewer"
    | "/evaluations/$evalId"
    | "/runs/$runId"
    | "/evaluations/"
    | "/runs/$runId_/items/$itemId/trajectory";
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  CompareRoute: typeof CompareRoute;
  ViewerRoute: typeof ViewerRoute;
  EvaluationsEvalIdRoute: typeof EvaluationsEvalIdRoute;
  RunsRunIdRoute: typeof RunsRunIdRoute;
  EvaluationsIndexRoute: typeof EvaluationsIndexRoute;
  RunsRunIdItemsItemIdTrajectoryRoute: typeof RunsRunIdItemsItemIdTrajectoryRoute;
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/viewer": {
      id: "/viewer";
      path: "/viewer";
      fullPath: "/viewer";
      preLoaderRoute: typeof ViewerRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/compare": {
      id: "/compare";
      path: "/compare";
      fullPath: "/compare";
      preLoaderRoute: typeof CompareRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/": {
      id: "/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof IndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/evaluations/": {
      id: "/evaluations/";
      path: "/evaluations";
      fullPath: "/evaluations/";
      preLoaderRoute: typeof EvaluationsIndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/runs/$runId": {
      id: "/runs/$runId";
      path: "/runs/$runId";
      fullPath: "/runs/$runId";
      preLoaderRoute: typeof RunsRunIdRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/evaluations/$evalId": {
      id: "/evaluations/$evalId";
      path: "/evaluations/$evalId";
      fullPath: "/evaluations/$evalId";
      preLoaderRoute: typeof EvaluationsEvalIdRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/runs/$runId_/items/$itemId/trajectory": {
      id: "/runs/$runId_/items/$itemId/trajectory";
      path: "/runs/$runId/items/$itemId/trajectory";
      fullPath: "/runs/$runId/items/$itemId/trajectory";
      preLoaderRoute: typeof RunsRunIdItemsItemIdTrajectoryRouteImport;
      parentRoute: typeof rootRouteImport;
    };
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CompareRoute: CompareRoute,
  ViewerRoute: ViewerRoute,
  EvaluationsEvalIdRoute: EvaluationsEvalIdRoute,
  RunsRunIdRoute: RunsRunIdRoute,
  EvaluationsIndexRoute: EvaluationsIndexRoute,
  RunsRunIdItemsItemIdTrajectoryRoute: RunsRunIdItemsItemIdTrajectoryRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();
