defmodule BridgeForTeams.Schema.AccountRecoveryLink do
  @moduledoc """
  One-time account recovery link generated by a system admin from the Elixir
  shell. The raw token is shown once; only `token_hash` is persisted.
  """
  use Ecto.Schema
  import Ecto.Changeset

  @primary_key {:id, :binary_id, autogenerate: true}
  @foreign_key_type :binary_id
  @timestamps_opts [type: :utc_datetime_usec, inserted_at: :created_at]

  schema "account_recovery_links" do
    field :token_hash, :string
    field :expires_at, :utc_datetime_usec
    field :used_at, :utc_datetime_usec
    field :note, :string

    belongs_to :user, BridgeForTeams.Schema.User

    timestamps()
  end

  @doc "Changeset for one-time account recovery links."
  @spec changeset(t() | Ecto.Changeset.t(), map()) :: Ecto.Changeset.t()
  def changeset(link, attrs) do
    link
    |> cast(attrs, [:user_id, :token_hash, :expires_at, :used_at, :note])
    |> validate_required([:user_id, :token_hash, :expires_at])
    |> validate_length(:token_hash, min: 1)
    |> unique_constraint(:token_hash)
  end

  @type t :: %__MODULE__{}
end
