import {
  type CentralIconVariant,
  filledAppIconVariant,
  filledMediaIconVariant,
  outlinedAiInputIconVariant,
  outlinedAppIconVariant,
  preThinnedAppIconVariant,
} from "./centralIconVariants";

export type IconRegistryEntry = {
  exportName: string;
  centralName: string;
  variant: CentralIconVariant;
  source: "figma" | "central";
  /** Figma file key is always VnkgBb2xCr5bRp4KHrLrqs unless noted. */
  figmaNodeId?: string;
  figmaSource?: string;
};

const outlined = outlinedAppIconVariant;
const outlinedAiInput = outlinedAiInputIconVariant;
const filledMedia = filledMediaIconVariant;
const filled = filledAppIconVariant;
const preThinned = preThinnedAppIconVariant;

/** A content brand mark, loaded on first use from `./brandMarks`. */
const brandMark = <Key extends string>(
  key: Key,
  centralName: string,
  variant = outlined
) => ({
  exportName: `brandMarks.${key}` as const,
  centralName,
  variant,
  source: "central" as const,
  figmaSource: "Content brand marks / Central Icons catalog",
});

/** Source-of-truth mapping from design icon usage to Central Icons npm packages. */
export const iconRegistry = [
  {
    exportName: "CloudIcon",
    centralName: "IconCloud",
    variant: outlined,
    source: "central",
    figmaSource: "Widget semantic icons / Central Icons catalog",
  },
  {
    exportName: "CloudySunIcon",
    centralName: "IconCloudySun",
    variant: outlined,
    source: "central",
    figmaSource: "Widget semantic icons / Central Icons catalog",
  },
  {
    exportName: "RainIcon",
    centralName: "IconRainy",
    variant: outlined,
    source: "central",
    figmaSource: "Widget semantic icons / Central Icons catalog",
  },
  {
    exportName: "SnowIcon",
    centralName: "IconSnowFlakes",
    variant: outlined,
    source: "central",
    figmaSource: "Widget semantic icons / Central Icons catalog",
  },
  {
    exportName: "TrainIcon",
    centralName: "IconTrainFrontView",
    variant: outlined,
    source: "central",
    figmaSource: "Widget semantic icons / Central Icons catalog",
  },

  {
    exportName: "CodexBrandIcon",
    centralName: "IconOpenaiCodex",
    variant: filled,
    source: "central",
    figmaSource: "Model providers / Central Icons catalog",
  },
  {
    exportName: "AnthropicBrandIcon",
    centralName: "IconAnthropic",
    variant: filled,
    source: "central",
    figmaSource: "Model providers / Central Icons catalog",
  },
  {
    exportName: "GeminiBrandIcon",
    centralName: "IconGemini",
    variant: filled,
    source: "central",
    figmaSource: "Model providers / Central Icons catalog",
  },
  {
    exportName: "DeepSeekBrandIcon",
    centralName: "IconDeepseek",
    variant: filled,
    source: "central",
    figmaSource: "Model providers / Central Icons catalog",
  },
  {
    exportName: "MistralBrandIcon",
    centralName: "IconMistral",
    variant: filled,
    source: "central",
    figmaSource: "Model providers / Central Icons catalog",
  },
  {
    exportName: "MetaAiBrandIcon",
    centralName: "IconMetaAi",
    variant: filled,
    source: "central",
    figmaSource: "Model providers / Central Icons catalog",
  },
  {
    exportName: "GrokBrandIcon",
    centralName: "IconGrok",
    variant: filled,
    source: "central",
    figmaSource: "Model providers / Central Icons catalog",
  },
  {
    exportName: "QwenBrandIcon",
    centralName: "IconQwen",
    variant: filled,
    source: "central",
    figmaSource: "Model providers / Central Icons catalog",
  },
  {
    exportName: "ZaiBrandIcon",
    centralName: "IconZai",
    variant: filled,
    source: "central",
    figmaSource: "Model providers / Central Icons catalog",
  },
  {
    exportName: "NvidiaBrandIcon",
    centralName: "IconNvidia",
    variant: filled,
    source: "central",
    figmaSource: "Model providers / Central Icons catalog",
  },
  {
    exportName: "OllamaBrandIcon",
    centralName: "IconOllama",
    variant: filled,
    source: "central",
    figmaSource: "Model providers / Central Icons catalog",
  },
  {
    exportName: "OpencodeBrandIcon",
    centralName: "IconOpencode",
    variant: filled,
    source: "central",
    figmaSource: "Model providers / Central Icons catalog",
  },
  {
    exportName: "VercelBrandIcon",
    centralName: "IconVercel",
    variant: filled,
    source: "central",
    figmaSource: "Model providers / Central Icons catalog",
  },
  {
    exportName: "CopilotBrandIcon",
    centralName: "IconCopilot",
    variant: filled,
    source: "central",
    figmaSource: "Model providers / Central Icons catalog",
  },
  {
    exportName: "OpenAiIcon",
    centralName: "IconOpenai",
    variant: filled,
    source: "central",
    figmaSource: "Comma App / Tasks / Worker filter / Codex (openai, chatgpt)",
  },
  {
    exportName: "ClaudeAiIcon",
    centralName: "IconClaudeai",
    variant: filled,
    source: "central",
    figmaSource: "Comma App / Tasks / Worker filter / Claude (claudeai)",
  },
  {
    exportName: "PlusIcon",
    centralName: "IconPlusLarge",
    variant: outlinedAiInput,
    source: "figma",
    figmaNodeId: "7593:390;7592:7068;3471:598450",
    figmaSource: "AI Input / fill / toolbar plus",
  },
  {
    exportName: "PaperclipIcon",
    centralName: "IconPaperclip1",
    variant: outlinedAiInput,
    source: "figma",
    figmaNodeId: "1292:12682",
    figmaSource:
      "Comma App (P0HbtMUd3lTy0FcGn0ojxT) / AI input @ menu / Add files or folders (paperclip-1, attachment)",
  },
  {
    exportName: "CirclePlusIcon",
    centralName: "IconCirclePlus",
    variant: outlined,
    source: "figma",
    figmaNodeId: "929:13141;929:13174",
    figmaSource: "Comma App / Recommendations / footer action (circle-plus, add)",
  },
  {
    exportName: "LoadingCircleIcon",
    centralName: "IconLoadingCircle",
    variant: outlinedAiInput,
    source: "figma",
    figmaNodeId: "8031:2387",
    figmaSource:
      "AI Input / attachment / image upload loading (loading-circle, quarter, spinner)",
  },
  {
    exportName: "CloseQuoteIcon",
    centralName: "IconCloseQuote1",
    variant: filled,
    source: "figma",
    figmaNodeId: "8024:3736",
    figmaSource: "AI Input / attachment / quote reference (close-quote-1, blockquote)",
  },
  {
    exportName: "ShieldCheckIcon",
    centralName: "IconShieldCheck",
    variant: outlined,
    source: "figma",
    figmaNodeId: "7593:390;7592:7069;3467:417299",
    figmaSource: "AI Input / fill / Full-access",
  },
  {
    exportName: "ChevronDownSmallIcon",
    centralName: "IconChevronDownSmall",
    variant: outlined,
    source: "figma",
    figmaNodeId: "7601:14308;7538:12072;7538:11900",
    figmaSource: "Left Sidebar / Pinned header / chevron-down-small (expanded)",
  },
  {
    exportName: "ChevronLeftSmallIcon",
    centralName: "IconChevronLeftSmall",
    variant: outlined,
    source: "central",
    figmaSource: "Chat panel image group / stack advance",
  },
  {
    exportName: "ChevronRightSmallIcon",
    centralName: "IconChevronRightSmall",
    variant: outlined,
    source: "figma",
    figmaNodeId: "7538:11909",
    figmaSource: "Left Sidebar / Pinned header / chevron-right-small (collapsed)",
  },
  {
    exportName: "ChevronTopSmallIcon",
    centralName: "IconChevronTopSmall",
    variant: outlined,
    source: "central",
    figmaSource: "Markdown stream / code block / collapse",
  },
  {
    exportName: "ChevronTriangleDownSmallIcon",
    centralName: "IconChevronTriangleDownSmall",
    variant: filled,
    source: "figma",
    figmaNodeId: "236:7005",
    figmaSource: "Task List Item / content / group header dropdown caret",
  },
  {
    exportName: "ChevronDownIcon",
    centralName: "IconChevronDownMedium",
    variant: outlined,
    source: "figma",
    figmaNodeId: "3281:379700",
    figmaSource:
      "Dropdown chevron; AI Input Full-access chevron (7593:390;7592:7069;3468:418654)",
  },
  {
    exportName: "MicrophoneIcon",
    centralName: "IconMicrophone",
    variant: outlinedAiInput,
    source: "figma",
    figmaNodeId: "7593:390;7592:7071;3471:598450",
    figmaSource: "AI Input / fill / microphone",
  },
  {
    exportName: "MicrophoneFilledIcon",
    centralName: "IconMicrophone",
    variant: filled,
    source: "central",
    figmaSource: "AI Input / empty send / microphone filled",
  },
  {
    exportName: "ArrowUpIcon",
    centralName: "IconArrowUp",
    variant: outlinedAiInput,
    source: "figma",
    figmaNodeId: "7593:390;7592:7072;3471:601890",
    figmaSource: "AI Input / fill / send",
  },
  {
    exportName: "FileIcon",
    centralName: "IconFileBend",
    variant: outlined,
    source: "figma",
    figmaNodeId: "7592:297;7622:1119",
    figmaSource: "AI Input / fill / attachment file",
  },
  {
    exportName: "ImageIcon",
    centralName: "IconImages1",
    variant: outlined,
    source: "figma",
    figmaNodeId: "1180:11256;3471:598450",
    figmaSource: "Comma App / AI input drop / images-1, photos, pictures, shot",
  },
  {
    exportName: "VideoIcon",
    centralName: "IconVideo",
    variant: outlined,
    source: "figma",
    figmaNodeId: "1180:11433;3471:598450",
    figmaSource: "Comma App / AI input drop / video, camera, movie, play",
  },
  {
    exportName: "AirDropIcon",
    centralName: "IconAirdrop",
    variant: outlined,
    source: "central",
    figmaSource: "Comma App / AirDrop toast / airdrop, file-sharing, radar",
  },
  {
    exportName: "FileTextIcon",
    centralName: "IconFileText",
    variant: outlined,
    source: "figma",
    figmaNodeId: "7798:28520",
    figmaSource: "Chat panel / generated file / file-text, document",
  },
  {
    exportName: "CopyIcon",
    centralName: "IconSquareBehindSquare6",
    variant: outlined,
    source: "figma",
    figmaNodeId: "7798:28574",
    figmaSource:
      "Chat panel / generated image / square-behind-square-6, layers, copy 6, pages",
  },
  {
    exportName: "PlayIcon",
    centralName: "IconPlay",
    variant: filledMedia,
    source: "figma",
    figmaNodeId: "7798:28526;7798:28557",
    figmaSource: "Chat panel / generated audio and video / play, go",
  },
  {
    exportName: "PauseIcon",
    centralName: "IconPause",
    variant: filledMedia,
    source: "figma",
    figmaNodeId: "7798:28541",
    figmaSource: "Chat panel / generated audio / pause",
  },
  {
    exportName: "StopIcon",
    centralName: "IconStop",
    variant: filledMedia,
    source: "central",
  },
  {
    exportName: "VoiceRecordIcon",
    centralName: "IconVoiceRecord",
    variant: outlined,
    source: "central",
    figmaSource:
      "Recording controls / voice-record (explicit user selection); parent 1453:17404",
  },
  {
    exportName: "MicrophoneOffIcon",
    centralName: "IconMicrophoneOff",
    variant: outlined,
    source: "central",
  },
  {
    exportName: "MicrophoneOffFilledIcon",
    centralName: "IconMicrophoneOff",
    variant: filled,
    source: "central",
    figmaSource: "Meeting Recorder / microphone off / user-requested filled variant",
  },
  {
    exportName: "VolumeFullIcon",
    centralName: "IconVolumeFull",
    variant: filledMedia,
    source: "figma",
    figmaNodeId: "7798:28528;7798:28543;7798:28559",
    figmaSource:
      "Chat panel / generated audio and video / volume-full, speaker, loud, sound",
  },
  {
    exportName: "VolumeHalfIcon",
    centralName: "IconVolumeHalf",
    variant: filledMedia,
    source: "central",
    figmaSource: "Generated media volume feedback / intermediate level",
  },
  {
    exportName: "VolumeOffIcon",
    centralName: "IconVolumeOff",
    variant: filledMedia,
    source: "central",
    figmaSource: "Generated media volume feedback / muted level",
  },
  {
    exportName: "DownloadIcon",
    centralName: "IconArrowInbox",
    variant: outlined,
    source: "figma",
    figmaNodeId: "7798:28575",
    figmaSource:
      "Chat panel / generated image / arrow-inbox, download, file, down, save",
  },
  {
    exportName: "MediaDownloadIcon",
    centralName: "IconArrowInbox",
    variant: filledMedia,
    source: "figma",
    figmaNodeId: "7798:28538;7798:28553;7798:28569",
    figmaSource:
      "Chat panel / generated audio and video / arrow-inbox, download, file, down, save",
  },
  {
    exportName: "MediaExpandIcon",
    centralName: "IconExpandSimple",
    variant: filledMedia,
    source: "figma",
    figmaNodeId: "7798:28571",
    figmaSource: "Chat panel / generated video / expand-simple",
  },
  {
    exportName: "Expand45Icon",
    centralName: "IconExpand45",
    variant: outlined,
    source: "central",
    figmaSource: "Video picture-in-picture / full window / Central Icons catalog",
  },
  {
    exportName: "SquareArrowBottomLeftCornerIcon",
    centralName: "IconSquareArrowBottomLeftCorner",
    variant: outlined,
    source: "central",
    figmaSource: "Video picture-in-picture / back to video / Central Icons catalog",
  },
  {
    exportName: "PictureInPictureIcon",
    centralName: "IconPictureInPicture",
    variant: outlined,
    source: "central",
    figmaSource:
      "Video picture-in-picture / frame while playing in the window / Central Icons catalog",
  },
  {
    exportName: "SearchIcon",
    centralName: "IconMagnifyingGlass",
    variant: outlined,
    source: "figma",
    figmaNodeId: "7601:14308;7538:11975;7538:11870;310:999",
    figmaSource: "Left Sidebar and Comma App Plugins search / magnifying-glass, search",
  },
  {
    exportName: "MoreHorizontalIcon",
    centralName: "IconDotGrid1x3Horizontal",
    variant: outlined,
    source: "figma",
    figmaNodeId: "7621:1033;7792:25470",
    figmaSource: "Chat panel / panel-header / menu",
  },
  {
    exportName: "DragHandleIcon",
    centralName: "IconDotGrid2x3",
    variant: outlined,
    source: "central",
    figmaSource: "Comma App / Recommendations / routine ordering drag handle",
  },
  {
    exportName: "PanelLeftIcon",
    centralName: "IconLayoutAlignLeft",
    // Central ships this one fill-only; taken pre-thinned (see preThinnedAppIconVariant).
    variant: preThinned,
    source: "figma",
    figmaNodeId: "7621:1033;7781:25190",
    figmaSource: "Chat panel / panel-header / device",
  },
  {
    exportName: "PanelRightIcon",
    centralName: "IconLayoutAlignRight",
    // Central ships this one fill-only; taken pre-thinned (see preThinnedAppIconVariant).
    variant: preThinned,
    source: "figma",
    figmaNodeId: "7621:1033;7545:21858",
    figmaSource: "Chat panel / panel-header / collapse",
  },
  {
    exportName: "TelegramBrandIcon",
    centralName: "IconTelegram",
    variant: outlined,
    source: "central",
  },
  {
    exportName: "WechatBrandIcon",
    centralName: "IconWechat",
    // Central draws this platform mark fill-only in every package, like the
    // other brand marks; it only ever sits beside them.
    variant: outlined,
    source: "central",
  },
  {
    exportName: "DiscordBrandIcon",
    centralName: "IconDiscord",
    variant: outlined,
    source: "central",
  },
  {
    exportName: "ChatBubbleIcon",
    centralName: "IconChatBubble7",
    variant: outlined,
    source: "central",
  },
  {
    exportName: "TagLabelIcon",
    centralName: "IconTag",
    variant: outlined,
    source: "central",
  },
  {
    exportName: "EditBigIcon",
    centralName: "IconEditBig",
    variant: outlined,
    source: "figma",
    figmaNodeId: "7538:9405",
    figmaSource: "Left Sidebar / Comma Center title",
  },
  {
    exportName: "ChevronDoubleRightIcon",
    centralName: "IconChevronDoubleRight",
    variant: outlined,
    source: "figma",
    figmaNodeId: "439:7808",
    figmaSource: "Comma App / Tasks / right task chat / collapse",
  },
  {
    exportName: "ExpandSimpleIcon",
    centralName: "IconExpandSimple2",
    variant: outlined,
    source: "figma",
    figmaNodeId: "439:8056",
    figmaSource: "Comma App / Tasks / right task chat / expand",
  },
  {
    exportName: "ChainLink3Icon",
    centralName: "IconChainLink3",
    variant: outlined,
    source: "central",
    figmaSource: "Settings / Channels category (chain-link-3, url)",
  },
  {
    exportName: "ChainLinkIcon",
    centralName: "IconChainLink4",
    variant: outlined,
    source: "figma",
    figmaNodeId: "439:8064",
    figmaSource: "Comma App / Tasks / right task chat / copy link",
  },
  {
    exportName: "UnpinIcon",
    centralName: "IconUnpin",
    variant: outlined,
    source: "figma",
    figmaNodeId: "14:3531;3473:603379",
    figmaSource: "Comma App / Menu / unpin",
  },
  {
    exportName: "ArchiveIcon",
    centralName: "IconArchive1",
    variant: outlined,
    // Picked from Central for the Task menu's Archive action and the Settings
    // "Archived" category; no Figma node traced yet.
    source: "central",
    figmaSource: "Comma App / Menu / archive (archive, box, storage)",
  },
  {
    exportName: "InboxDeleteIcon",
    centralName: "IconArchiveJunk",
    variant: outlined,
    // Picked from Central for the Inbox "···" menu's Delete all / Delete all
    // read rows; no Figma node traced yet.
    source: "central",
    figmaSource: "Comma App / Inbox / actions menu / delete (archive-junk, box, x)",
  },
  {
    exportName: "InboxMarkUnreadIcon",
    centralName: "IconEmail2Unread",
    variant: outlined,
    // Picked from Central for the Inbox item menu's Mark as unread / Mark as
    // read row; no Figma node traced yet.
    source: "central",
    figmaSource: "Comma App / Inbox / item menu / mark as unread (email-2-unread)",
  },
  {
    exportName: "PinIcon",
    centralName: "IconPin",
    variant: outlined,
    source: "central",
    figmaSource:
      "Comma App / Menu / Pin task, confirmed as pin in the Central Icons Figma library",
  },
  {
    exportName: "TrashCanIcon",
    centralName: "IconTrashCan",
    variant: outlined,
    source: "figma",
    figmaNodeId: "14:3534;3473:603379",
    figmaSource: "Comma App / Menu / trash-can, delete, remove, garbage, waste",
  },
  {
    exportName: "CheckIcon",
    centralName: "IconCheckmark1Small",
    variant: outlined,
    source: "figma",
    figmaNodeId: "1097:63713;1097:64015;1097:63897",
    figmaSource: "Checkbox / checked sm",
  },
  {
    exportName: "CheckLargeIcon",
    centralName: "IconCheckmark1",
    variant: outlined,
    source: "figma",
    figmaNodeId: "1371:19133;1097:64015;1097:63897",
    figmaSource:
      "Comma App (P0HbtMUd3lTy0FcGn0ojxT) / Checkbox / checked (list) — tick spans 8 of the 12px frame",
  },
  {
    exportName: "XIcon",
    centralName: "IconCrossSmall",
    variant: outlined,
    source: "figma",
    figmaNodeId: "7598:5556",
    figmaSource: "Toast / single / close",
  },
  {
    exportName: "CrossLargeIcon",
    centralName: "IconCrossLarge",
    variant: outlined,
    source: "figma",
    figmaNodeId: "7592:291;7592:263;7546:22589;7798:28577",
    figmaSource:
      "AI Input / attachment / Tag close X; Chat panel / generated media preview close (cross-large, crossed large, close)",
  },
  {
    exportName: "ToastCloseIcon",
    centralName: "IconCrossSmall",
    variant: outlined,
    source: "figma",
    figmaNodeId: "7598:5556",
    figmaSource: "Toast / single / close",
  },
  {
    exportName: "ToastGaugeIcon",
    centralName: "IconGauge",
    variant: filled,
    source: "central",
    figmaSource:
      "Toast / out of credits (gauge, tachometer, performance, speed, scale)",
  },
  {
    exportName: "ToastInfoIcon",
    centralName: "IconCircleInfo",
    variant: filled,
    source: "figma",
    figmaNodeId: "7601:17425",
    figmaSource: "Toast / single / info",
  },
  {
    exportName: "ToastSuccessIcon",
    centralName: "IconCircleCheck",
    variant: filled,
    source: "figma",
    figmaNodeId: "7602:2354",
    figmaSource: "Toast / component set",
  },
  {
    exportName: "DialogEnterIcon",
    centralName: "IconArrowCornerDownLeft",
    variant: filled,
    source: "figma",
    figmaNodeId: "7601:17311;7724:26594",
    figmaSource: "Dialog / Save shortcut / arrow-corner-down-left",
  },
  {
    exportName: "StatusDot",
    centralName: "IconCircle",
    variant: filled,
    source: "figma",
    figmaNodeId: "3281:380655",
    figmaSource: "Dropdown / dot leading item",
  },
  // Drive icons. Figma file key P0HbtMUd3lTy0FcGn0ojxT.
  {
    exportName: "Folder2Icon",
    centralName: "IconFolder2",
    variant: outlined,
    source: "figma",
    figmaNodeId: "1371:17466",
    figmaSource: "Comma App / Drive / sidebar entry (folder-2)",
  },
  {
    exportName: "Cursor1Icon",
    centralName: "IconCursor1",
    // Central draws this one at 2.05556, which `[stroke-width="2"]` cannot
    // thin, so it comes pre-thinned (see preThinnedAppIconVariant).
    variant: preThinned,
    source: "central",
    figmaSource: "Comma App / Drive / selection bar Ask Comma agent (cursor-1, arrow)",
  },
  {
    exportName: "Folder1Icon",
    centralName: "IconFolder1",
    variant: outlined,
    source: "figma",
    figmaNodeId: "1371:18062",
    figmaSource: "Comma App / Drive / space rail + transfer reveal (folder-1)",
  },
  {
    exportName: "FolderAddRightIcon",
    centralName: "IconFolderAddRight",
    variant: outlined,
    source: "figma",
    figmaNodeId: "1371:18062",
    figmaSource: "Comma App / Drive / rail menu new folder (folder-add-right)",
  },
  {
    exportName: "FolderUploadIcon",
    centralName: "IconFolderUpload",
    variant: outlined,
    source: "figma",
    figmaNodeId: "1371:18062",
    figmaSource: "Comma App / Drive / upload folder (folder-upload)",
  },
  {
    exportName: "FolderEditIcon",
    centralName: "IconFolderEdit",
    variant: outlined,
    source: "figma",
    figmaNodeId: "1371:18062",
    figmaSource: "Comma App / Drive / space menu rename (folder-edit)",
  },
  {
    exportName: "CloudOffIcon",
    centralName: "IconCloudOff",
    variant: outlined,
    source: "figma",
    figmaNodeId: "1371:18062",
    figmaSource: "Comma App / Drive / space not synced to this device (cloud-off)",
  },
  {
    exportName: "CloudSyncIcon",
    centralName: "IconCloudSync",
    variant: outlined,
    source: "figma",
    figmaNodeId: "1371:18062",
    figmaSource: "Comma App / Drive / local sync trigger + panel (cloud-sync)",
  },
  {
    exportName: "CloudCheckIcon",
    centralName: "IconCloudCheck",
    variant: outlined,
    source: "figma",
    figmaNodeId: "1371:18062",
    figmaSource: "Comma App / Drive / local sync on (cloud-check)",
  },
  {
    exportName: "CloudUploadIcon",
    centralName: "IconCloudUpload",
    variant: outlined,
    source: "figma",
    figmaNodeId: "1371:18062",
    figmaSource: "Comma App / Drive / add-files menu upload files (cloud-upload)",
  },
  {
    exportName: "HistoryIcon",
    centralName: "IconHistory",
    variant: outlined,
    source: "figma",
    figmaNodeId: "1371:18062",
    figmaSource: "Comma App / Drive / sync history (history)",
  },
  {
    exportName: "BranchIcon",
    centralName: "IconBranch",
    variant: outlined,
    source: "figma",
    figmaNodeId: "1371:18105",
    figmaSource: "Comma App / Drive / file versions badge (branch)",
  },
  {
    exportName: "ArrowTopBottomIcon",
    centralName: "IconArrowTopBottom",
    variant: outlined,
    source: "figma",
    figmaNodeId: "1371:18050",
    figmaSource: "Comma App / Drive / transfer toolbar button (arrow-top-bottom)",
  },
  {
    exportName: "CloudSimpleUploadIcon",
    centralName: "IconCloudSimpleUpload",
    variant: outlined,
    source: "figma",
    figmaNodeId: "1371:19066",
    figmaSource: "Comma App / Drive / transfer empty state (cloud-simple-upload)",
  },
  {
    exportName: "FolderOpenIcon",
    centralName: "IconFolderOpen",
    variant: outlined,
    source: "figma",
    figmaNodeId: "1371:20442",
    figmaSource: "Comma App / Drive / empty folder state (folder-open)",
  },
  {
    exportName: "CircleCheckFilledIcon",
    centralName: "IconCircleCheck",
    variant: filled,
    source: "figma",
    figmaNodeId: "1364:13207",
    figmaSource: "Comma App / Drive / transfer row success (circle-check, filled)",
  },
  // Shared app/navigation icons.
  {
    exportName: "HomeIcon",
    centralName: "IconHomeRoof",
    variant: outlined,
    source: "figma",
    figmaNodeId: "1384:23998",
    figmaSource:
      "Comma App (P0HbtMUd3lTy0FcGn0ojxT) / Left rail / Home (home-roof, house)",
  },
  {
    exportName: "ClockIcon",
    centralName: "IconClock",
    variant: outlined,
    source: "figma",
    figmaNodeId: "1384:24039",
    figmaSource:
      "Comma App (P0HbtMUd3lTy0FcGn0ojxT) / Window bar / Recent tasks (clock, time, timer)",
  },
  {
    exportName: "GaugeIcon",
    centralName: "IconGauge",
    variant: outlined,
    source: "central",
    figmaSource:
      "Chat out-of-credits notice (gauge, tachometer, performance, speed, scale)",
  },
  {
    exportName: "InboxIcon",
    centralName: "IconBox2",
    variant: outlined,
    source: "figma",
    figmaNodeId: "7601:14308;7641:22656;7538:11870",
    figmaSource: "Left Sidebar / box-2, inbox, archive, tray, shelf",
  },
  {
    exportName: "CalendarIcon",
    centralName: "IconCalendarDays",
    variant: outlined,
    source: "figma",
    figmaNodeId: "7538:17946",
    figmaSource: "Left Sidebar / home / Schedules nav",
  },
  {
    exportName: "ListChecksIcon",
    centralName: "IconPlanning",
    variant: outlined,
    source: "figma",
    figmaNodeId: "7601:14308;7781:25237;7538:11870",
    figmaSource: "Left Sidebar / planning, list, checklist",
  },
  {
    exportName: "ListBulletsIcon",
    centralName: "IconListBullets",
    variant: outlined,
    source: "central",
    figmaSource: "Task page header / expand task details (list-bullets)",
  },
  {
    exportName: "FlashcardsIcon",
    centralName: "IconFlashcards",
    variant: outlined,
    source: "central",
    figmaSource: "Settings / Labels row menu / view labeled tasks (flashcards, cards)",
  },
  {
    exportName: "BookIcon",
    centralName: "IconBook",
    // Central ships this one fill-only; taken pre-thinned (see preThinnedAppIconVariant).
    variant: preThinned,
    source: "figma",
    figmaNodeId: "7538:17946",
    figmaSource: "Left Sidebar / home / Books nav",
  },
  {
    exportName: "PuzzleIcon",
    centralName: "IconPuzzle",
    variant: outlined,
    source: "figma",
    figmaNodeId: "7538:17946",
    figmaSource: "Left Sidebar / home / Plugins nav",
  },
  {
    exportName: "SettingsIcon",
    centralName: "IconSettingsGear2",
    variant: outlined,
    source: "figma",
    figmaNodeId: "7634:18931",
    figmaSource: "Left Sidebar / settings variant",
  },
  {
    exportName: "PeopleCircleIcon",
    centralName: "IconPeopleCircle",
    variant: outlined,
    source: "figma",
    figmaNodeId: "299:5791;7638:22320;7538:11883",
    figmaSource:
      "Comma App (P0HbtMUd3lTy0FcGn0ojxT) / Settings / people-circle, user-circle,avatar,profile",
  },
  {
    exportName: "PaintBrushIcon",
    centralName: "IconPaintBrush",
    variant: outlined,
    source: "figma",
    figmaNodeId: "299:5791;7634:19099;7538:11870",
    figmaSource:
      "Comma App (P0HbtMUd3lTy0FcGn0ojxT) / Settings / paint-brush, design, color, appearance",
  },
  {
    exportName: "AudioIcon",
    centralName: "IconAudio",
    variant: outlined,
    source: "figma",
    figmaNodeId: "299:5791;7634:19100;7538:11870",
    figmaSource:
      "Comma App (P0HbtMUd3lTy0FcGn0ojxT) / Settings / audio, music, playlist, musical-note",
  },
  {
    exportName: "CmdIcon",
    centralName: "IconCmd",
    variant: outlined,
    source: "figma",
    figmaNodeId: "299:5791;7638:19369;7538:11870",
    figmaSource:
      "Comma App (P0HbtMUd3lTy0FcGn0ojxT) / Settings / cmd, command, apple, key",
  },
  {
    exportName: "ApiConnectionIcon",
    centralName: "IconApiConnection",
    variant: outlined,
    source: "central",
    figmaSource:
      "Comma App (P0HbtMUd3lTy0FcGn0ojxT) / Settings / api-connection, api, endpoint, model provider",
  },
  {
    exportName: "ConsoleSimpleIcon",
    centralName: "IconConsoleSimple",
    variant: outlined,
    source: "central",
    figmaSource:
      "Comma App (P0HbtMUd3lTy0FcGn0ojxT) / Settings / console-simple, terminal, proxy, subscription",
  },
  {
    exportName: "CreditCard2Icon",
    centralName: "IconCreditCard2",
    variant: outlined,
    source: "figma",
    figmaNodeId: "299:5791;7634:19101;7538:11870",
    figmaSource:
      "Comma App (P0HbtMUd3lTy0FcGn0ojxT) / Settings / credit-card-2, card, payment",
  },
  {
    exportName: "DevicesIcon",
    centralName: "IconDevices",
    variant: outlined,
    source: "figma",
    figmaNodeId: "299:5791;7638:19129;7538:11870",
    figmaSource:
      "Comma App (P0HbtMUd3lTy0FcGn0ojxT) / Settings / devices, macbook, iphone, phone, connected",
  },
  {
    exportName: "CallIcon",
    centralName: "IconCall",
    variant: outlined,
    source: "central",
    figmaSource:
      "Settings / Voice category (Central Icons catalog; no Figma node yet: call, phone, telephone)",
  },
  {
    exportName: "MacbookIcon",
    centralName: "IconMacbook",
    variant: outlined,
    source: "figma",
    figmaNodeId: "1484:17996",
    figmaSource:
      "Comma App (P0HbtMUd3lTy0FcGn0ojxT) / Task properties / macbook, laptop, computer",
  },
  {
    exportName: "WindowCursorIcon",
    centralName: "IconWindowCursor",
    variant: outlined,
    source: "figma",
    figmaNodeId: "299:5791;7638:19132;7538:11870",
    figmaSource:
      "Comma App (P0HbtMUd3lTy0FcGn0ojxT) / Settings / window-cursor, visit page, open app",
  },
  {
    exportName: "BellIcon",
    centralName: "IconBell",
    variant: outlined,
    source: "central",
    figmaSource: "Comma App (P0HbtMUd3lTy0FcGn0ojxT) / Settings / bell, notifications",
  },
  {
    exportName: "Filter2Icon",
    centralName: "IconFilter2",
    variant: outlined,
    source: "figma",
    figmaNodeId: "439:7346",
    figmaSource: "Comma App (P0HbtMUd3lTy0FcGn0ojxT) / Tasks toolbar / filter-2, sort",
  },
  {
    exportName: "SettingsSliderHorizontalIcon",
    centralName: "IconSettingsSliderHor",
    variant: outlined,
    source: "figma",
    figmaNodeId: "439:7347",
    figmaSource:
      "Comma App (P0HbtMUd3lTy0FcGn0ojxT) / Tasks toolbar / settings-slider-hor",
  },
  {
    exportName: "SettingsSliderThreeIcon",
    centralName: "IconSettingsSliderThree",
    variant: outlined,
    source: "figma",
    figmaNodeId: "929:13124",
    figmaSource:
      "Comma App (P0HbtMUd3lTy0FcGn0ojxT) / Comma Center recommendations / settings-slider-three",
  },
  {
    exportName: "LayoutColumnIcon",
    centralName: "IconLayoutColumn",
    // Central ships this one fill-only; taken pre-thinned (see preThinnedAppIconVariant).
    variant: preThinned,
    source: "central",
    figmaSource: "Comma App / Tasks view picker / layout-column, grid, column",
  },
  {
    exportName: "BarsThreeIcon",
    centralName: "IconBarsThree2",
    variant: outlined,
    source: "central",
    figmaSource: "Comma App / Tasks view picker / bars-three-2, menu, list, hamburger",
  },
  {
    exportName: "SquareCursorIcon",
    centralName: "IconSquareCursor",
    variant: filled,
    source: "central",
    figmaSource: "Comma App / Tasks filter / square-cursor, cursor box, arrow",
  },
  {
    exportName: "HelpCircleIcon",
    centralName: "IconCircleQuestionmark",
    variant: outlined,
    source: "figma",
    figmaNodeId: "85:1269",
    figmaSource: "Shared / Inputs / help icon",
  },
  {
    exportName: "MinusIcon",
    centralName: "IconMinusLarge",
    variant: outlined,
    source: "figma",
    figmaNodeId: "1224:6780",
    figmaSource: "Checkbox / indeterminate sm",
  },
  {
    exportName: "CircleMinusIcon",
    centralName: "IconCircleMinus",
    variant: filled,
    source: "central",
    figmaSource: "Settings shortcut / clear action / circle-minus, remove",
  },
  {
    exportName: "PlusSmallIcon",
    centralName: "IconPlusSmall",
    variant: outlined,
    source: "figma",
    figmaNodeId: "7592:7045",
    figmaSource: "AI Input / default / plus",
  },
  {
    exportName: "GlobeIcon",
    centralName: "IconGlobe",
    variant: outlined,
    source: "figma",
    figmaNodeId: "454:7128",
    figmaSource: "Comma-App / sidebar browser tab / globus, map, earth, globe",
  },
  {
    exportName: "ArrowLeftIcon",
    centralName: "IconArrowLeft",
    variant: outlined,
    source: "figma",
    figmaNodeId: "7542:2082",
    figmaSource: "Chat panel",
  },
  {
    exportName: "ArrowRightIcon",
    centralName: "IconArrowRight",
    variant: outlined,
    source: "figma",
    figmaNodeId: "7542:2082",
    figmaSource: "Chat panel",
  },
  {
    exportName: "ReloadIcon",
    centralName: "IconArrowRotateClockwise",
    variant: outlined,
    source: "central",
    figmaSource: "arrow-rotate-clockwise, rotate-right / browser reload action",
  },
  {
    exportName: "ResetIcon",
    centralName: "IconArrowRotateCounterClockwise",
    variant: outlined,
    source: "central",
    figmaSource: "arrow-rotate-counter-clockwise / reset a setting to its default",
  },
  {
    exportName: "CubeIcon",
    centralName: "Icon3dBoxTop",
    variant: outlined,
    source: "central",
    figmaSource: "Skills / 3d-box-top, shaders, model, cube, ar",
  },
  {
    exportName: "EyeIcon",
    centralName: "IconEyeOpen",
    variant: outlined,
    source: "central",
    figmaSource: "Skills / file viewer / eye-open, show, see, reveal, preview",
  },
  {
    exportName: "CodeIcon",
    centralName: "IconCodeBrackets",
    variant: outlined,
    source: "central",
    figmaSource: "Skills / file viewer / code-brackets, source, markup",
  },
  {
    exportName: "FolderIcon",
    centralName: "IconFolder1",
    variant: outlined,
    source: "central",
    figmaSource: "Skills / file tree / folder-1, directory",
  },
  {
    exportName: "SparklesIcon",
    centralName: "IconSparklesTwo",
    variant: outlined,
    source: "figma",
    figmaNodeId: "7542:2082",
    figmaSource: "Chat panel",
  },
  {
    exportName: "SunIcon",
    centralName: "IconSun",
    variant: outlined,
    source: "central",
    figmaSource: "Appearance custom studio / sun, light",
  },
  {
    exportName: "MoonIcon",
    centralName: "IconMoon",
    variant: outlined,
    source: "central",
    figmaSource: "Appearance custom studio / moon, dark",
  },
  {
    exportName: "CircleDashedIcon",
    centralName: "IconCircleDashed",
    variant: outlined,
    source: "figma",
    figmaNodeId: "236:7006;845:12215",
    figmaSource:
      "Task List Item / content / Backlog; Comma App (P0HbtMUd3lTy0FcGn0ojxT) / Status Indicator / Backlog / circle-dashed",
  },
  {
    exportName: "CircleInfoIcon",
    centralName: "IconCircleInfo",
    variant: outlined,
    source: "figma",
    figmaNodeId: "236:7037;845:12244",
    // Both nodes still draw circle-info in Figma, but the app now ships
    // BubbleAlertIcon in the Needs Review slot (see its entry). Do not "fix"
    // the app back to this glyph from these node ids alone.
    figmaSource:
      "Task List Item / content / Needs Review; Comma App (P0HbtMUd3lTy0FcGn0ojxT) / Status Indicator / Needs Review / circle-info, info circle, tooltip, information",
  },
  {
    exportName: "CircleCheckIcon",
    centralName: "IconCircleCheck",
    variant: outlined,
    source: "figma",
    figmaNodeId: "7538:17946;845:12260",
    figmaSource:
      "Left Sidebar / pinned complete; Comma App (P0HbtMUd3lTy0FcGn0ojxT) / Status Indicator / Done / circle-check, check radio, circle, checkbox, check, checkmark, confirm",
  },
  {
    exportName: "CircleXIcon",
    centralName: "IconCircleX",
    variant: outlined,
    source: "figma",
    figmaNodeId: "7538:17946;845:12274",
    figmaSource:
      "Left Sidebar / pinned error; Comma App (P0HbtMUd3lTy0FcGn0ojxT) / Status Indicator / Cancel / circle-x, close, checkbox, remove",
  },
  {
    exportName: "LoaderIcon",
    centralName: "IconLoader",
    variant: outlined,
    source: "figma",
    figmaNodeId: "7538:17946;845:12232",
    figmaSource:
      "Left Sidebar / pinned loading; Comma App (P0HbtMUd3lTy0FcGn0ojxT) / Status Indicator / In progress / loader, spinner",
  },
  {
    exportName: "BubbleAlertIcon",
    centralName: "IconBubbleAlert",
    variant: outlined,
    source: "figma",
    figmaNodeId: "7538:17946",
    // Also the app's Needs Review glyph everywhere (Task cards, Status
    // Indicator, Side Chat, Inbox), which Figma still draws as circle-info.
    // The app leads the design file here; this is deliberate, not drift.
    figmaSource: "Left Sidebar / pinned warning",
  },
  {
    exportName: "ExclamationTriangleIcon",
    centralName: "IconExclamationTriangle",
    variant: outlined,
    source: "central",
    figmaSource:
      "Comma App / Tasks error state / exclamation-triangle, error, warning, alert",
  },
  {
    exportName: "PlaceholderIcon",
    centralName: "IconPlaceholder",
    variant: outlined,
    source: "figma",
    figmaNodeId: "7601:17311;7724:26557",
    figmaSource: "Dialog / shortcut placeholder",
  },
  {
    exportName: "ResizeAlignmentCenterIcon",
    centralName: "IconAlignmentCenter",
    variant: outlined,
    source: "central",
    figmaSource: "ResizeContainer development control / center",
  },
  {
    exportName: "ResizeArrowsAllSidesIcon",
    centralName: "IconArrowsAllSides",
    variant: outlined,
    source: "central",
    figmaSource: "ResizeContainer development control / move",
  },
  {
    exportName: "ResizeLockIcon",
    centralName: "IconLock",
    variant: outlined,
    source: "central",
    figmaSource: "ResizeContainer development control / locked",
  },
  {
    exportName: "ResizeUnlockedIcon",
    centralName: "IconUnlocked2",
    variant: outlined,
    source: "central",
    figmaSource: "ResizeContainer development control / unlocked",
  },
  {
    exportName: "BugIcon",
    centralName: "IconBug",
    variant: outlined,
    source: "central",
    figmaSource: "Settings / System / Debug category",
  },
  {
    exportName: "GithubBrandIcon",
    centralName: "IconGithub",
    variant: outlined,
    source: "central",
    figmaSource: "Plugin integration brand artwork / GitHub",
  },
  {
    exportName: "GoogleBrandIcon",
    centralName: "IconGoogle",
    variant: outlined,
    source: "central",
    figmaSource: "Plugin integration brand artwork / Google",
  },
  {
    exportName: "LinearBrandIcon",
    centralName: "IconLinear",
    variant: outlined,
    source: "central",
    figmaSource: "Plugin integration brand artwork / Linear",
  },
  {
    exportName: "NotionBrandIcon",
    centralName: "IconNotion",
    variant: outlined,
    source: "central",
    figmaSource: "Plugin integration brand artwork / Notion",
  },
  {
    exportName: "SlackBrandIcon",
    centralName: "IconSlack",
    variant: outlined,
    source: "central",
    figmaSource: "Plugin integration brand artwork / Slack",
  },
  {
    exportName: "MergedIcon",
    centralName: "IconMerged",
    variant: outlined,
    source: "central",
    figmaSource: "Recommendation link preview / Pull request merged",
  },
  {
    exportName: "PullRequestIcon",
    centralName: "IconPullRequest",
    variant: outlined,
    source: "central",
    figmaSource: "Recommendation link preview / Pull request open",
  },
  {
    exportName: "PullRequestClosedIcon",
    centralName: "IconPullRequestClosedSimple",
    variant: outlined,
    source: "central",
    figmaSource: "Recommendation link preview / Pull request closed",
  },
  {
    exportName: "ShapesPlusXSquareCircleIcon",
    centralName: "IconShapesPlusXSquareCircle",
    // Fill-only upstream, so it is taken pre-thinned rather than thinned by CSS.
    variant: preThinned,
    source: "central",
    figmaSource: "Settings / Recommendations category",
  },
  {
    exportName: "SquareGridCircleIcon",
    centralName: "IconSquareGridCircle",
    // Central draws this one at 1.995 in the stroke-2 package, which the
    // global `[stroke-width="2"]` token cannot thin; the 1.5 package is a
    // real 1.5 stroke, so it is taken pre-thinned.
    variant: preThinned,
    source: "central",
    figmaSource:
      "Comma App / Tasks filter / Platform / square-grid-circle, layout, grid, list, category, categories",
  },
  brandMark("apple", "IconApple"),
  brandMark("apple-music", "IconAppleMusic"),
  brandMark("app-store", "IconAppstore"),
  brandMark("google", "IconGoogle"),
  brandMark("google-play", "IconGooglePlayStore"),
  brandMark("nvidia", "IconNvidia"),
  brandMark("bitcoin", "IconBitcoin"),
  brandMark("ethereum", "IconEthereum"),
  brandMark("github", "IconGithub"),
  brandMark("linear", "IconLinear"),
  brandMark("notion", "IconNotion"),
  brandMark("slack", "IconSlack"),
  brandMark("figma", "IconFigma"),
  brandMark("jira", "IconJira"),
  brandMark("atlassian", "IconAtlassian"),
  brandMark("vercel", "IconVercel"),
  brandMark("supabase", "IconSupabase"),
  brandMark("framer", "IconFramer"),
  brandMark("webflow", "IconWebflow"),
  brandMark("todoist", "IconTodoist"),
  brandMark("npm", "IconNpm"),
  brandMark("stack-overflow", "IconStackOverflow"),
  brandMark("product-hunt", "IconProducthunt"),
  brandMark("replit", "IconReplit"),
  brandMark("x", "IconX"),
  brandMark("reddit", "IconReddit"),
  brandMark("discord", "IconDiscord"),
  brandMark("telegram", "IconTelegram"),
  brandMark("wechat", "IconWechat"),
  brandMark("whatsapp", "IconWhatsapp"),
  brandMark("tiktok", "IconTiktok"),
  brandMark("instagram", "IconInstagram"),
  brandMark("facebook", "IconFacebook"),
  brandMark("linkedin", "IconLinkedin"),
  brandMark("threads", "IconThreads"),
  brandMark("bluesky", "IconBluesky"),
  brandMark("pinterest", "IconPinterest"),
  brandMark("snapchat", "IconSnapchat"),
  brandMark("medium", "IconMedium"),
  brandMark("substack", "IconSubstack"),
  brandMark("youtube", "IconYoutube"),
  brandMark("spotify", "IconSpotify"),
  brandMark("twitch", "IconTwitch"),
  brandMark("steam", "IconSteam"),
  brandMark("playstation", "IconPlaystation"),
  brandMark("xbox", "IconXbox"),
  brandMark("nintendo-switch", "IconNintendoSwitch"),
  brandMark("chrome", "IconChrome"),
  brandMark("safari", "IconSafari"),
  brandMark("firefox", "IconFirefox"),
  brandMark("duolingo", "IconDuolingo"),
  brandMark("openai", "IconOpenai", filled),
  brandMark("anthropic", "IconAnthropic", filled),
  brandMark("claude", "IconClaudeai", filled),
  brandMark("gemini", "IconGemini", filled),
  brandMark("deepseek", "IconDeepseek", filled),
  brandMark("qwen", "IconQwen", filled),
  brandMark("kimi", "IconKimi", filled),
  brandMark("minimax", "IconMinimax", filled),
  brandMark("mistral", "IconMistral", filled),
  brandMark("meta-ai", "IconMetaAi", filled),
  brandMark("grok", "IconGrok", filled),
  brandMark("perplexity", "IconPerplexity", filled),
  brandMark("midjourney", "IconMidjourney", filled),
  brandMark("microsoft-copilot", "IconMicrosoftCopilot", filled),
] as const satisfies readonly IconRegistryEntry[];

export const iconRegistryByExport = Object.fromEntries(
  iconRegistry.map((entry) => [entry.exportName, entry])
) as Record<(typeof iconRegistry)[number]["exportName"], IconRegistryEntry>;
