import { IconQwen as CentralQwenBrandIcon } from "@central-icons-react/round-filled-radius-2-stroke-2/IconQwen";
import { IconGrok as CentralGrokBrandIcon } from "@central-icons-react/round-filled-radius-2-stroke-2/IconGrok";
import { IconMetaAi as CentralMetaAiBrandIcon } from "@central-icons-react/round-filled-radius-2-stroke-2/IconMetaAi";
import { IconMistral as CentralMistralBrandIcon } from "@central-icons-react/round-filled-radius-2-stroke-2/IconMistral";
import { IconDeepseek as CentralDeepSeekBrandIcon } from "@central-icons-react/round-filled-radius-2-stroke-2/IconDeepseek";
import { IconGemini as CentralGeminiBrandIcon } from "@central-icons-react/round-filled-radius-2-stroke-2/IconGemini";
import { IconAnthropic as CentralAnthropicBrandIcon } from "@central-icons-react/round-filled-radius-2-stroke-2/IconAnthropic";
import { IconOpenaiCodex as CentralCodexBrandIcon } from "@central-icons-react/round-filled-radius-2-stroke-2/IconOpenaiCodex";
import { IconCloud as CentralCloudIcon } from "@central-icons-react/round-outlined-radius-2-stroke-2/IconCloud";
import { IconCloudySun as CentralCloudySunIcon } from "@central-icons-react/round-outlined-radius-2-stroke-2/IconCloudySun";
import { IconRainy as CentralRainIcon } from "@central-icons-react/round-outlined-radius-2-stroke-2/IconRainy";
import { IconSnowFlakes as CentralSnowIcon } from "@central-icons-react/round-outlined-radius-2-stroke-2/IconSnowFlakes";
import { IconTrainFrontView as CentralTrainIcon } from "@central-icons-react/round-outlined-radius-2-stroke-2/IconTrainFrontView";
import { Icon3dBoxTop as CentralCubeIcon } from "@central-icons-react/round-outlined-radius-2-stroke-2/Icon3dBoxTop";
import { IconArrowLeft as CentralArrowLeftIcon } from "@central-icons-react/round-outlined-radius-2-stroke-2/IconArrowLeft";
import { IconArrowInbox as CentralDownloadIcon } from "@central-icons-react/round-outlined-radius-2-stroke-2/IconArrowInbox";
import { IconArrowInbox as CentralMediaDownloadIcon } from "@central-icons-react/round-filled-radius-2-stroke-2/IconArrowInbox";
import { IconArrowRight as CentralArrowRightIcon } from "@central-icons-react/round-outlined-radius-2-stroke-2/IconArrowRight";
import { IconArrowRotateClockwise as CentralReloadIcon } from "@central-icons-react/round-outlined-radius-2-stroke-2/IconArrowRotateClockwise";
import { IconArrowRotateCounterClockwise as CentralResetIcon } from "@central-icons-react/round-outlined-radius-2-stroke-2/IconArrowRotateCounterClockwise";
import { IconArrowUp as CentralArrowUpIcon } from "@central-icons-react/round-outlined-radius-2-stroke-2/IconArrowUp";
import { IconBook as CentralBookIcon } from "@central-icons-react/round-outlined-radius-2-stroke-1.5/IconBook";
import { IconBug as CentralBugIcon } from "@central-icons-react/round-outlined-radius-2-stroke-2/IconBug";
import { IconBarsThree2 as CentralBarsThreeIcon } from "@central-icons-react/round-outlined-radius-2-stroke-2/IconBarsThree2";
import { IconBubbleAlert as CentralBubbleAlertIcon } from "@central-icons-react/round-outlined-radius-2-stroke-2/IconBubbleAlert";
import { IconCalendarDays as CentralCalendarIcon } from "@central-icons-react/round-outlined-radius-2-stroke-2/IconCalendarDays";
import { IconAudio as CentralAudioIcon } from "@central-icons-react/round-outlined-radius-2-stroke-2/IconAudio";
import { IconVoiceRecord as CentralVoiceRecordIcon } from "@central-icons-react/round-outlined-radius-2-stroke-2/IconVoiceRecord";
import { IconBell as CentralBellIcon } from "@central-icons-react/round-outlined-radius-2-stroke-2/IconBell";
import { IconCmd as CentralCmdIcon } from "@central-icons-react/round-outlined-radius-2-stroke-2/IconCmd";
import { IconConsoleSimple as CentralConsoleSimpleIcon } from "@central-icons-react/round-outlined-radius-2-stroke-2/IconConsoleSimple";
import { IconApiConnection as CentralApiConnectionIcon } from "@central-icons-react/round-outlined-radius-2-stroke-2/IconApiConnection";
import { IconCreditCard2 as CentralCreditCard2Icon } from "@central-icons-react/round-outlined-radius-2-stroke-2/IconCreditCard2";
import { IconDevices as CentralDevicesIcon } from "@central-icons-react/round-outlined-radius-2-stroke-2/IconDevices";
import { IconCall as CentralCallIcon } from "@central-icons-react/round-outlined-radius-2-stroke-2/IconCall";
import { IconMacbook as CentralMacbookIcon } from "@central-icons-react/round-outlined-radius-2-stroke-2/IconMacbook";
import { IconPaintBrush as CentralPaintBrushIcon } from "@central-icons-react/round-outlined-radius-2-stroke-2/IconPaintBrush";
import { IconPeopleCircle as CentralPeopleCircleIcon } from "@central-icons-react/round-outlined-radius-2-stroke-2/IconPeopleCircle";
import { IconWindowCursor as CentralWindowCursorIcon } from "@central-icons-react/round-outlined-radius-2-stroke-2/IconWindowCursor";
import { IconCheckmark1Small as CentralCheckIcon } from "@central-icons-react/round-outlined-radius-2-stroke-2/IconCheckmark1Small";
import { IconCheckmark1 as CentralCheckLargeIcon } from "@central-icons-react/round-outlined-radius-2-stroke-2/IconCheckmark1";
import { IconChevronDownMedium as CentralChevronDownIcon } from "@central-icons-react/round-outlined-radius-2-stroke-2/IconChevronDownMedium";
import { IconChevronDownSmall as CentralChevronDownSmallIcon } from "@central-icons-react/round-outlined-radius-2-stroke-2/IconChevronDownSmall";
import { IconChevronDoubleRight as CentralChevronDoubleRightIcon } from "@central-icons-react/round-outlined-radius-2-stroke-2/IconChevronDoubleRight";
import { IconChevronLeftSmall as CentralChevronLeftSmallIcon } from "@central-icons-react/round-outlined-radius-2-stroke-2/IconChevronLeftSmall";
import { IconChevronRightSmall as CentralChevronRightSmallIcon } from "@central-icons-react/round-outlined-radius-2-stroke-2/IconChevronRightSmall";
import { IconChevronTopSmall as CentralChevronTopSmallIcon } from "@central-icons-react/round-outlined-radius-2-stroke-2/IconChevronTopSmall";
import { IconChevronTriangleDownSmall as CentralChevronTriangleDownSmallIcon } from "@central-icons-react/round-filled-radius-2-stroke-2/IconChevronTriangleDownSmall";
import { IconCircleCheck as CentralCircleCheckIcon } from "@central-icons-react/round-outlined-radius-2-stroke-2/IconCircleCheck";
import { IconCircleCheck as CentralCircleCheckFilledIcon } from "@central-icons-react/round-filled-radius-2-stroke-2/IconCircleCheck";
import { IconCircleDashed as CentralCircleDashedIcon } from "@central-icons-react/round-outlined-radius-2-stroke-2/IconCircleDashed";
import { IconCircleInfo as CentralCircleInfoIcon } from "@central-icons-react/round-outlined-radius-2-stroke-2/IconCircleInfo";
import { IconCircleMinus as CentralCircleMinusIcon } from "@central-icons-react/round-filled-radius-2-stroke-2/IconCircleMinus";
import { IconCirclePlus as CentralCirclePlusIcon } from "@central-icons-react/round-outlined-radius-2-stroke-2/IconCirclePlus";
import { IconCircleQuestionmark as CentralHelpCircleIcon } from "@central-icons-react/round-outlined-radius-2-stroke-2/IconCircleQuestionmark";
import { IconCircleX as CentralCircleXIcon } from "@central-icons-react/round-outlined-radius-2-stroke-2/IconCircleX";
import { IconSquareBehindSquare6 as CentralCopyIcon } from "@central-icons-react/round-outlined-radius-2-stroke-2/IconSquareBehindSquare6";
import { IconCloseQuote1 as CentralCloseQuoteIcon } from "@central-icons-react/round-filled-radius-2-stroke-2/IconCloseQuote1";
import { IconCrossLarge as CentralCrossLargeIcon } from "@central-icons-react/round-outlined-radius-2-stroke-2/IconCrossLarge";
import { IconCrossSmall as CentralXIcon } from "@central-icons-react/round-outlined-radius-2-stroke-2/IconCrossSmall";
import { IconChainLink4 as CentralChainLinkIcon } from "@central-icons-react/round-outlined-radius-2-stroke-2/IconChainLink4";
import { IconChainLink3 as CentralChainLink3Icon } from "@central-icons-react/round-outlined-radius-2-stroke-2/IconChainLink3";
import { IconClock as CentralClockIcon } from "@central-icons-react/round-outlined-radius-2-stroke-2/IconClock";
import { IconGauge as CentralGaugeIcon } from "@central-icons-react/round-outlined-radius-2-stroke-2/IconGauge";
import { IconDotGrid1x3Horizontal as CentralMoreHorizontalIcon } from "@central-icons-react/round-outlined-radius-2-stroke-2/IconDotGrid1x3Horizontal";
import { IconDotGrid2x3 as CentralDragHandleIcon } from "@central-icons-react/round-outlined-radius-2-stroke-2/IconDotGrid2x3";
import { IconAirdrop as CentralAirDropIcon } from "@central-icons-react/round-outlined-radius-2-stroke-2/IconAirdrop";
import { IconArchive1 as CentralArchiveIcon } from "@central-icons-react/round-outlined-radius-2-stroke-2/IconArchive1";
import { IconArchiveJunk as CentralInboxDeleteIcon } from "@central-icons-react/round-outlined-radius-2-stroke-2/IconArchiveJunk";
import { IconEmail2Unread as CentralInboxMarkUnreadIcon } from "@central-icons-react/round-outlined-radius-2-stroke-2/IconEmail2Unread";
import { IconArrowTopBottom as CentralArrowTopBottomIcon } from "@central-icons-react/round-outlined-radius-2-stroke-2/IconArrowTopBottom";
import { IconBranch as CentralBranchIcon } from "@central-icons-react/round-outlined-radius-2-stroke-2/IconBranch";
import { IconCloudSimpleUpload as CentralCloudSimpleUploadIcon } from "@central-icons-react/round-outlined-radius-2-stroke-2/IconCloudSimpleUpload";
import { IconCursor1 as CentralCursor1Icon } from "@central-icons-react/round-outlined-radius-2-stroke-1.5/IconCursor1";
import { IconFolder1 as CentralFolder1Icon } from "@central-icons-react/round-outlined-radius-2-stroke-2/IconFolder1";
import { IconFolderAddRight as CentralFolderAddRightIcon } from "@central-icons-react/round-outlined-radius-2-stroke-2/IconFolderAddRight";
import { IconFolderUpload as CentralFolderUploadIcon } from "@central-icons-react/round-outlined-radius-2-stroke-2/IconFolderUpload";
import { IconFolderEdit as CentralFolderEditIcon } from "@central-icons-react/round-outlined-radius-2-stroke-2/IconFolderEdit";
import { IconCloudOff as CentralCloudOffIcon } from "@central-icons-react/round-outlined-radius-2-stroke-2/IconCloudOff";
import { IconCloudSync as CentralCloudSyncIcon } from "@central-icons-react/round-outlined-radius-2-stroke-2/IconCloudSync";
import { IconCloudCheck as CentralCloudCheckIcon } from "@central-icons-react/round-outlined-radius-2-stroke-2/IconCloudCheck";
import { IconCloudUpload as CentralCloudUploadIcon } from "@central-icons-react/round-outlined-radius-2-stroke-2/IconCloudUpload";
import { IconHistory as CentralHistoryIcon } from "@central-icons-react/round-outlined-radius-2-stroke-2/IconHistory";
import { IconFolder2 as CentralFolder2Icon } from "@central-icons-react/round-outlined-radius-2-stroke-2/IconFolder2";
import { IconFolderOpen as CentralFolderOpenIcon } from "@central-icons-react/round-outlined-radius-2-stroke-2/IconFolderOpen";
import { IconFolder1 as CentralFolderIcon } from "@central-icons-react/round-outlined-radius-2-stroke-2/IconFolder1";
import { IconEyeOpen as CentralEyeIcon } from "@central-icons-react/round-outlined-radius-2-stroke-2/IconEyeOpen";
import { IconCodeBrackets as CentralCodeIcon } from "@central-icons-react/round-outlined-radius-2-stroke-2/IconCodeBrackets";
import { IconEditBig as CentralEditBigIcon } from "@central-icons-react/round-outlined-radius-2-stroke-2/IconEditBig";
import { IconExclamationTriangle as CentralExclamationTriangleIcon } from "@central-icons-react/round-outlined-radius-2-stroke-2/IconExclamationTriangle";
import { IconExpandSimple2 as CentralExpandSimpleIcon } from "@central-icons-react/round-outlined-radius-2-stroke-2/IconExpandSimple2";
import { IconExpandSimple as CentralMediaExpandIcon } from "@central-icons-react/round-filled-radius-2-stroke-2/IconExpandSimple";
import { IconExpand45 as CentralExpand45Icon } from "@central-icons-react/round-outlined-radius-2-stroke-2/IconExpand45";
import { IconSquareArrowBottomLeftCorner as CentralSquareArrowBottomLeftCornerIcon } from "@central-icons-react/round-outlined-radius-2-stroke-2/IconSquareArrowBottomLeftCorner";
import { IconPictureInPicture as CentralPictureInPictureIcon } from "@central-icons-react/round-outlined-radius-2-stroke-2/IconPictureInPicture";
import { IconFileBend as CentralFileIcon } from "@central-icons-react/round-outlined-radius-2-stroke-2/IconFileBend";
import { IconFileText as CentralFileTextIcon } from "@central-icons-react/round-outlined-radius-2-stroke-2/IconFileText";
import { IconImages1 as CentralImageIcon } from "@central-icons-react/round-outlined-radius-2-stroke-2/IconImages1";
import { IconFilter2 as CentralFilter2Icon } from "@central-icons-react/round-outlined-radius-2-stroke-2/IconFilter2";
import { IconGithub as CentralGithubBrandIcon } from "@central-icons-react/round-outlined-radius-2-stroke-2/IconGithub";
import { IconMerged as CentralMergedIcon } from "@central-icons-react/round-outlined-radius-2-stroke-2/IconMerged";
import { IconPullRequest as CentralPullRequestIcon } from "@central-icons-react/round-outlined-radius-2-stroke-2/IconPullRequest";
import { IconPullRequestClosedSimple as CentralPullRequestClosedIcon } from "@central-icons-react/round-outlined-radius-2-stroke-2/IconPullRequestClosedSimple";
import { IconGoogle as CentralGoogleBrandIcon } from "@central-icons-react/round-outlined-radius-2-stroke-2/IconGoogle";
import { IconHomeRoof as CentralHomeIcon } from "@central-icons-react/round-outlined-radius-2-stroke-2/IconHomeRoof";
import { IconLayoutAlignLeft as CentralPanelLeftIcon } from "@central-icons-react/round-outlined-radius-2-stroke-1.5/IconLayoutAlignLeft";
import { IconLayoutAlignRight as CentralPanelRightIcon } from "@central-icons-react/round-outlined-radius-2-stroke-1.5/IconLayoutAlignRight";
import { IconLinear as CentralLinearBrandIcon } from "@central-icons-react/round-outlined-radius-2-stroke-2/IconLinear";
import { IconLayoutColumn as CentralLayoutColumnIcon } from "@central-icons-react/round-outlined-radius-2-stroke-1.5/IconLayoutColumn";
import { IconLoader as CentralLoaderIcon } from "@central-icons-react/round-outlined-radius-2-stroke-2/IconLoader";
import { IconLoadingCircle as CentralLoadingCircleIcon } from "@central-icons-react/round-outlined-radius-2-stroke-2/IconLoadingCircle";
import { IconBox2 as CentralInboxIcon } from "@central-icons-react/round-outlined-radius-2-stroke-2/IconBox2";
import { IconMicrophone as CentralMicrophoneIcon } from "@central-icons-react/round-outlined-radius-2-stroke-2/IconMicrophone";
import { IconMicrophone as CentralMicrophoneFilledIcon } from "@central-icons-react/round-filled-radius-2-stroke-2/IconMicrophone";
import { IconOpenai as CentralOpenAiIcon } from "@central-icons-react/round-filled-radius-2-stroke-2/IconOpenai";
import { IconClaudeai as CentralClaudeAiIcon } from "@central-icons-react/round-filled-radius-2-stroke-2/IconClaudeai";
import { IconMinusLarge as CentralMinusIcon } from "@central-icons-react/round-outlined-radius-2-stroke-2/IconMinusLarge";
import { IconNotion as CentralNotionBrandIcon } from "@central-icons-react/round-outlined-radius-2-stroke-2/IconNotion";
import { IconPaperclip1 as CentralPaperclipIcon } from "@central-icons-react/round-outlined-radius-2-stroke-2/IconPaperclip1";
import { IconPlaceholder as CentralPlaceholderIcon } from "@central-icons-react/round-outlined-radius-2-stroke-2/IconPlaceholder";
import { IconPause as CentralPauseIcon } from "@central-icons-react/round-filled-radius-2-stroke-2/IconPause";
import { IconStop as CentralStopIcon } from "@central-icons-react/round-filled-radius-2-stroke-2/IconStop";
import { IconMicrophoneOff as CentralMicrophoneOffIcon } from "@central-icons-react/round-outlined-radius-2-stroke-2/IconMicrophoneOff";
import { IconMicrophoneOff as CentralMicrophoneOffFilledIcon } from "@central-icons-react/round-filled-radius-2-stroke-2/IconMicrophoneOff";
import { IconPlanning as CentralListChecksIcon } from "@central-icons-react/round-outlined-radius-2-stroke-2/IconPlanning";
import { IconListBullets as CentralListBulletsIcon } from "@central-icons-react/round-outlined-radius-2-stroke-2/IconListBullets";
import { IconFlashcards as CentralFlashcardsIcon } from "@central-icons-react/round-outlined-radius-2-stroke-2/IconFlashcards";
import { IconPlay as CentralPlayIcon } from "@central-icons-react/round-filled-radius-2-stroke-2/IconPlay";
import { IconPlusLarge as CentralPlusIcon } from "@central-icons-react/round-outlined-radius-2-stroke-2/IconPlusLarge";
import { IconPlusSmall as CentralPlusSmallIcon } from "@central-icons-react/round-outlined-radius-2-stroke-2/IconPlusSmall";
import { IconGlobe as CentralGlobeIcon } from "@central-icons-react/round-outlined-radius-2-stroke-2/IconGlobe";
import { IconTag as CentralTagLabelIcon } from "@central-icons-react/round-outlined-radius-2-stroke-2/IconTag";
import { IconTelegram as CentralTelegramBrandIcon } from "@central-icons-react/round-outlined-radius-2-stroke-2/IconTelegram";
import { IconWechat as CentralWechatBrandIcon } from "@central-icons-react/round-outlined-radius-2-stroke-2/IconWechat";
import { IconPin as CentralPinIcon } from "@central-icons-react/round-outlined-radius-2-stroke-2/IconPin";
import { IconPuzzle as CentralPuzzleIcon } from "@central-icons-react/round-outlined-radius-2-stroke-2/IconPuzzle";
import { IconMagnifyingGlass as CentralSearchIcon } from "@central-icons-react/round-outlined-radius-2-stroke-2/IconMagnifyingGlass";
import { IconSettingsGear2 as CentralSettingsIcon } from "@central-icons-react/round-outlined-radius-2-stroke-2/IconSettingsGear2";
// Central ships this glyph fill-only; the stroke-1.5 package bakes it at the
// weight this app renders at (see preThinnedAppIconVariant).
import { IconShapesPlusXSquareCircle as CentralShapesPlusXSquareCircleIcon } from "@central-icons-react/round-outlined-radius-2-stroke-1.5/IconShapesPlusXSquareCircle";
import { IconSettingsSliderHor as CentralSettingsSliderHorizontalIcon } from "@central-icons-react/round-outlined-radius-2-stroke-2/IconSettingsSliderHor";
import { IconSettingsSliderThree as CentralSettingsSliderThreeIcon } from "@central-icons-react/round-outlined-radius-2-stroke-2/IconSettingsSliderThree";
import { IconSquareCursor as CentralSquareCursorIcon } from "@central-icons-react/round-filled-radius-2-stroke-2/IconSquareCursor";
import { IconSquareGridCircle as CentralSquareGridCircleIcon } from "@central-icons-react/round-outlined-radius-2-stroke-1.5/IconSquareGridCircle";
import { IconShieldCheck as CentralShieldCheckIcon } from "@central-icons-react/round-outlined-radius-2-stroke-2/IconShieldCheck";
import { IconSlack as CentralSlackBrandIcon } from "@central-icons-react/round-outlined-radius-2-stroke-2/IconSlack";
import { IconSparklesTwo as CentralSparklesIcon } from "@central-icons-react/round-outlined-radius-2-stroke-2/IconSparklesTwo";
import { IconSun as CentralSunIcon } from "@central-icons-react/round-outlined-radius-2-stroke-2/IconSun";
import { IconMoon as CentralMoonIcon } from "@central-icons-react/round-outlined-radius-2-stroke-2/IconMoon";
import { IconTrashCan as CentralTrashCanIcon } from "@central-icons-react/round-outlined-radius-2-stroke-2/IconTrashCan";
import { IconUnpin as CentralUnpinIcon } from "@central-icons-react/round-outlined-radius-2-stroke-2/IconUnpin";
import { IconVideo as CentralVideoIcon } from "@central-icons-react/round-outlined-radius-2-stroke-2/IconVideo";
import { IconVolumeFull as CentralVolumeFullIcon } from "@central-icons-react/round-filled-radius-2-stroke-2/IconVolumeFull";
import { IconVolumeHalf as CentralVolumeHalfIcon } from "@central-icons-react/round-filled-radius-2-stroke-2/IconVolumeHalf";
import { IconVolumeOff as CentralVolumeOffIcon } from "@central-icons-react/round-filled-radius-2-stroke-2/IconVolumeOff";
import { IconCircle as CentralStatusDot } from "@central-icons-react/round-filled-radius-2-stroke-2/IconCircle";
import { createCentralIcon } from "./createCentralIcon";

export type { IconProps } from "./createCentralIcon";
export { centralIconPackage, parseCentralIconVariantName } from "./centralIconVariants";
export { iconRegistry, iconRegistryByExport } from "./iconRegistry";

export const PlaceholderIcon = createCentralIcon(CentralPlaceholderIcon);
export const ChevronDownIcon = createCentralIcon(CentralChevronDownIcon);
export const ChevronDownSmallIcon = createCentralIcon(CentralChevronDownSmallIcon);
export const ChevronTopSmallIcon = createCentralIcon(CentralChevronTopSmallIcon);
export const ChevronDoubleRightIcon = createCentralIcon(CentralChevronDoubleRightIcon);
export const ChevronLeftSmallIcon = createCentralIcon(CentralChevronLeftSmallIcon);
export const ChevronRightSmallIcon = createCentralIcon(CentralChevronRightSmallIcon);
export const ChevronTriangleDownSmallIcon = createCentralIcon(
  CentralChevronTriangleDownSmallIcon
);
export const CheckIcon = createCentralIcon(CentralCheckIcon);
export const CheckLargeIcon = createCentralIcon(CentralCheckLargeIcon);
export const XIcon = createCentralIcon(CentralXIcon);
export const CrossLargeIcon = createCentralIcon(CentralCrossLargeIcon);
export const CloseQuoteIcon = createCentralIcon(CentralCloseQuoteIcon);
export const ChainLinkIcon = createCentralIcon(CentralChainLinkIcon);
export const ChainLink3Icon = createCentralIcon(CentralChainLink3Icon);
export const PinIcon = createCentralIcon(CentralPinIcon);
export const UnpinIcon = createCentralIcon(CentralUnpinIcon);
export const TrashCanIcon = createCentralIcon(CentralTrashCanIcon);
export const HelpCircleIcon = createCentralIcon(CentralHelpCircleIcon);
export const PaperclipIcon = createCentralIcon(CentralPaperclipIcon);
export const PlusIcon = createCentralIcon(CentralPlusIcon);
export const PlusSmallIcon = createCentralIcon(CentralPlusSmallIcon);
export const GlobeIcon = createCentralIcon(CentralGlobeIcon);
export const TagLabelIcon = createCentralIcon(CentralTagLabelIcon);
export const TelegramBrandIcon = createCentralIcon(CentralTelegramBrandIcon);
export const WechatBrandIcon = createCentralIcon(CentralWechatBrandIcon);
export const MinusIcon = createCentralIcon(CentralMinusIcon);
export const CircleMinusIcon = createCentralIcon(CentralCircleMinusIcon);
export const CirclePlusIcon = createCentralIcon(CentralCirclePlusIcon);
export const ArrowUpIcon = createCentralIcon(CentralArrowUpIcon);
export const ArrowLeftIcon = createCentralIcon(CentralArrowLeftIcon);
export const ArrowRightIcon = createCentralIcon(CentralArrowRightIcon);
export const ReloadIcon = createCentralIcon(CentralReloadIcon);
export const ResetIcon = createCentralIcon(CentralResetIcon);
export const MicrophoneIcon = createCentralIcon(CentralMicrophoneIcon);
export const MicrophoneFilledIcon = createCentralIcon(CentralMicrophoneFilledIcon);
export const OpenAiIcon = createCentralIcon(CentralOpenAiIcon);
export const ClaudeAiIcon = createCentralIcon(CentralClaudeAiIcon);
export const CubeIcon = createCentralIcon(CentralCubeIcon);
export const EyeIcon = createCentralIcon(CentralEyeIcon);
export const CodeIcon = createCentralIcon(CentralCodeIcon);
export const FolderIcon = createCentralIcon(CentralFolderIcon);
export const SparklesIcon = createCentralIcon(CentralSparklesIcon);
export const SunIcon = createCentralIcon(CentralSunIcon);
export const MoonIcon = createCentralIcon(CentralMoonIcon);
export const ShieldCheckIcon = createCentralIcon(CentralShieldCheckIcon);
export const FileIcon = createCentralIcon(CentralFileIcon);
export const FileTextIcon = createCentralIcon(CentralFileTextIcon);
export const ImageIcon = createCentralIcon(CentralImageIcon);
export const VideoIcon = createCentralIcon(CentralVideoIcon);
export const CopyIcon = createCentralIcon(CentralCopyIcon);
export const PlayIcon = createCentralIcon(CentralPlayIcon);
export const PauseIcon = createCentralIcon(CentralPauseIcon);
export const StopIcon = createCentralIcon(CentralStopIcon);
export const MicrophoneOffIcon = createCentralIcon(CentralMicrophoneOffIcon);
export const MicrophoneOffFilledIcon = createCentralIcon(
  CentralMicrophoneOffFilledIcon
);
export const VolumeFullIcon = createCentralIcon(CentralVolumeFullIcon);
export const VolumeHalfIcon = createCentralIcon(CentralVolumeHalfIcon);
export const VolumeOffIcon = createCentralIcon(CentralVolumeOffIcon);
export const DownloadIcon = createCentralIcon(CentralDownloadIcon);
export const MediaDownloadIcon = createCentralIcon(CentralMediaDownloadIcon);
export const MediaExpandIcon = createCentralIcon(CentralMediaExpandIcon);
export const Expand45Icon = createCentralIcon(CentralExpand45Icon);
export const SquareArrowBottomLeftCornerIcon = createCentralIcon(
  CentralSquareArrowBottomLeftCornerIcon
);
export const PictureInPictureIcon = createCentralIcon(CentralPictureInPictureIcon);
export const SearchIcon = createCentralIcon(CentralSearchIcon);
export const InboxIcon = createCentralIcon(CentralInboxIcon);
export const HomeIcon = createCentralIcon(CentralHomeIcon);
export const ClockIcon = createCentralIcon(CentralClockIcon);
export const GaugeIcon = createCentralIcon(CentralGaugeIcon);
export const CalendarIcon = createCentralIcon(CentralCalendarIcon);
export const ListChecksIcon = createCentralIcon(CentralListChecksIcon);
export const ListBulletsIcon = createCentralIcon(CentralListBulletsIcon);
export const FlashcardsIcon = createCentralIcon(CentralFlashcardsIcon);
export const BookIcon = createCentralIcon(CentralBookIcon);
export const BugIcon = createCentralIcon(CentralBugIcon);
export const PuzzleIcon = createCentralIcon(CentralPuzzleIcon);
export const AirDropIcon = createCentralIcon(CentralAirDropIcon);
export const ArchiveIcon = createCentralIcon(CentralArchiveIcon);
export const InboxDeleteIcon = createCentralIcon(CentralInboxDeleteIcon);
export const InboxMarkUnreadIcon = createCentralIcon(CentralInboxMarkUnreadIcon);
export const ArrowTopBottomIcon = createCentralIcon(CentralArrowTopBottomIcon);
export const BranchIcon = createCentralIcon(CentralBranchIcon);
export const CloudSimpleUploadIcon = createCentralIcon(CentralCloudSimpleUploadIcon);
export const Cursor1Icon = createCentralIcon(CentralCursor1Icon);
export const Folder1Icon = createCentralIcon(CentralFolder1Icon);
export const FolderAddRightIcon = createCentralIcon(CentralFolderAddRightIcon);
export const FolderUploadIcon = createCentralIcon(CentralFolderUploadIcon);
export const FolderEditIcon = createCentralIcon(CentralFolderEditIcon);
export const CloudOffIcon = createCentralIcon(CentralCloudOffIcon);
export const CloudSyncIcon = createCentralIcon(CentralCloudSyncIcon);
export const CloudCheckIcon = createCentralIcon(CentralCloudCheckIcon);
export const CloudUploadIcon = createCentralIcon(CentralCloudUploadIcon);
export const HistoryIcon = createCentralIcon(CentralHistoryIcon);
export const Folder2Icon = createCentralIcon(CentralFolder2Icon);
export const FolderOpenIcon = createCentralIcon(CentralFolderOpenIcon);
export const EditBigIcon = createCentralIcon(CentralEditBigIcon);
export const ExpandSimpleIcon = createCentralIcon(CentralExpandSimpleIcon);
export const SettingsIcon = createCentralIcon(CentralSettingsIcon);
export const ShapesPlusXSquareCircleIcon = createCentralIcon(
  CentralShapesPlusXSquareCircleIcon
);
export const PeopleCircleIcon = createCentralIcon(CentralPeopleCircleIcon);
export const PaintBrushIcon = createCentralIcon(CentralPaintBrushIcon);
export const AudioIcon = createCentralIcon(CentralAudioIcon);
export const VoiceRecordIcon = createCentralIcon(CentralVoiceRecordIcon);
export const BellIcon = createCentralIcon(CentralBellIcon);
export const CmdIcon = createCentralIcon(CentralCmdIcon);
export const ConsoleSimpleIcon = createCentralIcon(CentralConsoleSimpleIcon);
export const ApiConnectionIcon = createCentralIcon(CentralApiConnectionIcon);
export const CreditCard2Icon = createCentralIcon(CentralCreditCard2Icon);
export const DevicesIcon = createCentralIcon(CentralDevicesIcon);
export const CallIcon = createCentralIcon(CentralCallIcon);
export const MacbookIcon = createCentralIcon(CentralMacbookIcon);
export const WindowCursorIcon = createCentralIcon(CentralWindowCursorIcon);
export const Filter2Icon = createCentralIcon(CentralFilter2Icon);
export const LayoutColumnIcon = createCentralIcon(CentralLayoutColumnIcon);
export const BarsThreeIcon = createCentralIcon(CentralBarsThreeIcon);
export const SettingsSliderHorizontalIcon = createCentralIcon(
  CentralSettingsSliderHorizontalIcon
);
export const SettingsSliderThreeIcon = createCentralIcon(
  CentralSettingsSliderThreeIcon
);
export const SquareCursorIcon = createCentralIcon(CentralSquareCursorIcon);
export const SquareGridCircleIcon = createCentralIcon(CentralSquareGridCircleIcon);
export const PanelLeftIcon = createCentralIcon(CentralPanelLeftIcon);
export const PanelRightIcon = createCentralIcon(CentralPanelRightIcon);
export const MoreHorizontalIcon = createCentralIcon(CentralMoreHorizontalIcon);
export const DragHandleIcon = createCentralIcon(CentralDragHandleIcon);
export const CircleCheckIcon = createCentralIcon(CentralCircleCheckIcon);
export const CircleCheckFilledIcon = createCentralIcon(CentralCircleCheckFilledIcon);
export const CircleDashedIcon = createCentralIcon(CentralCircleDashedIcon);
export const CircleInfoIcon = createCentralIcon(CentralCircleInfoIcon);
export const CircleXIcon = createCentralIcon(CentralCircleXIcon);
export const LoaderIcon = createCentralIcon(CentralLoaderIcon);
export const LoadingCircleIcon = createCentralIcon(CentralLoadingCircleIcon);
export const BubbleAlertIcon = createCentralIcon(CentralBubbleAlertIcon);
export const ExclamationTriangleIcon = createCentralIcon(
  CentralExclamationTriangleIcon
);
export const StatusDot = createCentralIcon(CentralStatusDot);
export const GithubBrandIcon = createCentralIcon(CentralGithubBrandIcon);
export const MergedIcon = createCentralIcon(CentralMergedIcon);
export const PullRequestIcon = createCentralIcon(CentralPullRequestIcon);
export const PullRequestClosedIcon = createCentralIcon(CentralPullRequestClosedIcon);
export const GoogleBrandIcon = createCentralIcon(CentralGoogleBrandIcon);
export const LinearBrandIcon = createCentralIcon(CentralLinearBrandIcon);
export const NotionBrandIcon = createCentralIcon(CentralNotionBrandIcon);
export const SlackBrandIcon = createCentralIcon(CentralSlackBrandIcon);

export const CloudIcon = createCentralIcon(CentralCloudIcon);
export const CloudySunIcon = createCentralIcon(CentralCloudySunIcon);
export const RainIcon = createCentralIcon(CentralRainIcon);
export const SnowIcon = createCentralIcon(CentralSnowIcon);
export const TrainIcon = createCentralIcon(CentralTrainIcon);

export const CodexBrandIcon = createCentralIcon(CentralCodexBrandIcon);

export const AnthropicBrandIcon = createCentralIcon(CentralAnthropicBrandIcon);

export const GeminiBrandIcon = createCentralIcon(CentralGeminiBrandIcon);

export const DeepSeekBrandIcon = createCentralIcon(CentralDeepSeekBrandIcon);

export const MistralBrandIcon = createCentralIcon(CentralMistralBrandIcon);

export const MetaAiBrandIcon = createCentralIcon(CentralMetaAiBrandIcon);

export const GrokBrandIcon = createCentralIcon(CentralGrokBrandIcon);

export const QwenBrandIcon = createCentralIcon(CentralQwenBrandIcon);
