defmodule SalixIM.TelegramTextSamplesTest do
  use ExUnit.Case, async: true

  alias SalixIM.TelegramText

  # Independent visible-text expectations, not snapshots generated by the adapter.
  @samples [
    {"screenshot", "**Agent Files（vfs）** / **Default workspace Connector（comma）**",
     "Agent Files（vfs） / Default workspace Connector（comma）"},
    {"mixed-language", "你好 **Peng**，版本 `v1.2.3` 已就绪 😀", "你好 Peng，版本 v1.2.3 已就绪 😀"},
    {"nested-emphasis", "**粗体里有 _斜体_** 和 *斜体里有 **粗体***", "粗体里有 斜体 和 斜体里有 粗体"},
    {"strike", "~~旧版本~~ → **新版本**", "旧版本 → 新版本"},
    {"nested-code", "**执行 `mix test` 后检查**", "执行 mix test 后检查"},
    {"link-code", "[`a_b`](https://example.test/a?x=1&y=2)", "a_b"},
    {"link-bold", "[**报告**](https://example.test/report)", "报告"},
    {"reference-link", "查看 [报告][r]\n\n[r]: https://example.test/report", "查看 报告"},
    {"autolink", "<https://example.test/a?q=1&x=2>", "https://example.test/a?q=1&x=2"},
    {"mailto", "[联系](mailto:peng@example.test)", "联系"},
    {"parenthesized-url", "[说明](https://example.test/a_(b))", "说明"},
    {"unsafe-link", "[不要执行](javascript:alert%281%29)", "不要执行"},
    {"credential-link", "[受限](https://user:password@example.test/a)", "受限"},
    {"image-as-link", "![截图说明](https://example.test/image.png)", "截图说明"},
    {"raw-html", "<b>不是标签</b> <script>alert(1)</script>",
     "<b>不是标签</b> <script>alert(1)</script>"},
    {"raw-buttons", "<tg-button type=\"callback\" data=\"secret\">按钮</tg-button>",
     "<tg-button type=\"callback\" data=\"secret\">按钮</tg-button>"},
    {"entities", "A &amp; B &lt; C &#x1F600;", "A & B < C 😀"},
    {"literal-entities-in-code", "`&amp; &lt; &#x1F600;`", "&amp; &lt; &#x1F600;"},
    {"escaped-markers", "\\*literal\\* \\[brackets\\] a_b_c", "*literal* [brackets] a_b_c"},
    {"inline-backtick", "``const value = `x`;``", "const value = `x`;"},
    {"json-code", "```json\n{\"html\": \"<b>&</b>\", \"value\": 42}\n```",
     "{\"html\": \"<b>&</b>\", \"value\": 42}"},
    {"shell-code", "```sh\ncurl 'https://example.test/?a=1&b=2'\nprintf '%s' '$HOME'\n```",
     "curl 'https://example.test/?a=1&b=2' printf '%s' '$HOME'"},
    {"unclosed-fence", "```ts\nconst x = '**literal**';", "const x = '**literal**';"},
    {"tilde-fence", "~~~\n<b>code</b> & x_y\n~~~", "<b>code</b> & x_y"},
    {"indented-code", "    x < y && y > z\n    **not bold**", "x < y && y > z **not bold**"},
    {"crlf", "**第一行**\r\n\r\n`第二行`", "第一行 第二行"},
    {"hard-break", "第一行  \n第二行", "第一行 第二行"},
    {"zwj-emoji", "**👨‍👩‍👧‍👦 👩🏽‍💻 🇸🇬**", "👨‍👩‍👧‍👦 👩🏽‍💻 🇸🇬"},
    {"combining", "**cafe\u0301** `e\u0301`", "cafe\u0301 e\u0301"},
    {"rtl", "**مرحبا** שלום `abc_123`", "مرحبا שלום abc_123"},
    {"punctuation", "（测试）「引用」￥123.45 / $9.99 + 50%", "（测试）「引用」￥123.45 / $9.99 + 50%"},
    {"literal-path", "`/tmp/a_b/[draft].md` 与 `C:\\Users\\Peng\\a.txt`",
     "/tmp/a_b/[draft].md 与 C:\\Users\\Peng\\a.txt"},
    {"inline-less-than", "1 < 2 > 0 & 3", "1 < 2 > 0 & 3"},
    {"html-comment", "<!-- keep this text -->", "<!-- keep this text -->"}
  ]

  for {name, source, expected} <- @samples do
    test "body and caption sample: #{name}" do
      source = unquote(source)
      expected = unquote(expected)
      assert {:ok, body} = TelegramText.message(source)
      assert {:ok, caption} = TelegramText.caption(source)

      for {mode, html} <- [
            body: body.fields["text"],
            caption: caption.fields.caption
          ] do
        assert_valid_html(html, mode)
        assert normalize(visible(html)) == normalize(expected), "#{mode}: #{inspect(html)}"
      end
    end
  end

  test "empty image and link labels keep their destination visible" do
    for source <- ["![](https://example.test/image.png)", "[](https://example.test/report)"] do
      assert {:ok, body} = TelegramText.message(source)
      html = body.fields["text"]
      assert String.trim(visible(html)) != ""
      assert visible(html) =~ "https://example.test/"
      assert {:ok, caption} = TelegramText.caption(source)
      assert visible(caption.fields.caption) =~ "https://example.test/"
    end
  end

  test "linked images and badges become one link, never nested anchors" do
    for source <- [
          "[![Build passing](https://example.test/badge.svg)](https://example.test/build)",
          "[**![logo](https://example.test/logo.png)**](https://example.test/home)",
          "[![](https://example.test/logo.png)](https://example.test/home)"
        ] do
      assert {:ok, body} = TelegramText.message(source)
      assert {:ok, caption} = TelegramText.caption(source)

      for {mode, html} <- [
            body: body.fields["text"],
            caption: caption.fields.caption
          ] do
        assert_valid_html(html, mode)
        assert length(Regex.scan(~r/<a /, html)) == 1
        assert String.trim(visible(html)) != ""
      end
    end
  end

  test "structured reply samples retain every distinct cell and list payload" do
    cases = [
      {"# 概览\n\n## 风险\n\n### 后续\n\n#### 四级\n\n##### 五级\n\n###### 六级", ~w(概览 风险 后续 四级 五级 六级)},
      {"> 外层引用\n>\n> > 内层引用\n\n结束", ~w(外层引用 内层引用 结束)},
      {"- 条目甲\n  - 子项乙\n  - 子项丙\n- 条目丁", ~w(条目甲 子项乙 子项丙 条目丁)},
      {"7. 步骤甲\n8. 步骤乙\n\n后续丙", ~w(步骤甲 步骤乙 后续丙)},
      {"| 项目 | 结果 |\n|:---|---:|\n| **加粗甲** | `代码乙` |\n| [链接丙](https://example.test) | 😀丁 |",
       ~w(项目 结果 加粗甲 代码乙 链接丙 😀丁)},
      {"| A | B |\n|---|---|\n| a\\|b | `<>&` |", ["A", "B", "a|b", "<>&"]},
      {"段落甲\n\n---\n\n段落乙", ~w(段落甲 段落乙)},
      {"结论甲\n======\n\n细节乙\n------", ~w(结论甲 细节乙)}
    ]

    for {source, tokens} <- cases do
      assert {:ok, body} = TelegramText.message(source)
      assert {:ok, caption} = TelegramText.caption(source)

      for {mode, html} <- [
            body: body.fields["text"],
            caption: caption.fields.caption
          ] do
        assert_valid_html(html, mode)
        text = visible(html)

        positions =
          Enum.map(tokens, fn token ->
            assert text =~ token, "#{mode} lost #{token}: #{inspect(html)}"
            {offset, _} = :binary.match(text, token)
            offset
          end)

        assert positions == Enum.sort(positions)
      end
    end
  end

  test "20-column tables retain all header and body cells" do
    headers = Enum.map(1..20, &"Header#{&1}X")
    values = Enum.map(1..20, &"Value#{&1}X")
    row = fn cells -> "|" <> Enum.join(cells, "|") <> "|\n" end
    source = row.(headers) <> row.(List.duplicate("---", 20)) <> row.(values)
    assert {:ok, body} = TelegramText.message(source)
    html = body.fields["text"]
    assert_valid_html(html, :body)
    refute html =~ "<table>"
    refute html =~ "<th>"
    refute html =~ "<td>"
    for token <- headers ++ values, do: assert(visible(html) =~ token)
  end

  test "1000 seeded malformed Markdown samples either render safely or return a bounded error" do
    :rand.seed(:exsss, {71, 208, 419})

    fragments = [
      "**",
      "_",
      "`",
      "```\n",
      "[x](",
      ")",
      "<a href=\"",
      "</b>",
      "![",
      "&amp;",
      "\\",
      "\n\n",
      "😀",
      "中文",
      "|---|",
      "- [ ]",
      "> "
    ]

    for _ <- 1..1000 do
      source =
        "start " <>
          Enum.map_join(1..16, fn _ ->
            Enum.at(fragments, :rand.uniform(length(fragments)) - 1)
          end) <> " end"

      for mode <- [:body, :caption] do
        result =
          if mode == :body, do: TelegramText.message(source), else: TelegramText.caption(source)

        case result do
          {:ok, rendered} ->
            html =
              if mode == :body,
                do: rendered.fields["text"],
                else: rendered.fields.caption

            assert_valid_html(html, mode)
            assert visible(html) =~ "start"
            assert visible(html) =~ "end"

          {:error, reason} ->
            assert is_binary(reason) and byte_size(reason) < 300
        end
      end
    end
  end

  test "code indentation and trailing spaces survive plain fallback" do
    source = "```\n  first\n    second  \n```"
    assert {:ok, body} = TelegramText.message(source)
    assert body.plain == "  first\n    second  \n"
  end

  test "nested lists and task lists use safe ordinary-message markup" do
    for source <- [
          "- 第一项\n  - 子项\n- 第二项",
          "3. 三\n4. 四\n   1. 子项",
          "- [x] Done\n- [ ] Todo",
          "- **标题**\n\n  描述\n\n  ```\n  code\n  ```"
        ] do
      assert {:ok, body} = TelegramText.message(source)
      assert_valid_html(body.fields["text"], :body)
      assert {:ok, caption} = TelegramText.caption(source)
      assert_valid_html(caption.fields.caption, :caption)
    end
  end

  test "1000 deterministic composition samples preserve payload and valid markup in both surfaces" do
    atoms = [
      "中文English",
      "😀",
      "👩🏽‍💻",
      "e\u0301",
      "مرحبا",
      "שלום",
      "a_b/c",
      "<>&\"'",
      "£€¥$",
      "[x](y)"
    ]

    wrappers = [
      fn x -> "`#{x}`" end,
      fn x -> "**`#{x}`**" end,
      fn x -> "*`#{x}`*" end,
      fn x -> "~~`#{x}`~~" end,
      fn x -> "[`#{x}`](https://example.test)" end,
      fn x -> "**start *`#{x}`* end**" end,
      fn x -> "```\n#{x}\n```" end,
      fn x -> "~~~text\n#{x}\n~~~" end,
      fn x -> "# `#{x}`" end,
      fn x -> "    #{x}" end
    ]

    for atom <- atoms, wrap <- wrappers, index <- 1..10 do
      marker = "sample#{index}"
      source = marker <> "\n\n" <> wrap.(atom) <> "\n\n" <> marker
      assert {:ok, body} = TelegramText.message(source)
      assert {:ok, caption} = TelegramText.caption(source)

      for {mode, html} <- [
            body: body.fields["text"],
            caption: caption.fields.caption
          ] do
        assert_valid_html(html, mode)
        text = visible(html)
        assert text =~ atom, "lost #{inspect(atom)} in #{inspect(source)}: #{inspect(html)}"
        assert length(Regex.scan(~r/sample#{index}(?!\d)/, text)) == 2
      end
    end
  end

  test "boundary matrix accepts exact limits and rejects one extra code unit" do
    for {format, limit} <- [{"markdown", 4096}, {"plain", 4096}] do
      for atom <- ["a", "中", "😀", "e\u0301"] do
        units = div(byte_size(:unicode.characters_to_binary(atom, :utf8, {:utf16, :little})), 2)
        text = String.duplicate(atom, div(limit, units))
        assert {:ok, _} = TelegramText.message(text, format)
        assert {:error, _} = TelegramText.message(text <> "x", format)
      end
    end

    for atom <- ["a", "中", "😀", "e\u0301"], format <- ["plain", "markdown"] do
      units = div(byte_size(:unicode.characters_to_binary(atom, :utf8, {:utf16, :little})), 2)
      text = String.duplicate(atom, div(1024, units))
      assert {:ok, _} = TelegramText.caption(text, format)
      assert {:error, _} = TelegramText.caption(text <> "x", format)
    end
  end

  # This validator covers our emitted subset, not arbitrary HTML or Telegram's
  # server parser. It deliberately checks structural rules independently of MDEx.
  defp assert_valid_html(html, mode) do
    allowed = ~w(b i s code pre a)

    tags = Regex.scan(~r/<(\/?)([a-z0-9]+)([^>]*)>/, html)

    stack =
      Enum.reduce(tags, [], fn [full, closing, tag, attrs], stack ->
        assert tag in allowed, "unsupported #{full} in #{mode}"

        if closing == "/" do
          assert List.first(stack) == tag, "unbalanced #{full}: #{inspect(stack)}"
          tl(stack)
        else
          if mode == :caption and tag in ["code", "pre"],
            do: assert(stack == [], "caption code overlaps #{inspect(stack)}")

          if tag == "a" do
            assert attrs =~ ~r/^ href="(?:https?:\/\/|mailto:)[^"<>]*"$/
            refute "a" in stack
          else
            assert attrs == ""
          end

          [tag | stack]
        end
      end)

    assert stack == [], "unclosed tags #{inspect(stack)}"
  end

  defp visible(html) do
    html
    |> String.replace("<br>", "\n")
    |> String.replace(~r/<[^>]*>/, "")
    |> String.replace("&lt;", "<")
    |> String.replace("&gt;", ">")
    |> String.replace("&quot;", "\"")
    |> String.replace("&amp;", "&")
  end

  defp normalize(text), do: text |> String.replace(~r/\s+/u, " ") |> String.trim()
end
