/**
 * Styles for the `comma.card` templates. Every value is a Comma token the host
 * resolves for the current theme; the rules also reset the runtime's defaults
 * for authored controls, which the templates do not use.
 *
 * Half-pixel lines are inset box-shadows: Chromium rounds a 0.5px border up
 * to 1px, while a 0.5px shadow ring draws one device pixel on a 2x screen.
 */
export const cardCss = `
.wc-card{container-type:inline-size;display:flex;flex-direction:column;gap:var(--spacing-lg);width:100%;max-width:var(--container-md);padding:var(--spacing-xl);border-radius:var(--radius-xl);background:var(--color-bg-popup-secondary);box-shadow:inset 0 0 0 var(--border-width-0-5) var(--color-border-primary),var(--shadow-xs);color:var(--color-text-secondary);font-size:var(--text-sm);line-height:var(--text-sm--line-height);font-weight:var(--font-weight-regular)}
.wc-card-sm{max-width:var(--container-xs)}
.wc-card ul,.wc-card ol{list-style:none;margin:0;padding:0}.wc-card p,.wc-card h3,.wc-card h4,.wc-card figure{margin:0}
.wc-head{display:flex;align-items:center;gap:var(--spacing-sm);min-width:0}
.wc-title{min-width:0;overflow:hidden;text-overflow:ellipsis;white-space:nowrap;font-size:var(--text-sm);line-height:var(--text-sm--line-height);font-weight:var(--font-weight-medium);color:var(--color-text-secondary)}
.wc-meta{margin-inline-start:auto;flex:none;font-size:var(--text-xs);line-height:var(--text-xs--line-height);color:var(--color-text-tertiary);font-variant-numeric:tabular-nums}
.wc-foot{display:flex;flex-wrap:wrap;align-items:center;gap:var(--spacing-md)}
.wc-src{display:flex;align-items:center;gap:var(--spacing-xs);flex:1;min-width:0;font-size:var(--text-xs);line-height:var(--text-xs--line-height);color:var(--color-text-tertiary)}.wc-src>span:last-child{overflow:hidden;text-overflow:ellipsis;white-space:nowrap}
.wc-glyph{display:inline-flex;flex:none;width:var(--spacing-lg);height:var(--spacing-lg)}.wc-glyph svg{width:100%;height:100%}
.wc-card .wc-action{display:inline-flex;align-items:center;justify-content:center;gap:var(--spacing-xs);min-height:0;padding:calc(var(--spacing-xs) - var(--border-width-default)) calc(var(--spacing-lg) - var(--border-width-default));border:var(--border-width-default) solid var(--color-button-secondary-border);border-radius:var(--radius-md);background:var(--color-button-secondary-bg);box-shadow:var(--shadow-xs);color:var(--color-button-secondary-fg);font-size:var(--text-sm);line-height:var(--text-sm--line-height);font-weight:var(--font-weight-medium);white-space:nowrap}
.wc-card .wc-action:hover{background:var(--color-bg-secondary);color:var(--color-text-primary)}.wc-card .wc-action .wc-icon{width:var(--spacing-2xl);height:var(--spacing-2xl)}
.wc-card a.wc-action{min-height:0}.wc-card a.wc-action:active{transform:scale(var(--motion-scale-pressed))}
.wc-sr{position:absolute;width:1px;height:1px;overflow:hidden;clip-path:inset(50%);white-space:nowrap}
.wc-icon{display:inline-flex;flex:none;align-items:center;justify-content:center}.wc-icon svg{width:100%;height:100%}
.wc-card [data-comma-icon] :where([stroke-width="2"]){stroke-width:var(--comma-icon-stroke-width,2)}
.wc-col{display:flex;flex-direction:column;min-width:0}.wc-grow{flex:1;min-width:0}.wc-end{align-items:flex-end;text-align:end}
.wc-row-center,.wc-row-start,.wc-row-end{display:flex;min-width:0}.wc-row-center{align-items:center}.wc-row-start{align-items:flex-start}.wc-row-end{align-items:flex-end}.wc-wrap{flex-wrap:wrap}.wc-between{justify-content:space-between}.wc-push{margin-inline-start:auto}
.wc-gap-xxs{gap:var(--spacing-xxs)}.wc-gap-xs{gap:var(--spacing-xs)}.wc-gap-sm{gap:var(--spacing-sm)}.wc-gap-md{gap:var(--spacing-md)}.wc-gap-lg{gap:var(--spacing-lg)}.wc-gap-xl{gap:var(--spacing-xl)}
.wc-pad-t{padding-top:var(--spacing-xs)}.wc-pad-b{padding-bottom:var(--spacing-xs)}.wc-pad-b-lg{padding-bottom:var(--spacing-lg)}.wc-invisible{visibility:hidden}.wc-dim{opacity:var(--opacity-disabled)}
.wc-baseline{display:inline-flex;align-items:baseline;gap:var(--spacing-xxs);flex:none}
.wc-clip{overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.wc-clamp-1,.wc-clamp-2{display:-webkit-box;-webkit-box-orient:vertical;overflow:hidden}.wc-clamp-1{-webkit-line-clamp:1}.wc-clamp-2{-webkit-line-clamp:2}
.wc-num{font-variant-numeric:tabular-nums}
.wc-micro{font-size:var(--text-micro);line-height:var(--text-micro--line-height)}.wc-xs{font-size:var(--text-xs);line-height:var(--text-xs--line-height)}.wc-sm{font-size:var(--text-sm);line-height:var(--text-sm--line-height)}.wc-md{font-size:var(--text-md);line-height:var(--text-md--line-height)}.wc-lg{font-size:var(--text-lg);line-height:var(--text-lg--line-height);letter-spacing:var(--text-lg--letter-spacing)}
.wc-title-3{font-size:var(--text-title-3);line-height:var(--text-title-3--line-height);letter-spacing:var(--text-title-3--letter-spacing)}.wc-title-2{font-size:var(--text-title-2);line-height:var(--text-title-2--line-height);letter-spacing:var(--text-title-2--letter-spacing)}
.wc-display-md{font-size:var(--text-display-md);line-height:var(--text-display-md--line-height);letter-spacing:var(--text-display-md--letter-spacing)}.wc-display-lg{font-size:var(--text-display-lg);line-height:var(--text-display-lg--line-height);letter-spacing:var(--text-display-lg--letter-spacing)}
.wc-display-md.wc-tight{line-height:var(--text-display-md)}.wc-display-lg.wc-tight{line-height:var(--text-display-lg)}
.wc-w5{font-weight:var(--font-weight-medium)}.wc-w6{font-weight:var(--font-weight-semibold)}
.wc-c1{color:var(--color-text-primary)}.wc-c2{color:var(--color-text-secondary)}.wc-c3{color:var(--color-text-tertiary)}.wc-c4{color:var(--color-text-quaternary)}
.wc-text-neutral{color:var(--color-text-tertiary)}.wc-text-brand{color:var(--color-fg-brand-primary)}.wc-text-success{color:var(--color-text-success-primary)}.wc-text-warning{color:var(--color-fg-warning-primary)}.wc-text-error{color:var(--color-text-error-primary)}
.wc-dot{flex:none;width:var(--spacing-sm);height:var(--spacing-sm);border-radius:50%}.wc-dot-neutral{background:var(--color-fg-quaternary)}.wc-dot-brand{background:var(--color-bg-brand-solid)}.wc-dot-success{background:var(--color-fg-success-primary)}.wc-dot-warning{background:var(--color-fg-warning-primary)}.wc-dot-error{background:var(--color-fg-error-primary)}.wc-dot-accent{background:var(--wc-accent)}
.wc-status{display:inline-flex;align-items:center;gap:var(--spacing-xs);white-space:nowrap;font-size:var(--text-xs);line-height:var(--text-xs--line-height)}
.wc-badge{display:inline-flex;align-items:center;width:fit-content;padding:var(--spacing-xxs) var(--spacing-md);border:var(--border-width-default) solid;border-radius:999px;font-size:var(--text-xs);line-height:var(--text-xs--line-height);font-weight:var(--font-weight-medium);white-space:nowrap}
.wc-badge-brand{background:var(--color-utility-brand-50);color:var(--color-utility-brand-700);border-color:var(--color-utility-brand-200)}.wc-badge-gray{background:var(--color-utility-gray-50);color:var(--color-utility-gray-700);border-color:var(--color-utility-gray-200)}
.wc-insight{padding:var(--spacing-sm) var(--spacing-md);border-radius:var(--radius-md);background:var(--color-bg-secondary);color:var(--color-text-primary)}
.wc-delta{display:inline-flex;align-items:center;gap:var(--spacing-xxs);font-size:var(--text-xs);line-height:var(--text-xs--line-height);font-weight:var(--font-weight-medium);font-variant-numeric:tabular-nums}.wc-delta .wc-icon{width:var(--spacing-lg);height:var(--spacing-lg)}.wc-down{rotate:180deg}
.wc-divided+.wc-divided{border-top:var(--border-width-default) solid var(--color-border-secondary)}
.wc-wx{display:inline-flex;flex:none}.wc-wx .wc-icon{width:100%;height:100%}.wc-wx-sun{color:var(--color-fg-warning-primary)}.wc-wx-moon{color:var(--color-utility-indigo-700)}.wc-wx-cloud{color:var(--color-fg-quaternary)}.wc-wx-rain{color:var(--color-utility-blue-700)}.wc-wx-snow{color:var(--color-utility-blue-300)}
.wc-glyph-xl{width:var(--spacing-xl);height:var(--spacing-xl)}.wc-glyph-md{width:var(--spacing-2xl);height:var(--spacing-2xl)}.wc-glyph-5xl{width:var(--spacing-5xl);height:var(--spacing-5xl)}
.wc-mark{display:inline-flex;flex:none;align-items:center;justify-content:center;font-weight:var(--font-weight-semibold)}.wc-mark-sm{width:var(--spacing-2xl);height:var(--spacing-2xl);border-radius:var(--radius-sm);font-size:var(--text-micro)}.wc-mark-md{width:var(--spacing-3xl);height:var(--spacing-3xl);border-radius:var(--radius-md);font-size:var(--text-xs)}.wc-mark-lg{width:var(--spacing-4xl);height:var(--spacing-4xl);border-radius:var(--radius-lg);font-size:var(--text-sm)}
.wc-brand{box-shadow:inset 0 0 0 var(--border-width-0-5) var(--color-border-primary);background:var(--color-bg-popup-secondary);color:var(--color-text-primary)}.wc-brand svg{width:66%;height:66%}.wc-arrive{animation:wc-fade var(--motion-duration-state-change) var(--motion-easing-smooth-out)}
.wc-avatar-blue{background:var(--color-utility-blue-50);color:var(--color-utility-blue-700)}.wc-avatar-purple{background:var(--color-utility-purple-50);color:var(--color-utility-purple-700)}.wc-avatar-success{background:var(--color-utility-success-50);color:var(--color-utility-success-700)}.wc-avatar-orange{background:var(--color-utility-orange-50);color:var(--color-utility-orange-700)}.wc-avatar-pink{background:var(--color-utility-pink-50);color:var(--color-utility-pink-700)}.wc-avatar-indigo{background:var(--color-utility-indigo-50);color:var(--color-utility-indigo-700)}
.wc-spark{position:relative;width:100%}.wc-spark-svg{display:block;width:100%;height:100%;overflow:visible}.wc-spark-end{position:absolute;right:0;width:var(--spacing-sm);height:var(--spacing-sm);border-radius:50%;translate:50% -50%;box-shadow:0 0 0 2px var(--color-bg-popup-secondary)}
.wc-ring{position:relative;display:inline-flex;flex:none;align-items:center;justify-content:center}.wc-ring-svg{position:absolute;inset:0;width:100%;height:100%;rotate:-90deg}.wc-ring-center{position:relative;display:flex;flex-direction:column;align-items:center}.wc-ring-8xl{width:var(--spacing-8xl);height:var(--spacing-8xl)}
.wc-bar{position:relative;height:var(--spacing-sm);overflow:hidden;border-radius:999px;background:var(--color-utility-gray-200)}.wc-bar-fill{position:absolute;inset-block:0;left:0;border-radius:999px;background:var(--color-bg-brand-solid);transition:width var(--motion-duration-spatial-move) var(--motion-easing-drawer),background-color var(--motion-duration-spatial-move) var(--motion-easing-drawer)}.wc-bar-done{background:var(--color-bg-success-solid)}
.wc-range{position:relative;flex:1;height:var(--spacing-xs);border-radius:999px;background:var(--color-utility-gray-200)}.wc-range-fill{position:absolute;inset-block:0;border-radius:999px;background-image:linear-gradient(90deg,var(--color-utility-blue-300),var(--color-utility-success-300),var(--color-utility-warning-300),var(--color-utility-orange-300))}
.wc-seg{position:relative;display:inline-grid;grid-auto-flow:column;grid-auto-columns:1fr;width:fit-content;padding:var(--spacing-xxs);border-radius:var(--radius-md);background:var(--color-bg-quaternary)}
.wc-seg-thumb{position:absolute;inset-block:var(--spacing-xxs);left:var(--spacing-xxs);width:calc((100% - 2 * var(--spacing-xxs)) / var(--wc-seg-count));translate:calc(var(--wc-seg-index) * 100%) 0;border-radius:var(--radius-sm);background:var(--color-bg-popup-secondary);box-shadow:var(--shadow-xs);transition:translate var(--motion-duration-spatial-move) var(--motion-easing-drawer)}
.wc-card .wc-seg-option{position:relative;min-height:0;padding:var(--spacing-xxs) var(--spacing-lg);border:0;border-radius:var(--radius-sm);background:transparent;color:var(--color-text-tertiary);font-size:var(--text-sm);line-height:var(--text-sm--line-height);font-weight:var(--font-weight-medium);white-space:nowrap;transition:color var(--motion-duration-state-change) var(--motion-easing-smooth-out),transform var(--motion-duration-feedback-out) var(--motion-easing-smooth-out)}
.wc-card .wc-seg-option:hover{color:var(--color-text-secondary)}.wc-card .wc-seg-option[aria-pressed=true],.wc-card .wc-seg-option:active{color:var(--color-text-primary)}
.wc-row{display:flex;gap:var(--spacing-md);min-height:0;margin-inline:calc(-1 * var(--spacing-sm));padding:var(--spacing-md) var(--spacing-sm);border-radius:var(--radius-md);text-align:start}
.wc-card a.wc-row-link{min-height:0;transition:background-color var(--motion-duration-state-change) var(--motion-easing-smooth-out),transform var(--motion-duration-feedback-out) var(--motion-easing-smooth-out)}.wc-card a.wc-row-link:hover{background:var(--color-bg-quaternary)}.wc-card a.wc-row-link:active{transform:scale(var(--motion-scale-pressed));transition-duration:var(--motion-duration-feedback-in)}
.wc-fc-hero{display:flex;align-items:center;gap:var(--spacing-xl)}.wc-fc-temp{color:var(--color-text-primary);font-size:var(--text-display-lg);line-height:var(--text-display-lg);letter-spacing:var(--text-display-lg--letter-spacing)}.wc-fc-hero-glyph{width:var(--spacing-7xl);height:var(--spacing-7xl)}
.wc-fc-strip{display:grid;grid-template-columns:repeat(5,minmax(0,1fr));gap:var(--spacing-xs)}.wc-fc-day{display:flex;flex-direction:column;align-items:center;gap:var(--spacing-xs);padding-block:var(--spacing-xs);border-radius:var(--radius-md)}.wc-fc-today{background:var(--color-bg-secondary)}
.wc-fc-week-row{display:flex;align-items:center;gap:var(--spacing-lg);padding-block:var(--spacing-md)}.wc-fc-week-row+.wc-fc-week-row{border-top:var(--border-width-default) solid var(--color-border-secondary)}.wc-fc-week-row:first-child{padding-top:0}.wc-fc-week-row:last-child{padding-bottom:0}
.wc-fc-week-label,.wc-fc-rain,.wc-fc-low,.wc-fc-high{flex:none;width:var(--spacing-4xl)}.wc-fc-rain{color:var(--color-utility-blue-700)}.wc-fc-low{text-align:end}
.wc-fc-compact-temp{color:var(--color-text-primary);font-size:var(--text-title-1);line-height:var(--text-title-1);letter-spacing:var(--text-title-1--letter-spacing)}
.wc-fc-tomorrow{display:flex;align-items:center;gap:var(--spacing-sm);padding-top:var(--spacing-md);border-top:var(--border-width-default) solid var(--color-border-secondary);font-size:var(--text-xs);line-height:var(--text-xs--line-height);color:var(--color-text-tertiary)}
.wc-opt{display:flex;flex-direction:column;gap:var(--spacing-xs);padding-block:var(--spacing-md)}.wc-opt+.wc-opt{border-top:var(--border-width-default) solid var(--color-border-secondary)}.wc-opt-pick{margin-inline:calc(-1 * var(--spacing-md));padding-inline:var(--spacing-md);border-radius:var(--radius-lg);background:var(--color-bg-secondary)}.wc-opt.wc-opt-pick,.wc-opt-pick+.wc-opt{border-top-color:transparent}
.wc-leg{display:flex;flex:1;align-items:center;gap:var(--spacing-md);min-width:0}.wc-leg-time{font-size:var(--text-title-3);line-height:var(--text-title-3--line-height);letter-spacing:var(--text-title-3--letter-spacing);font-weight:var(--font-weight-semibold);font-variant-numeric:tabular-nums}.wc-leg-arrive{font-weight:var(--font-weight-regular);color:var(--color-text-secondary)}
.wc-leg-line{display:flex;flex:1;flex-direction:column;align-items:center;gap:var(--spacing-xxs);min-width:var(--spacing-4xl)}.wc-leg-track{display:flex;align-items:center;width:100%}.wc-leg-from,.wc-leg-to{width:var(--spacing-xs);height:var(--spacing-xs);border-radius:50%}.wc-leg-from{border:var(--border-width-default) solid var(--color-fg-quaternary)}.wc-leg-to{background:var(--color-fg-quaternary)}.wc-leg-rule{flex:1;height:1px;background:var(--color-border-primary)}
.wc-price-col{display:flex;flex:none;flex-direction:column;align-items:flex-end;gap:var(--spacing-xxs);min-width:var(--spacing-6xl)}
.wc-tags{display:flex;flex-wrap:wrap;align-items:center;gap:var(--spacing-sm);font-size:var(--text-xs);line-height:var(--text-xs--line-height);color:var(--color-text-tertiary)}
.wc-opt-dense{display:flex;align-items:center;gap:var(--spacing-md);padding-block:var(--spacing-sm)}.wc-opt-dense+.wc-opt-dense{border-top:var(--border-width-default) solid var(--color-border-secondary)}.wc-opt-times{flex:none;width:var(--spacing-9xl)}.wc-opt-price{flex:none;width:var(--spacing-4xl);text-align:end}
.wc-pick{display:flex;flex-direction:column;gap:var(--spacing-md);padding:var(--spacing-lg);border-radius:var(--radius-lg);background:var(--color-bg-secondary)}
.wc-opt-alt{display:flex;align-items:center;gap:var(--spacing-lg);padding-block:var(--spacing-md)}.wc-opt-alt+.wc-opt-alt{border-top:var(--border-width-default) solid var(--color-border-secondary)}
.wc-value{color:var(--color-text-primary);font-weight:var(--font-weight-semibold)}.wc-unit{margin-inline-start:var(--spacing-xxs);color:var(--color-text-tertiary);font-size:var(--text-sm);line-height:var(--text-sm--line-height);font-weight:var(--font-weight-medium);letter-spacing:normal}
.wc-metric-single{display:flex;flex-direction:column;gap:var(--spacing-lg)}.wc-metric-spark{height:var(--spacing-5xl)}
.wc-metric-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:var(--spacing-sm)}.wc-tile{display:flex;flex-direction:column;gap:var(--spacing-xs);padding:var(--spacing-lg);border-radius:var(--radius-lg);background:var(--color-bg-secondary)}
.wc-area{display:flex;flex-direction:column;gap:var(--spacing-sm)}.wc-area-plot{position:relative;height:var(--spacing-10xl)}.wc-area-grid{position:absolute;inset:0;display:flex;flex-direction:column;justify-content:space-between}.wc-area-grid>div{border-top:var(--border-width-default) dashed var(--color-border-secondary)}
.wc-area-svg{position:absolute;inset:0;width:100%;height:100%;overflow:visible}.wc-morph{transition:d var(--motion-duration-spatial-move) var(--motion-easing-drawer)}.wc-glide{transition:top var(--motion-duration-spatial-move) var(--motion-easing-drawer)}
.wc-area-end{position:absolute;right:0;width:var(--spacing-md);height:var(--spacing-md);border-radius:50%;translate:50% -50%;background:var(--color-bg-brand-solid);box-shadow:0 0 0 2px var(--color-bg-popup-secondary)}
.wc-area-label{position:absolute;left:0;padding-inline:var(--spacing-xxs);border-radius:var(--radius-xs);background:var(--color-bg-popup-secondary);color:var(--color-text-tertiary);font-size:var(--text-micro);line-height:var(--text-micro--line-height);font-variant-numeric:tabular-nums}.wc-area-high{translate:0 -120%}.wc-area-low{translate:0 20%}
.wc-area-axis,.wc-bars-axis{display:flex;justify-content:space-between;color:var(--color-text-tertiary);font-size:var(--text-micro);line-height:var(--text-micro--line-height);font-variant-numeric:tabular-nums}
.wc-bars{display:flex;flex-direction:column;gap:var(--spacing-sm)}.wc-bars-legend{display:flex;align-items:center;gap:var(--spacing-xs);color:var(--color-text-tertiary);font-size:var(--text-micro);line-height:var(--text-micro--line-height)}.wc-bars-swatch{width:var(--spacing-lg);border-top:var(--border-width-default) dashed var(--color-fg-quaternary)}
.wc-bars-plot{position:relative;display:flex;align-items:flex-end;gap:var(--spacing-xs);height:var(--spacing-9xl)}.wc-bar-slot{position:relative;display:flex;flex:1;align-items:flex-end;height:100%}.wc-bar-col{width:100%;border-radius:var(--radius-xs) var(--radius-xs) 0 0;background:var(--color-utility-gray-300)}.wc-bar-latest{background:var(--color-bg-brand-solid)}
.wc-bars-value{position:absolute;left:50%;translate:-50% -100%;padding-bottom:var(--spacing-xxs);color:var(--color-text-primary);font-size:var(--text-micro);line-height:var(--text-micro--line-height);font-weight:var(--font-weight-medium);white-space:nowrap;font-variant-numeric:tabular-nums}
.wc-bars-average{position:absolute;inset-inline:0;border-top:var(--border-width-default) dashed var(--color-fg-quaternary);pointer-events:none}.wc-bars-axis{gap:var(--spacing-xs)}.wc-bars-axis>span{flex:1;text-align:center}
.wc-watch{display:flex;align-items:center;gap:var(--spacing-lg);padding-block:var(--spacing-md)}.wc-watch+.wc-watch{border-top:var(--border-width-default) solid var(--color-border-secondary)}.wc-watch:first-child{padding-top:0}.wc-watch:last-child{padding-bottom:0}
.wc-watch-name{display:flex;flex:none;align-items:center;gap:var(--spacing-md);width:var(--spacing-8xl)}.wc-watch-spark{flex:1;min-width:0;height:var(--spacing-2xl)}.wc-watch-value{flex:none;width:var(--spacing-7xl);text-align:end}
.wc-pill{flex:none;width:var(--spacing-6xl);padding-block:var(--spacing-xxs);border-radius:var(--radius-sm);text-align:center;font-size:var(--text-xs);line-height:var(--text-xs--line-height);font-weight:var(--font-weight-medium);font-variant-numeric:tabular-nums}.wc-pill-good{background:var(--color-utility-success-50);color:var(--color-utility-success-700)}.wc-pill-bad{background:var(--color-utility-error-50);color:var(--color-utility-error-700)}
.wc-card table{width:100%;border-collapse:collapse;text-align:start}.wc-card th,.wc-card td{padding:0;border:0;font-weight:inherit;text-align:start;overflow-wrap:normal}
.wc-cmp{table-layout:fixed}.wc-cmp-corner{width:var(--spacing-7xl)}.wc-cmp-head{padding:0 var(--spacing-sm) var(--spacing-md)!important;vertical-align:bottom}.wc-cmp tbody tr{border-top:var(--border-width-default) solid var(--color-border-secondary)}
.wc-cmp-label{padding:var(--spacing-md) var(--spacing-sm) var(--spacing-md) 0!important;color:var(--color-text-tertiary);font-size:var(--text-xs);line-height:var(--text-xs--line-height)}.wc-cmp-cell{padding:var(--spacing-md) var(--spacing-sm)!important;color:var(--color-text-secondary);font-variant-numeric:tabular-nums}.wc-cmp-best{color:var(--color-text-primary);font-weight:var(--font-weight-medium)}.wc-cmp-check{width:var(--spacing-xl);height:var(--spacing-xl);color:var(--color-text-success-primary)}
.wc-attr thead th{padding:0 var(--spacing-sm) var(--spacing-sm)!important;color:var(--color-text-tertiary);font-size:var(--text-xs);line-height:var(--text-xs--line-height);text-align:end}.wc-attr thead th:first-child{text-align:start}.wc-attr tbody tr{border-top:var(--border-width-default) solid var(--color-border-secondary)}
.wc-attr-name{padding:var(--spacing-md) var(--spacing-sm) var(--spacing-md) 0!important}.wc-attr td{padding:var(--spacing-md) var(--spacing-sm)!important;text-align:end;font-variant-numeric:tabular-nums}.wc-attr-value{padding:var(--spacing-xxs) var(--spacing-xs);border-radius:var(--radius-sm);color:var(--color-text-secondary)}.wc-attr-best{background:var(--color-utility-success-50);color:var(--color-utility-success-700);font-weight:var(--font-weight-medium)}
.wc-vs-name{display:flex;flex:1;align-items:center;gap:var(--spacing-sm);min-width:0}.wc-vs-right{justify-content:flex-end}.wc-vs-rows{display:flex;flex-direction:column;gap:var(--spacing-sm)}
.wc-vs-score{flex:none;width:var(--spacing-3xl);color:var(--color-text-secondary);font-size:var(--text-xs);line-height:var(--text-xs--line-height);font-weight:var(--font-weight-medium);font-variant-numeric:tabular-nums}.wc-vs-score-left{text-align:end}
.wc-vs-track{display:flex;flex:1;height:var(--spacing-sm);overflow:hidden;border-radius:999px;background:var(--color-bg-quaternary)}.wc-vs-end{justify-content:flex-end}.wc-vs-fill{height:100%;border-radius:999px}.wc-vs-win{background:var(--color-bg-brand-solid)}.wc-vs-lose{background:var(--color-fg-quinary)}
.wc-vs-label{flex:none;width:var(--spacing-7xl);text-align:center;color:var(--color-text-tertiary);font-size:var(--text-xs);line-height:var(--text-xs--line-height)}
.wc-agenda{display:flex;align-items:stretch;gap:var(--spacing-md);padding:var(--spacing-sm);border-radius:var(--radius-md)}.wc-agenda-now{background:var(--color-bg-secondary)}.wc-agenda-time{flex:none;width:var(--spacing-5xl);padding-top:var(--spacing-xxs);color:var(--color-text-tertiary);font-size:var(--text-xs);line-height:var(--text-xs--line-height);font-variant-numeric:tabular-nums}
.wc-agenda-bar{flex:none;width:var(--spacing-xs);border-radius:999px}.wc-agenda-done{background:var(--color-utility-gray-300)}
.wc-now{display:flex;align-items:center;gap:var(--spacing-md);padding:var(--spacing-xxs) var(--spacing-sm)}.wc-now-time{flex:none;width:var(--spacing-5xl);color:var(--color-text-error-primary);font-size:var(--text-micro);line-height:var(--text-micro--line-height);font-weight:var(--font-weight-medium);font-variant-numeric:tabular-nums}.wc-now-dot{flex:none;width:var(--spacing-sm);height:var(--spacing-sm);border-radius:50%;background:var(--color-fg-error-primary)}.wc-now-line{flex:1;height:1px;background:var(--color-fg-error-primary)}
.wc-step{display:flex;gap:var(--spacing-md)}.wc-step-time{flex:none;width:var(--spacing-5xl);padding-top:var(--spacing-xxs);text-align:end;color:var(--color-text-tertiary);font-size:var(--text-xs);line-height:var(--text-xs--line-height);font-variant-numeric:tabular-nums}.wc-step-time-now{color:var(--color-text-primary);font-weight:var(--font-weight-medium)}
.wc-step-rail{display:flex;flex:none;flex-direction:column;align-items:center;width:var(--spacing-md)}.wc-step-dot{flex:none;width:var(--spacing-md);height:var(--spacing-md);margin-top:var(--spacing-sm);border-radius:50%}.wc-step-done{background:var(--color-fg-quaternary)}.wc-step-current{background:var(--color-bg-brand-solid);box-shadow:0 0 0 4px color-mix(in oklch,var(--color-bg-brand-solid) 24%,transparent)}.wc-step-upcoming{border:var(--border-width-default) solid var(--color-fg-quaternary);background:var(--color-bg-popup-secondary)}
.wc-step-line{flex:1;width:1px;margin-top:var(--spacing-xs);background:var(--color-border-primary)}.wc-step-line-done{background:var(--color-fg-quaternary)}
.wc-stages{display:flex;align-items:flex-start}.wc-stage{display:flex;flex:1;flex-direction:column;align-items:center;gap:var(--spacing-sm);min-width:0;text-align:center}.wc-stage-track{display:flex;align-items:center;width:100%}.wc-stage-line{flex:1;height:var(--spacing-xxs);background:var(--color-utility-gray-200)}.wc-stage-line-on{background:var(--color-bg-brand-solid)}
.wc-stage-mark{display:flex;flex:none;align-items:center;justify-content:center;width:var(--spacing-2xl);height:var(--spacing-2xl);border-radius:50%}.wc-stage-done{background:var(--color-bg-brand-solid);color:var(--color-fg-white)}.wc-stage-done .wc-icon{width:var(--spacing-lg);height:var(--spacing-lg)}.wc-stage-current{background:var(--color-bg-popup-secondary);box-shadow:inset 0 0 0 2px var(--color-bg-brand-solid)}.wc-stage-core{width:var(--spacing-md);height:var(--spacing-md);border-radius:50%;background:var(--color-bg-brand-solid)}.wc-stage-upcoming{border:var(--border-width-default) solid var(--color-fg-quinary);background:var(--color-bg-popup-secondary)}
.wc-stage-detail{margin-top:calc(-1 * var(--spacing-xs));max-width:100%;overflow:hidden;text-overflow:ellipsis;white-space:nowrap;color:var(--color-text-tertiary);font-size:var(--text-micro);line-height:var(--text-micro--line-height)}
.wc-check{position:relative;display:flex;align-items:flex-start;gap:var(--spacing-md);padding-block:var(--spacing-sm);cursor:pointer;transition:transform var(--motion-duration-feedback-out) var(--motion-easing-smooth-out)}.wc-check:active{transform:scale(var(--motion-scale-pressed));transition-duration:var(--motion-duration-feedback-in)}
.wc-card .wc-check-input{position:absolute;width:1px;height:1px;min-width:0;min-height:0;margin:0;opacity:0}
.wc-check-box{display:inline-flex;flex:none;align-items:center;justify-content:center;width:var(--spacing-xl);height:var(--spacing-xl);margin-top:var(--spacing-xxs);border:var(--border-width-default) solid var(--color-border-menu-primary);border-radius:var(--radius-xs);background:var(--color-main-panel-bg);box-shadow:var(--shadow-xs);color:var(--color-fg-white)}.wc-check-box .wc-icon{width:var(--spacing-lg);height:var(--spacing-lg);opacity:0}.wc-check-box [data-comma-icon] :where([stroke-width="2"]){stroke-width:3.33}
.wc-check-input:checked+.wc-check-box{border-color:transparent;background:var(--color-bg-brand-solid)}.wc-check-input:checked+.wc-check-box .wc-icon{opacity:1}.wc-check-input:focus-visible+.wc-check-box{outline:2px solid var(--color-bg-brand-solid);outline-offset:2px}
.wc-check-label{color:var(--color-text-primary);font-size:var(--text-sm);line-height:var(--text-sm--line-height)}.wc-check-input:checked~.wc-col .wc-check-label{color:var(--color-text-tertiary);text-decoration:line-through}
.wc-check-groups{display:grid;grid-template-columns:minmax(0,1fr);gap:var(--spacing-sm)}.wc-check-group{display:flex;flex-direction:column;padding:var(--spacing-sm) var(--spacing-md);border-radius:var(--radius-lg);background:var(--color-bg-secondary)}.wc-check-group-head{display:flex;align-items:center;justify-content:space-between;padding-bottom:var(--spacing-xxs)}
.wc-legend{display:grid;grid-template-columns:minmax(0,1fr);gap:var(--spacing-sm) var(--spacing-xl)}.wc-swatch{flex:none;width:var(--spacing-sm);height:var(--spacing-sm);border-radius:50%}.wc-legend-share{flex:none;width:var(--spacing-4xl);text-align:end;color:var(--color-text-tertiary);font-size:var(--text-xs);line-height:var(--text-xs--line-height);font-variant-numeric:tabular-nums}
.wc-stack{display:flex;gap:var(--spacing-xxs);height:var(--spacing-md);overflow:hidden;border-radius:999px}.wc-stack-part{min-width:var(--spacing-xxs);height:100%}.wc-stack-part:first-child{border-radius:999px 0 0 999px}.wc-stack-part:last-child{border-radius:0 999px 999px 0}
.wc-donut-row{display:flex;flex-direction:column;gap:var(--spacing-xl)}.wc-donut{position:relative;flex:none;align-self:center;width:var(--spacing-10xl);height:var(--spacing-10xl)}.wc-donut-svg{width:100%;height:100%;rotate:-90deg}.wc-donut-center{position:absolute;inset:0;display:flex;flex-direction:column;align-items:center;justify-content:center}
.wc-chip{padding:var(--spacing-xxs) var(--spacing-sm);border-radius:var(--radius-md);background:var(--color-bg-quaternary);color:var(--color-text-secondary);font-size:var(--text-xs);line-height:var(--text-xs--line-height);font-variant-numeric:tabular-nums}
.wc-place{align-items:center}.wc-place-index{display:inline-flex;flex:none;align-items:center;justify-content:center;width:var(--spacing-2xl);height:var(--spacing-2xl);border-radius:50%;background:var(--color-bg-quaternary);color:var(--color-text-secondary);font-size:var(--text-xs);line-height:var(--text-xs--line-height);font-weight:var(--font-weight-medium);font-variant-numeric:tabular-nums}.wc-chevron{width:var(--spacing-xl);height:var(--spacing-xl);color:var(--color-fg-quaternary)}
.wc-news{align-items:flex-start}
.wc-digest{display:flex;align-items:flex-start;gap:var(--spacing-md);padding:var(--spacing-md);border-radius:var(--radius-lg);background:var(--color-bg-secondary)}
.wc-dial{position:relative;flex:none;width:var(--spacing-11xl);height:var(--spacing-11xl)}.wc-dial-svg{position:absolute;inset:0;width:100%;height:100%}.wc-timer-arc{transition:opacity var(--motion-duration-state-change) var(--motion-easing-smooth-out)}
.wc-orbit{position:absolute;inset:18.125%;border-radius:50%;animation:wc-orbit 60s linear infinite}.wc-orbit::before{content:"";position:absolute;inset:0;border-radius:50%;background:conic-gradient(from 0turn,transparent 0turn 0.7turn,color-mix(in oklch,var(--wc-accent) 60%,transparent) 1turn);mask:radial-gradient(farthest-side,transparent calc(100% - var(--spacing-xxs)),#000 calc(100% - var(--spacing-xxs)))}
.wc-orbit-dot{position:absolute;left:50%;top:0;width:var(--spacing-sm);height:var(--spacing-sm);border-radius:50%;translate:-50% -50%;background:var(--wc-accent)}
.wc-dial-face{position:absolute;inset:0;display:flex;flex-direction:column;align-items:center;justify-content:center}.wc-dial-time{color:var(--color-text-primary);font-size:var(--text-display-sm);line-height:var(--text-display-sm--line-height);font-weight:var(--font-weight-semibold)}
.wc-digits{display:flex;font-variant-numeric:tabular-nums}.wc-digit-slot{display:inline-block;overflow:hidden}.wc-digit-slot>span{display:inline-block}.wc-digit-roll{animation:wc-digit var(--motion-duration-icon-swap) var(--motion-easing-smooth-out) backwards}
.wc-dial-check{width:var(--spacing-4xl);height:var(--spacing-4xl);color:var(--color-text-success-primary)}.wc-dial-complete{animation:wc-complete var(--motion-duration-dialog-enter) var(--motion-easing-smooth-out)}
.wc-timer-chip{display:inline-flex;align-items:center;gap:var(--spacing-xs);font-size:var(--text-xs);line-height:var(--text-xs--line-height);font-weight:var(--font-weight-medium)}
.wc-cycle{width:var(--spacing-sm);height:var(--spacing-sm);border-radius:50%;background:var(--color-bg-quaternary)}.wc-cycle-done{background:var(--wc-accent)}.wc-cycle-now{background:transparent;box-shadow:inset 0 0 0 var(--spacing-xxs) var(--wc-accent)}
@keyframes wc-fade{from{opacity:0}}@keyframes wc-orbit{to{rotate:1turn}}@keyframes wc-digit{from{opacity:0;translate:0 .5em}}@keyframes wc-complete{from{scale:.94}}
@container (min-width:480px){.wc-fc-strip{grid-template-columns:repeat(7,minmax(0,1fr))}.wc-metric-single{flex-direction:row;align-items:flex-end;justify-content:space-between}.wc-metric-spark{width:50%}.wc-metric-grid{grid-template-columns:repeat(4,minmax(0,1fr))}.wc-check-groups,.wc-legend-two{grid-template-columns:repeat(2,minmax(0,1fr))}.wc-donut-row{flex-direction:row;align-items:center}}
@container (max-width:479px){.wc-attr thead{position:absolute;width:1px;height:1px;overflow:hidden;clip-path:inset(50%)}.wc-attr,.wc-attr tbody{display:block}.wc-attr tbody{display:flex;flex-direction:column;gap:var(--spacing-sm)}.wc-attr tr{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:var(--spacing-xs) var(--spacing-lg);padding:var(--spacing-md);border:0!important;border-radius:var(--radius-lg);background:var(--color-bg-secondary)}.wc-attr-name{grid-column:1/-1;padding:0!important}.wc-attr td{display:flex;align-items:center;justify-content:space-between;gap:var(--spacing-sm);padding:0!important}.wc-attr td::before{content:attr(data-label);color:var(--color-text-tertiary);font-size:var(--text-xs);line-height:var(--text-xs--line-height)}}
@media (prefers-reduced-motion:reduce){.wc-orbit{display:none}.wc-digit-roll,.wc-dial-complete,.wc-arrive{animation:none}.wc-seg-thumb,.wc-morph,.wc-glide,.wc-bar-fill,.wc-card .wc-seg-option,.wc-card a.wc-row-link,.wc-check{transition:none}.wc-card a.wc-row-link:active,.wc-check:active,.wc-card a.wc-action:active{transform:none}}
@media (prefers-contrast:more){.wc-card{border-width:var(--border-width-default);--color-border-primary:var(--color-fg-quaternary);--color-border-secondary:var(--color-fg-quinary)}}
`;
