/**
 * Generates Tailwind v4 theme variables and semantic utilities from the
 * TypeScript token source of truth.
 */
import { mkdirSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { borderWidth } from "../src/tokens/borders";
import {
  components,
  componentsDark,
  grayDarkMode,
  grayLightMode,
  hexToOklch,
  commaThemeLightnessNeutral,
  oklchChromaGainFromSample,
  oklchNeutralCss,
  palettes,
  semantic,
  semanticDark,
} from "../src/tokens/colors";
import {
  backdropBlur,
  focusRing,
  focusRingDark,
  opacity,
  shadow,
  shadowDark,
  zIndex,
} from "../src/tokens/effects";
import {
  dialogLayout,
  meetingRecorderLayout,
  taskWorkspaceLayout,
  toastLayout,
} from "../src/tokens/layout";
import { iconStrokeWidth } from "../src/tokens/icons";
import {
  motionBlur,
  motionDistance,
  motionDuration,
  motionEasing,
  motionLoginCodeError,
  motionRotate,
  motionScale,
} from "../src/tokens/motion";
import { radius } from "../src/tokens/radius";
import { container, spacing, width } from "../src/tokens/spacing";
import {
  fontFamily,
  fontWeight,
  compactTypeScale,
  typeScale,
} from "../src/tokens/typography";
import { kebab } from "../src/tokens/naming";

type TokenMap = Record<string, string | number>;
type TokenGroup = Record<string, TokenMap>;

const normalizeHex = (hex: string) => hex.trim().toLowerCase();

const neutralHexes = new Set<string>(
  [...Object.values(grayLightMode), ...Object.values(grayDarkMode)].map(normalizeHex)
);

const commaThemeHKey = "comma-theme-h";
const commaThemeCKey = "comma-theme-c";
const commaThemeLKey = "comma-theme-l";

const surfaceBackgroundTokens = new Set([
  "primary",
  "popupPrimary",
  "popupSecondary",
  "window",
]);

const oklchNeutral = (hex: string) => oklchNeutralCss(hex);

const maybeRetintNeutralHex = (hex: string | number) =>
  typeof hex === "string" && neutralHexes.has(normalizeHex(hex))
    ? oklchNeutral(hex)
    : hex;

const emitSemanticColorValue = (group: string, token: string, hex: string | number) => {
  if (
    typeof hex === "string" &&
    group === "background" &&
    surfaceBackgroundTokens.has(token)
  ) {
    return oklchNeutral(hex);
  }
  return maybeRetintNeutralHex(hex);
};

const lines: string[] = [
  "/* Generated by scripts/generate-css.ts. Do not edit by hand. */",
  "",
];

const emit = (name: string, value: string | number, unit = "") => {
  lines.push(`  --${name}: ${value}${unit};`);
};

const emitTheme = (name: string, value: string | number, unit = "") => {
  lines.push(`  --${name}: ${value}${unit};`);
};

const pxToRem = (value: number) => {
  const rem = Number((value / 16).toFixed(4));
  return `${rem}rem`;
};

const emitUtility = (name: string, declarations: Record<string, string>) => {
  lines.push(`@utility ${name} {`);
  for (const [property, value] of Object.entries(declarations)) {
    lines.push(`  ${property}: ${value};`);
  }
  lines.push("}", "");
};

const emitSemanticColorVars = (
  semanticTokens: TokenGroup,
  componentTokens: TokenGroup
) => {
  for (const [group, entries] of Object.entries(semanticTokens)) {
    const groupName =
      group === "foreground" ? "fg" : group === "background" ? "bg" : group;
    for (const [token, hex] of Object.entries(entries)) {
      emit(
        `color-${groupName}-${kebab(token)}`,
        emitSemanticColorValue(group, token, hex)
      );
    }
  }

  for (const [component, entries] of Object.entries(componentTokens)) {
    for (const [token, hex] of Object.entries(entries)) {
      emit(`color-${kebab(component)}-${kebab(token)}`, maybeRetintNeutralHex(hex));
    }
  }
};

const emitSemanticUtilities = () => {
  for (const token of Object.keys(semantic.text)) {
    emitUtility(`text-${kebab(token)}`, {
      color: `var(--color-text-${kebab(token)})`,
    });
  }

  for (const token of Object.keys(semantic.background)) {
    emitUtility(`bg-${kebab(token)}`, {
      "background-color": `var(--color-bg-${kebab(token)})`,
    });
  }

  for (const token of Object.keys(semantic.border)) {
    const name = kebab(token);
    emitUtility(`border-${name}`, {
      "border-color": `var(--color-border-${name})`,
    });
    emitUtility(`ring-${name}`, {
      "--tw-ring-color": `var(--color-border-${name})`,
    });
  }

  emitUtility("bg-overlay-scrim", {
    "background-color": "color-mix(in srgb, var(--color-bg-overlay) 60%, transparent)",
  });
};

const emitLayoutUtilities = () => {
  emitUtility("w-toast-single", {
    width: "min(var(--toast-width-single), calc(100vw - var(--spacing-xl) * 2))",
  });
  emitUtility("w-toast-action", {
    width: "min(var(--toast-width-action), calc(100vw - var(--spacing-xl) * 2))",
  });
  emitUtility("w-toast-actions-row", {
    width: "min(var(--toast-width-actions-row), 100%)",
  });
  emitUtility("w-dialog-default", {
    width: "min(var(--dialog-width-default), calc(100vw - var(--spacing-xl) * 2))",
  });
  emitUtility("w-meeting-recorder", {
    width: "min(var(--meeting-recorder-width), calc(100vw - var(--spacing-xl) * 2))",
  });
  emitUtility("w-dialog-wide", {
    width: "min(var(--dialog-width-wide), calc(100vw - var(--spacing-xl) * 2))",
  });
  emitUtility("w-dialog-preview", {
    width: "min(var(--dialog-width-preview), calc(100vw - var(--spacing-xl) * 2))",
  });
  emitUtility("inset-toast-close-icon", { inset: "var(--toast-close-icon-inset)" });
  emitUtility("inset-dialog-close-icon", { inset: "var(--dialog-close-icon-inset)" });
};

lines.push("@theme static {");

for (const [family, steps] of Object.entries(palettes)) {
  for (const [step, hex] of Object.entries(steps)) {
    emitTheme(
      `color-${kebab(family)}-${kebab(step)}`,
      typeof hex === "string" ? maybeRetintNeutralHex(hex) : hex
    );
  }
}

emitSemanticColorVars(semantic, components);

for (const [key, value] of Object.entries(spacing))
  emitTheme(`spacing-${key}`, value, "px");
for (const [key, value] of Object.entries(width))
  emitTheme(`container-${key}`, value, "px");
for (const [key, value] of Object.entries(container)) {
  emitTheme(kebab(`container-layout-${key}`), value, "px");
}
for (const [key, value] of Object.entries(radius))
  emitTheme(`radius-${key}`, value, "px");
for (const [key, value] of Object.entries(shadow)) emitTheme(`shadow-${key}`, value);
for (const [key, value] of Object.entries(focusRing)) {
  emitTheme(`shadow-focus-${kebab(key)}`, value);
}
for (const [key, value] of Object.entries(backdropBlur))
  emitTheme(`blur-${key}`, value, "px");
for (const [key, value] of Object.entries(opacity))
  emitTheme(`opacity-${kebab(key)}`, value);
for (const [key, value] of Object.entries(zIndex))
  emitTheme(`z-index-${kebab(key)}`, value);
// Tailwind's `font-normal` utility reads this built-in theme key. Keep it
// aliased to Comma's Regular token so Preflight/utilities cannot reintroduce 400.
emitTheme("font-weight-normal", fontWeight.regular);
for (const [key, value] of Object.entries(fontWeight))
  emitTheme(`font-weight-${key}`, value);

for (const [key, value] of Object.entries(fontFamily)) {
  emitTheme(`font-${kebab(key)}`, value);
}

for (const [key, style] of Object.entries(typeScale)) {
  const name = kebab(key).replace(/^text-/, "");
  emitTheme(`text-${name}`, pxToRem(style.fontSize));
  emitTheme(`text-${name}--line-height`, pxToRem(style.lineHeight));
  emitTheme(`text-${name}--letter-spacing`, style.letterSpacing);
}

for (const [key, style] of Object.entries(compactTypeScale)) {
  const name = kebab(key).replace(/^text-/, "");
  emitTheme(`text-${name}`, pxToRem(style.fontSize));
  emitTheme(`text-${name}--line-height`, pxToRem(style.lineHeight));
  emitTheme(`text-${name}--letter-spacing`, style.letterSpacing);
}

lines.push("}", "");

lines.push(":root {");
emit("comma-icon-stroke-width", iconStrokeWidth);

// Seed hue, peak chroma gain, and identity lightness. Token C/L' use the
// 4L(1−L) envelope in oklchNeutralCss.
const lightRef = grayLightMode[500] ?? grayLightMode[900];

const { c: lightC, h: lightH, l: lightL } = hexToOklch(lightRef);
const signalHue = hexToOklch("#0c55ff").h;
// If chroma is effectively 0, the hue is meaningless; keep Comma Signal as the stable angle.
const safeLightH = lightC < 1e-7 ? signalHue : lightH;
const safeLightC = oklchChromaGainFromSample(lightC, lightL);

emit(commaThemeHKey, safeLightH, "deg");
emit(commaThemeCKey, safeLightC);
emit(commaThemeLKey, commaThemeLightnessNeutral);

for (const [key, value] of Object.entries(motionDuration)) {
  emit(`motion-duration-${kebab(key)}`, value, "ms");
}
for (const [key, value] of Object.entries(motionEasing)) {
  emit(`motion-easing-${kebab(key)}`, value);
}
for (const [key, value] of Object.entries(motionScale)) {
  emit(`motion-scale-${kebab(key)}`, value);
}
for (const [key, value] of Object.entries(motionDistance)) {
  emit(`motion-distance-${kebab(key)}`, value, "px");
}
for (const [key, value] of Object.entries(motionBlur)) {
  emit(`motion-blur-${kebab(key)}`, value, "px");
}
for (const [key, value] of Object.entries(motionRotate)) {
  emit(`motion-rotate-${kebab(key)}`, value, "deg");
}
emit("motion-login-code-error-amplitude", motionLoginCodeError.amplitude, "px");
lines.push("}", "");

lines.push(":root,");
lines.push('[data-theme="Light mode"] {');
for (const [key, value] of Object.entries(borderWidth)) {
  emit(`border-width-${kebab(key)}`, value, "px");
}
for (const [key, value] of Object.entries(toastLayout)) {
  emit(`toast-${kebab(key)}`, value, key === "closeIconInset" ? "%" : "px");
}
for (const [key, value] of Object.entries(dialogLayout)) {
  emit(`dialog-${kebab(key)}`, value, key === "closeIconInset" ? "%" : "px");
}
for (const [key, value] of Object.entries(taskWorkspaceLayout)) {
  emit(`task-workspace-${kebab(key)}`, value, "px");
}
for (const [key, value] of Object.entries(meetingRecorderLayout)) {
  emit(`meeting-recorder-${kebab(key)}`, value, "px");
}
lines.push("}", "");

// Nested `[data-theme="Light mode"]` islands (theme swatches) must re-apply
// light colors; `:root` / `@theme` values are inherited from a dark document.
lines.push('[data-theme="Light mode"] {');
emitSemanticColorVars(semantic, components);
for (const [key, value] of Object.entries(shadow)) emit(`shadow-${key}`, value);
for (const [key, value] of Object.entries(focusRing)) {
  emit(`shadow-focus-${kebab(key)}`, value);
}
lines.push("}", "");

lines.push(".dark,");
lines.push('[data-theme="Dark mode"] {');
emitSemanticColorVars(semanticDark, componentsDark);
for (const [key, value] of Object.entries(shadowDark)) emit(`shadow-${key}`, value);
for (const [key, value] of Object.entries(focusRingDark)) {
  emit(`shadow-focus-${kebab(key)}`, value);
}
lines.push("}", "");

emitSemanticUtilities();
emitLayoutUtilities();

const outFile = resolve(
  dirname(fileURLToPath(import.meta.url)),
  "../src/styles/theme.css"
);

mkdirSync(dirname(outFile), { recursive: true });
writeFileSync(outFile, `${lines.join("\n").trimEnd()}\n`);
console.log(`Wrote ${outFile}`);
