// Generated by @comma/native-bridge/scripts/generate-native-partner-contracts.mjs.
// Do not edit by hand. Change the native partner leaf registry or its Zod schemas.

import Foundation

private enum CommaNativeContractValidation {
    static func decodeOptional<Value: Decodable, Key: CodingKey>(
        _ type: Value.Type,
        from container: KeyedDecodingContainer<Key>,
        forKey key: Key
    ) throws -> Value? {
        guard container.contains(key) else { return nil }
        if try container.decodeNil(forKey: key) {
            throw DecodingError.valueNotFound(
                type,
                DecodingError.Context(
                    codingPath: container.codingPath + [key],
                    debugDescription: "Explicit null is not allowed for optional field \(key.stringValue)."
                )
            )
        }
        return try container.decode(type, forKey: key)
    }

    static func decodeString<Key: CodingKey>(
        _ type: String.Type,
        from container: KeyedDecodingContainer<Key>,
        forKey key: Key,
        minimumLength: Int?,
        maximumLength: Int?
    ) throws -> String {
        let value = try container.decode(type, forKey: key)
        try validateDecodedString(
            value,
            minimumLength: minimumLength,
            maximumLength: maximumLength,
            forKey: key,
            in: container
        )
        return value
    }

    static func decodeOptionalString<Key: CodingKey>(
        _ type: String.Type,
        from container: KeyedDecodingContainer<Key>,
        forKey key: Key,
        minimumLength: Int?,
        maximumLength: Int?
    ) throws -> String? {
        guard let value = try decodeOptional(type, from: container, forKey: key) else {
            return nil
        }
        try validateDecodedString(
            value,
            minimumLength: minimumLength,
            maximumLength: maximumLength,
            forKey: key,
            in: container
        )
        return value
    }

    static func decodeInteger<Key: CodingKey>(
        _ type: Int.Type,
        from container: KeyedDecodingContainer<Key>,
        forKey key: Key,
        minimum: Int?,
        maximum: Int?
    ) throws -> Int {
        let value = try container.decode(type, forKey: key)
        try validateDecodedInteger(
            value,
            minimum: minimum,
            maximum: maximum,
            forKey: key,
            in: container
        )
        return value
    }

    static func decodeOptionalInteger<Key: CodingKey>(
        _ type: Int.Type,
        from container: KeyedDecodingContainer<Key>,
        forKey key: Key,
        minimum: Int?,
        maximum: Int?
    ) throws -> Int? {
        guard let value = try decodeOptional(type, from: container, forKey: key) else {
            return nil
        }
        try validateDecodedInteger(
            value,
            minimum: minimum,
            maximum: maximum,
            forKey: key,
            in: container
        )
        return value
    }

    static func decodeNumber<Key: CodingKey>(
        _ type: Double.Type,
        from container: KeyedDecodingContainer<Key>,
        forKey key: Key,
        minimum: Double?,
        maximum: Double?
    ) throws -> Double {
        let value = try container.decode(type, forKey: key)
        try validateDecodedNumber(
            value,
            minimum: minimum,
            maximum: maximum,
            forKey: key,
            in: container
        )
        return value
    }

    static func decodeOptionalNumber<Key: CodingKey>(
        _ type: Double.Type,
        from container: KeyedDecodingContainer<Key>,
        forKey key: Key,
        minimum: Double?,
        maximum: Double?
    ) throws -> Double? {
        guard let value = try decodeOptional(type, from: container, forKey: key) else {
            return nil
        }
        try validateDecodedNumber(
            value,
            minimum: minimum,
            maximum: maximum,
            forKey: key,
            in: container
        )
        return value
    }

    static func decodeArray<Element: Decodable, Key: CodingKey>(
        _ type: [Element].Type,
        from container: KeyedDecodingContainer<Key>,
        forKey key: Key,
        minimumItems: Int?,
        maximumItems: Int?
    ) throws -> [Element] {
        let value = try container.decode(type, forKey: key)
        try validateDecodedArray(
            value,
            minimumItems: minimumItems,
            maximumItems: maximumItems,
            forKey: key,
            in: container
        )
        return value
    }

    static func decodeOptionalArray<Element: Decodable, Key: CodingKey>(
        _ type: [Element].Type,
        from container: KeyedDecodingContainer<Key>,
        forKey key: Key,
        minimumItems: Int?,
        maximumItems: Int?
    ) throws -> [Element]? {
        guard let value = try decodeOptional(type, from: container, forKey: key) else {
            return nil
        }
        try validateDecodedArray(
            value,
            minimumItems: minimumItems,
            maximumItems: maximumItems,
            forKey: key,
            in: container
        )
        return value
    }

    static func validateStringForEncoding(
        _ value: String,
        minimumLength: Int?,
        maximumLength: Int?,
        codingPath: [CodingKey]
    ) throws {
        let length = value.unicodeScalars.count
        if let minimumLength = minimumLength, length < minimumLength {
            throw EncodingError.invalidValue(
                value,
                EncodingError.Context(
                    codingPath: codingPath,
                    debugDescription: "String length \(length) is below minimum \(minimumLength)."
                )
            )
        }
        if let maximumLength = maximumLength, length > maximumLength {
            throw EncodingError.invalidValue(
                value,
                EncodingError.Context(
                    codingPath: codingPath,
                    debugDescription: "String length \(length) exceeds maximum \(maximumLength)."
                )
            )
        }
    }

    static func validateIntegerForEncoding(
        _ value: Int,
        minimum: Int?,
        maximum: Int?,
        codingPath: [CodingKey]
    ) throws {
        try validateNumberForEncoding(
            value,
            minimum: minimum,
            maximum: maximum,
            codingPath: codingPath
        )
    }

    static func validateNumberForEncoding<Value: Comparable>(
        _ value: Value,
        minimum: Value?,
        maximum: Value?,
        codingPath: [CodingKey]
    ) throws {
        if let minimum = minimum, value < minimum {
            throw EncodingError.invalidValue(
                value,
                EncodingError.Context(
                    codingPath: codingPath,
                    debugDescription: "Numeric value is below the schema minimum."
                )
            )
        }
        if let maximum = maximum, value > maximum {
            throw EncodingError.invalidValue(
                value,
                EncodingError.Context(
                    codingPath: codingPath,
                    debugDescription: "Numeric value exceeds the schema maximum."
                )
            )
        }
    }

    static func validateArrayForEncoding<Element>(
        _ value: [Element],
        minimumItems: Int?,
        maximumItems: Int?,
        codingPath: [CodingKey]
    ) throws {
        if let minimumItems = minimumItems, value.count < minimumItems {
            throw EncodingError.invalidValue(
                value,
                EncodingError.Context(
                    codingPath: codingPath,
                    debugDescription: "Array count \(value.count) is below minimum \(minimumItems)."
                )
            )
        }
        if let maximumItems = maximumItems, value.count > maximumItems {
            throw EncodingError.invalidValue(
                value,
                EncodingError.Context(
                    codingPath: codingPath,
                    debugDescription: "Array count \(value.count) exceeds maximum \(maximumItems)."
                )
            )
        }
    }

    private static func validateDecodedString<Key: CodingKey>(
        _ value: String,
        minimumLength: Int?,
        maximumLength: Int?,
        forKey key: Key,
        in container: KeyedDecodingContainer<Key>
    ) throws {
        let length = value.unicodeScalars.count
        if let minimumLength = minimumLength, length < minimumLength {
            throw DecodingError.dataCorruptedError(
                forKey: key,
                in: container,
                debugDescription: "String length \(length) is below minimum \(minimumLength)."
            )
        }
        if let maximumLength = maximumLength, length > maximumLength {
            throw DecodingError.dataCorruptedError(
                forKey: key,
                in: container,
                debugDescription: "String length \(length) exceeds maximum \(maximumLength)."
            )
        }
    }

    private static func validateDecodedArray<Element, Key: CodingKey>(
        _ value: [Element],
        minimumItems: Int?,
        maximumItems: Int?,
        forKey key: Key,
        in container: KeyedDecodingContainer<Key>
    ) throws {
        if let minimumItems = minimumItems, value.count < minimumItems {
            throw DecodingError.dataCorruptedError(
                forKey: key,
                in: container,
                debugDescription: "Array count \(value.count) is below minimum \(minimumItems)."
            )
        }
        if let maximumItems = maximumItems, value.count > maximumItems {
            throw DecodingError.dataCorruptedError(
                forKey: key,
                in: container,
                debugDescription: "Array count \(value.count) exceeds maximum \(maximumItems)."
            )
        }
    }

    private static func validateDecodedInteger<Key: CodingKey>(
        _ value: Int,
        minimum: Int?,
        maximum: Int?,
        forKey key: Key,
        in container: KeyedDecodingContainer<Key>
    ) throws {
        try validateDecodedNumber(
            value,
            minimum: minimum,
            maximum: maximum,
            forKey: key,
            in: container
        )
    }

    private static func validateDecodedNumber<Value: Comparable, Key: CodingKey>(
        _ value: Value,
        minimum: Value?,
        maximum: Value?,
        forKey key: Key,
        in container: KeyedDecodingContainer<Key>
    ) throws {
        if let minimum = minimum, value < minimum {
            throw DecodingError.dataCorruptedError(
                forKey: key,
                in: container,
                debugDescription: "Numeric value is below the schema minimum."
            )
        }
        if let maximum = maximum, value > maximum {
            throw DecodingError.dataCorruptedError(
                forKey: key,
                in: container,
                debugDescription: "Numeric value exceeds the schema maximum."
            )
        }
    }
}

public struct CommaNotchScenePayload: Codable, Equatable, Sendable {
    public let airDrop: CommaNotchScenePayloadAirDrop?
    public let compactSideWidth: Int?
    public let detail: String?
    public let hasActivity: Bool?
    public let listSubtitle: String?
    public let listTitle: String?
    public let notify: Bool?
    public let openChatLabel: String?
    public let subtitle: String?
    public let tasks: [CommaNotchScenePayloadTask]?
    public let title: String?

    public init(
        airDrop: CommaNotchScenePayloadAirDrop? = nil,
        compactSideWidth: Int? = nil,
        detail: String? = nil,
        hasActivity: Bool? = nil,
        listSubtitle: String? = nil,
        listTitle: String? = nil,
        notify: Bool? = nil,
        openChatLabel: String? = nil,
        subtitle: String? = nil,
        tasks: [CommaNotchScenePayloadTask]? = nil,
        title: String? = nil
    ) {
        self.airDrop = airDrop
        self.compactSideWidth = compactSideWidth
        self.detail = detail
        self.hasActivity = hasActivity
        self.listSubtitle = listSubtitle
        self.listTitle = listTitle
        self.notify = notify
        self.openChatLabel = openChatLabel
        self.subtitle = subtitle
        self.tasks = tasks
        self.title = title
    }

    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        self.airDrop = try CommaNativeContractValidation.decodeOptional(CommaNotchScenePayloadAirDrop.self, from: container, forKey: .airDrop)
        self.compactSideWidth = try CommaNativeContractValidation.decodeOptionalInteger(Int.self, from: container, forKey: .compactSideWidth, minimum: 32, maximum: 240)
        self.detail = try CommaNativeContractValidation.decodeOptional(String.self, from: container, forKey: .detail)
        self.hasActivity = try CommaNativeContractValidation.decodeOptional(Bool.self, from: container, forKey: .hasActivity)
        self.listSubtitle = try CommaNativeContractValidation.decodeOptionalString(String.self, from: container, forKey: .listSubtitle, minimumLength: nil, maximumLength: 2048)
        self.listTitle = try CommaNativeContractValidation.decodeOptionalString(String.self, from: container, forKey: .listTitle, minimumLength: nil, maximumLength: 256)
        self.notify = try CommaNativeContractValidation.decodeOptional(Bool.self, from: container, forKey: .notify)
        self.openChatLabel = try CommaNativeContractValidation.decodeOptionalString(String.self, from: container, forKey: .openChatLabel, minimumLength: nil, maximumLength: 128)
        self.subtitle = try CommaNativeContractValidation.decodeOptional(String.self, from: container, forKey: .subtitle)
        self.tasks = try CommaNativeContractValidation.decodeOptionalArray([CommaNotchScenePayloadTask].self, from: container, forKey: .tasks, minimumItems: nil, maximumItems: 100)
        self.title = try CommaNativeContractValidation.decodeOptional(String.self, from: container, forKey: .title)
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(self.airDrop, forKey: .airDrop)
        if let value = compactSideWidth {
            try CommaNativeContractValidation.validateIntegerForEncoding(value, minimum: 32, maximum: 240, codingPath: container.codingPath + [CodingKeys.compactSideWidth])
        }
        try container.encodeIfPresent(self.compactSideWidth, forKey: .compactSideWidth)
        try container.encodeIfPresent(self.detail, forKey: .detail)
        try container.encodeIfPresent(self.hasActivity, forKey: .hasActivity)
        if let value = listSubtitle {
            try CommaNativeContractValidation.validateStringForEncoding(value, minimumLength: nil, maximumLength: 2048, codingPath: container.codingPath + [CodingKeys.listSubtitle])
        }
        try container.encodeIfPresent(self.listSubtitle, forKey: .listSubtitle)
        if let value = listTitle {
            try CommaNativeContractValidation.validateStringForEncoding(value, minimumLength: nil, maximumLength: 256, codingPath: container.codingPath + [CodingKeys.listTitle])
        }
        try container.encodeIfPresent(self.listTitle, forKey: .listTitle)
        try container.encodeIfPresent(self.notify, forKey: .notify)
        if let value = openChatLabel {
            try CommaNativeContractValidation.validateStringForEncoding(value, minimumLength: nil, maximumLength: 128, codingPath: container.codingPath + [CodingKeys.openChatLabel])
        }
        try container.encodeIfPresent(self.openChatLabel, forKey: .openChatLabel)
        try container.encodeIfPresent(self.subtitle, forKey: .subtitle)
        if let value = tasks {
            try CommaNativeContractValidation.validateArrayForEncoding(value, minimumItems: nil, maximumItems: 100, codingPath: container.codingPath + [CodingKeys.tasks])
        }
        try container.encodeIfPresent(self.tasks, forKey: .tasks)
        try container.encodeIfPresent(self.title, forKey: .title)
    }

    private enum CodingKeys: String, CodingKey {
        case airDrop = "airDrop"
        case compactSideWidth = "compactSideWidth"
        case detail = "detail"
        case hasActivity = "hasActivity"
        case listSubtitle = "listSubtitle"
        case listTitle = "listTitle"
        case notify = "notify"
        case openChatLabel = "openChatLabel"
        case subtitle = "subtitle"
        case tasks = "tasks"
        case title = "title"
    }
}

public struct CommaNotchScenePayloadAirDrop: Codable, Equatable, Sendable {
    public let transfer: CommaNotchScenePayloadAirDropTransfer?

    public init(
        transfer: CommaNotchScenePayloadAirDropTransfer? = nil
    ) {
        self.transfer = transfer
    }

    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        self.transfer = try CommaNativeContractValidation.decodeOptional(CommaNotchScenePayloadAirDropTransfer.self, from: container, forKey: .transfer)
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(self.transfer, forKey: .transfer)
    }

    private enum CodingKeys: String, CodingKey {
        case transfer = "transfer"
    }
}

public struct CommaNotchScenePayloadAirDropTransfer: Codable, Equatable, Sendable {
    public let acceptLabel: String?
    public let declineLabel: String?
    public let phase: CommaNotchScenePayloadAirDropTransferPhase
    public let preview: String?
    public let progress: Double?
    public let requestId: String
    public let subtitle: String?
    public let title: String

    public init(
        acceptLabel: String? = nil,
        declineLabel: String? = nil,
        phase: CommaNotchScenePayloadAirDropTransferPhase,
        preview: String? = nil,
        progress: Double? = nil,
        requestId: String,
        subtitle: String? = nil,
        title: String
    ) {
        self.acceptLabel = acceptLabel
        self.declineLabel = declineLabel
        self.phase = phase
        self.preview = preview
        self.progress = progress
        self.requestId = requestId
        self.subtitle = subtitle
        self.title = title
    }

    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        self.acceptLabel = try CommaNativeContractValidation.decodeOptionalString(String.self, from: container, forKey: .acceptLabel, minimumLength: nil, maximumLength: 64)
        self.declineLabel = try CommaNativeContractValidation.decodeOptionalString(String.self, from: container, forKey: .declineLabel, minimumLength: nil, maximumLength: 64)
        self.phase = try container.decode(CommaNotchScenePayloadAirDropTransferPhase.self, forKey: .phase)
        self.preview = try CommaNativeContractValidation.decodeOptionalString(String.self, from: container, forKey: .preview, minimumLength: nil, maximumLength: 700000)
        self.progress = try CommaNativeContractValidation.decodeOptionalNumber(Double.self, from: container, forKey: .progress, minimum: 0, maximum: 1)
        self.requestId = try CommaNativeContractValidation.decodeString(String.self, from: container, forKey: .requestId, minimumLength: 1, maximumLength: 64)
        self.subtitle = try CommaNativeContractValidation.decodeOptionalString(String.self, from: container, forKey: .subtitle, minimumLength: nil, maximumLength: 512)
        self.title = try CommaNativeContractValidation.decodeString(String.self, from: container, forKey: .title, minimumLength: nil, maximumLength: 256)
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        if let value = acceptLabel {
            try CommaNativeContractValidation.validateStringForEncoding(value, minimumLength: nil, maximumLength: 64, codingPath: container.codingPath + [CodingKeys.acceptLabel])
        }
        try container.encodeIfPresent(self.acceptLabel, forKey: .acceptLabel)
        if let value = declineLabel {
            try CommaNativeContractValidation.validateStringForEncoding(value, minimumLength: nil, maximumLength: 64, codingPath: container.codingPath + [CodingKeys.declineLabel])
        }
        try container.encodeIfPresent(self.declineLabel, forKey: .declineLabel)
        try container.encode(self.phase, forKey: .phase)
        if let value = preview {
            try CommaNativeContractValidation.validateStringForEncoding(value, minimumLength: nil, maximumLength: 700000, codingPath: container.codingPath + [CodingKeys.preview])
        }
        try container.encodeIfPresent(self.preview, forKey: .preview)
        if let value = progress {
            try CommaNativeContractValidation.validateNumberForEncoding(value, minimum: 0, maximum: 1, codingPath: container.codingPath + [CodingKeys.progress])
        }
        try container.encodeIfPresent(self.progress, forKey: .progress)
        try CommaNativeContractValidation.validateStringForEncoding(requestId, minimumLength: 1, maximumLength: 64, codingPath: container.codingPath + [CodingKeys.requestId])
        try container.encode(self.requestId, forKey: .requestId)
        if let value = subtitle {
            try CommaNativeContractValidation.validateStringForEncoding(value, minimumLength: nil, maximumLength: 512, codingPath: container.codingPath + [CodingKeys.subtitle])
        }
        try container.encodeIfPresent(self.subtitle, forKey: .subtitle)
        try CommaNativeContractValidation.validateStringForEncoding(title, minimumLength: nil, maximumLength: 256, codingPath: container.codingPath + [CodingKeys.title])
        try container.encode(self.title, forKey: .title)
    }

    private enum CodingKeys: String, CodingKey {
        case acceptLabel = "acceptLabel"
        case declineLabel = "declineLabel"
        case phase = "phase"
        case preview = "preview"
        case progress = "progress"
        case requestId = "requestId"
        case subtitle = "subtitle"
        case title = "title"
    }
}

public enum CommaNotchScenePayloadAirDropTransferPhase: String, Codable, Equatable, Sendable {
    case offer = "offer"
    case receiving = "receiving"
    case completed = "completed"
    case failed = "failed"
}

public struct CommaNotchScenePayloadTask: Codable, Equatable, Sendable {
    public let conversationId: String
    public let groupId: String
    public let id: String
    public let status: CommaNotchScenePayloadTaskStatus
    public let subtitle: String
    public let title: String
    public let updatedAt: Double
    public let workspaceId: String

    public init(
        conversationId: String,
        groupId: String,
        id: String,
        status: CommaNotchScenePayloadTaskStatus = .inProgress,
        subtitle: String,
        title: String,
        updatedAt: Double,
        workspaceId: String
    ) {
        self.conversationId = conversationId
        self.groupId = groupId
        self.id = id
        self.status = status
        self.subtitle = subtitle
        self.title = title
        self.updatedAt = updatedAt
        self.workspaceId = workspaceId
    }

    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        self.conversationId = try CommaNativeContractValidation.decodeString(String.self, from: container, forKey: .conversationId, minimumLength: 1, maximumLength: 256)
        self.groupId = try CommaNativeContractValidation.decodeString(String.self, from: container, forKey: .groupId, minimumLength: 1, maximumLength: 256)
        self.id = try CommaNativeContractValidation.decodeString(String.self, from: container, forKey: .id, minimumLength: 1, maximumLength: 256)
        self.status = try container.decode(CommaNotchScenePayloadTaskStatus.self, forKey: .status)
        guard self.status == .inProgress else {
            throw DecodingError.dataCorruptedError(
                forKey: .status,
                in: container,
                debugDescription: "Unexpected constant value for status."
            )
        }
        self.subtitle = try CommaNativeContractValidation.decodeString(String.self, from: container, forKey: .subtitle, minimumLength: nil, maximumLength: 2048)
        self.title = try CommaNativeContractValidation.decodeString(String.self, from: container, forKey: .title, minimumLength: nil, maximumLength: 2048)
        self.updatedAt = try container.decode(Double.self, forKey: .updatedAt)
        self.workspaceId = try CommaNativeContractValidation.decodeString(String.self, from: container, forKey: .workspaceId, minimumLength: 1, maximumLength: 256)
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try CommaNativeContractValidation.validateStringForEncoding(conversationId, minimumLength: 1, maximumLength: 256, codingPath: container.codingPath + [CodingKeys.conversationId])
        try container.encode(self.conversationId, forKey: .conversationId)
        try CommaNativeContractValidation.validateStringForEncoding(groupId, minimumLength: 1, maximumLength: 256, codingPath: container.codingPath + [CodingKeys.groupId])
        try container.encode(self.groupId, forKey: .groupId)
        try CommaNativeContractValidation.validateStringForEncoding(id, minimumLength: 1, maximumLength: 256, codingPath: container.codingPath + [CodingKeys.id])
        try container.encode(self.id, forKey: .id)
        guard self.status == .inProgress else {
            throw EncodingError.invalidValue(
                self.status,
                EncodingError.Context(
                    codingPath: container.codingPath + [CodingKeys.status],
                    debugDescription: "Unexpected constant value for status."
                )
            )
        }
        try container.encode(self.status, forKey: .status)
        try CommaNativeContractValidation.validateStringForEncoding(subtitle, minimumLength: nil, maximumLength: 2048, codingPath: container.codingPath + [CodingKeys.subtitle])
        try container.encode(self.subtitle, forKey: .subtitle)
        try CommaNativeContractValidation.validateStringForEncoding(title, minimumLength: nil, maximumLength: 2048, codingPath: container.codingPath + [CodingKeys.title])
        try container.encode(self.title, forKey: .title)
        try container.encode(self.updatedAt, forKey: .updatedAt)
        try CommaNativeContractValidation.validateStringForEncoding(workspaceId, minimumLength: 1, maximumLength: 256, codingPath: container.codingPath + [CodingKeys.workspaceId])
        try container.encode(self.workspaceId, forKey: .workspaceId)
    }

    private enum CodingKeys: String, CodingKey {
        case conversationId = "conversationId"
        case groupId = "groupId"
        case id = "id"
        case status = "status"
        case subtitle = "subtitle"
        case title = "title"
        case updatedAt = "updatedAt"
        case workspaceId = "workspaceId"
    }
}

public enum CommaNotchScenePayloadTaskStatus: String, Codable, Equatable, Sendable {
    case inProgress = "in_progress"
}
